#!/usr/bin/env python3
"""Generates tests/lz4_block/kat.h: reference-lz4 (liblz4 via python `lz4.block`) compressed forms of
deterministic inputs. Run: PYTHONPATH=<dir with lz4> python3 gen_kat.py > kat.h"""
import lz4.block as B, random
random.seed(490)
def inputs():
    yield b"a"
    yield b"hello hello hello hello hello hello hello hello!"
    yield bytes(range(256)) * 3
    yield b"\x00" * 1000
    yield (b"EDGE.GAME arcade cabinet " * 40)
    yield bytes(random.randrange(256) for _ in range(300))
    yield bytes(random.choice(b"abcd") for _ in range(4000))
    yield b"x" * 15 + b"y" * 300 + b"zzzzzzzzzzzzzzzzzzzzzzzzzzzz"
cases = list(inputs())
print("/* generated by gen_kat.py from liblz4 (python lz4.block) -- do not edit */")
for i, d in enumerate(cases):
    c = B.compress(d, store_size=False, mode="default")
    print("static const unsigned char kat_raw_%d[] = {%s};" % (i, ",".join(str(x) for x in d)))
    print("static const unsigned char kat_lz4_%d[] = {%s};" % (i, ",".join(str(x) for x in c)))
print("typedef struct { const unsigned char *raw; int raw_len; const unsigned char *lz4; int lz4_len; } LzKat;")
print("static const LzKat kats[] = {")
for i in range(len(cases)):
    print("  {kat_raw_%d, (int)sizeof(kat_raw_%d), kat_lz4_%d, (int)sizeof(kat_lz4_%d)}," % (i,i,i,i))
print("};")
print("#define N_KATS %d" % len(cases))
