/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline __attribute__((unused)) ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

typedef struct {
    char * text;
    int cursor;
    int selection_anchor;
} Buffer;
static inline __attribute__((unused)) Buffer Buffer_new(char * text, int cursor, int selection_anchor) {
    Buffer v;
    v.text = text;
    v.cursor = cursor;
    v.selection_anchor = selection_anchor;
    return v;
}

typedef enum {
    BufferError_TAG_OutOfRange,
} BufferError_Tag;
typedef struct { BufferError_Tag tag; void *value; } BufferError;
static inline __attribute__((unused)) BufferError BufferError_OutOfRange(void) { BufferError v; v.tag = BufferError_TAG_OutOfRange; v.value = NULL; return v; }

typedef struct {
    Buffer buf;
    int current_version;
    int last_edit_epoch;
} Document;
static inline __attribute__((unused)) Document Document_new(Buffer buf, int current_version, int last_edit_epoch) {
    Document v;
    v.buf = buf;
    v.current_version = current_version;
    v.last_edit_epoch = last_edit_epoch;
    return v;
}

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
char * char_from_code(int, Arena *);
char * i32_to_string(int, Arena *);
int contains_ci_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
double parse_f64_raw(char *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
Buffer new(Arena *);
Buffer from_text(char *);
char * active_text(Buffer *);
int cursor_pos(Buffer *);
Result insert(Buffer *, int, char *, Arena *);
Result delete_range(Buffer *, int, int, Arena *);
Result insert_at_cursor(Buffer *, char *, Arena *);
Result backspace_at_cursor(Buffer *, Arena *);
Buffer move_cursor_left(Buffer *);
Buffer move_cursor_right(Buffer *);
Buffer move_cursor_home(Buffer *);
Buffer move_cursor_end(Buffer *);
Buffer move_cursor_up(Buffer *);
Buffer move_cursor_down(Buffer *);
int line_start_before(char *, int);
int line_end_after(char *, int, int);
Result delete_forward_at_cursor(Buffer *, Arena *);
int has_selection_(Buffer *);
int selection_start(Buffer *);
int selection_end(Buffer *);
Buffer extend_selection_left(Buffer *);
Buffer extend_selection_right(Buffer *);
Buffer extend_selection_up(Buffer *);
Buffer extend_selection_down(Buffer *);
Result delete_selection(Buffer *, Arena *);
Buffer set_cursor(Buffer *, int);
Buffer set_selection(Buffer *, int, int);
int max_versions_per_note();
int coalesce_window_seconds();
int on_papercraft_should_coalesce_edit(int);
int on_papercraft_version_to_evict(int);
int on_papercraft_has_version_conflict(int, int);
Document new_document(int, Arena *);
Document apply_edit(Document, char *, int, Arena *);
char * document_text(Document *);
int document_version(Document *);
int document_cursor(Document *);

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

static inline BufferError *BufferError_box(Arena *dest, BufferError v) {
    BufferError *p = (BufferError *)arena_alloc(dest, sizeof(BufferError));
    *p = v;
    return p;
}

static inline Buffer *Buffer_box(Arena *dest, Buffer v) {
    Buffer *p = (Buffer *)arena_alloc(dest, sizeof(Buffer));
    *p = v;
    return p;
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

char * char_from_code(int code __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (1) + 1);
    out[0] = (char)code; out[1] = '\0';
    return out;
}

char * i32_to_string(int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (16) + 1);
    snprintf(out, 16, "%d", n);
    return out;
}

int contains_ci_(char * haystack __attribute__((unused)), char * needle __attribute__((unused))) {
    return (string_contains_ci_impl(haystack, needle) != 0);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

double parse_f64_raw(char * s __attribute__((unused))) {
    return (strtod(s, NULL));
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    double i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    double start = 0;
    double i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        double __recur_tmp_0 = start;
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

Buffer new(Arena *dest __attribute__((unused))) {
    return Buffer_new("", 0, -1);
}

Buffer from_text(char * text __attribute__((unused))) {
    return Buffer_new(text, length(text), -1);
}

char * active_text(Buffer * buf __attribute__((unused))) {
    return (buf)->text;
}

int cursor_pos(Buffer * buf __attribute__((unused))) {
    return (buf)->cursor;
}

Result insert(Buffer * buf __attribute__((unused)), int pos __attribute__((unused)), char * text __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *cur __attribute__((unused)) = (buf)->text;
    int len __attribute__((unused)) = length(cur);
    if (((pos < 0) || (pos > len))) {
    return result_err(BufferError_box(dest, BufferError_OutOfRange()));
    } else {
    char *before __attribute__((unused)) = substring(cur, 0, pos, dest);
    char *after __attribute__((unused)) = substring(cur, pos, len, dest);
    char *combined __attribute__((unused)) = concat(concat(before, text, dest), after, dest);
    return result_ok(Buffer_box(dest, Buffer_new(combined, (buf)->cursor, -1)));
    }
}

Result delete_range(Buffer * buf __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *cur __attribute__((unused)) = (buf)->text;
    int len __attribute__((unused)) = length(cur);
    if ((((start < 0) || (end > len)) || (start > end))) {
    return result_err(BufferError_box(dest, BufferError_OutOfRange()));
    } else {
    char *before __attribute__((unused)) = substring(cur, 0, start, dest);
    char *after __attribute__((unused)) = substring(cur, end, len, dest);
    return result_ok(Buffer_box(dest, Buffer_new(concat(before, after, dest), (buf)->cursor, -1)));
    }
}

Result insert_at_cursor(Buffer * buf __attribute__((unused)), char * text __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int pos __attribute__((unused)) = (buf)->cursor;
    char *cur __attribute__((unused)) = (buf)->text;
    int len __attribute__((unused)) = length(cur);
    if (((pos < 0) || (pos > len))) {
    return result_err(BufferError_box(dest, BufferError_OutOfRange()));
    } else {
    char *before __attribute__((unused)) = substring(cur, 0, pos, dest);
    char *after __attribute__((unused)) = substring(cur, pos, len, dest);
    char *combined __attribute__((unused)) = concat(concat(before, text, dest), after, dest);
    int advance __attribute__((unused)) = length(text);
    return result_ok(Buffer_box(dest, Buffer_new(combined, (pos + advance), -1)));
    }
}

Result backspace_at_cursor(Buffer * buf __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int pos __attribute__((unused)) = (buf)->cursor;
    if ((pos <= 0)) {
    return result_err(BufferError_box(dest, BufferError_OutOfRange()));
    } else {
    char *cur __attribute__((unused)) = (buf)->text;
    int len __attribute__((unused)) = length(cur);
    char *before __attribute__((unused)) = substring(cur, 0, (pos - 1), dest);
    char *after __attribute__((unused)) = substring(cur, pos, len, dest);
    return result_ok(Buffer_box(dest, Buffer_new(concat(before, after, dest), (pos - 1), -1)));
    }
}

Buffer move_cursor_left(Buffer * buf __attribute__((unused))) {
    int pos __attribute__((unused)) = (buf)->cursor;
    char *text __attribute__((unused)) = (buf)->text;
    if ((pos <= 0)) {
    return Buffer_new(text, 0, -1);
    } else {
    return Buffer_new(text, (pos - 1), -1);
    }
}

Buffer move_cursor_right(Buffer * buf __attribute__((unused))) {
    int pos __attribute__((unused)) = (buf)->cursor;
    char *text __attribute__((unused)) = (buf)->text;
    int len __attribute__((unused)) = length(text);
    if ((pos >= len)) {
    return Buffer_new(text, len, -1);
    } else {
    return Buffer_new(text, (pos + 1), -1);
    }
}

Buffer move_cursor_home(Buffer * buf __attribute__((unused))) {
    int pos __attribute__((unused)) = (buf)->cursor;
    char *text __attribute__((unused)) = (buf)->text;
    return Buffer_new(text, line_start_before(text, pos), -1);
}

Buffer move_cursor_end(Buffer * buf __attribute__((unused))) {
    int pos __attribute__((unused)) = (buf)->cursor;
    char *text __attribute__((unused)) = (buf)->text;
    return Buffer_new(text, line_end_after(text, pos, length(text)), -1);
}

Buffer move_cursor_up(Buffer * buf __attribute__((unused))) {
    char *text __attribute__((unused)) = (buf)->text;
    int cursor __attribute__((unused)) = (buf)->cursor;
    int cur_line_start __attribute__((unused)) = line_start_before(text, cursor);
    int column __attribute__((unused)) = (cursor - cur_line_start);
    if ((cur_line_start <= 0)) {
    return Buffer_new(text, cursor, -1);
    } else {
    int prev_line_end __attribute__((unused)) = (cur_line_start - 1);
    int prev_line_start __attribute__((unused)) = line_start_before(text, prev_line_end);
    int prev_line_len __attribute__((unused)) = (prev_line_end - prev_line_start);
    int target_col __attribute__((unused)) = ((column < prev_line_len) ? column : prev_line_len);
    return Buffer_new(text, (prev_line_start + target_col), -1);
    }
}

Buffer move_cursor_down(Buffer * buf __attribute__((unused))) {
    char *text __attribute__((unused)) = (buf)->text;
    int cursor __attribute__((unused)) = (buf)->cursor;
    int len __attribute__((unused)) = length(text);
    int cur_line_start __attribute__((unused)) = line_start_before(text, cursor);
    int column __attribute__((unused)) = (cursor - cur_line_start);
    int cur_line_end __attribute__((unused)) = line_end_after(text, cursor, len);
    if ((cur_line_end >= len)) {
    return Buffer_new(text, cursor, -1);
    } else {
    int next_line_start __attribute__((unused)) = (cur_line_end + 1);
    int next_line_end __attribute__((unused)) = line_end_after(text, next_line_start, len);
    int next_line_len __attribute__((unused)) = (next_line_end - next_line_start);
    int target_col __attribute__((unused)) = ((column < next_line_len) ? column : next_line_len);
    return Buffer_new(text, (next_line_start + target_col), -1);
    }
}

int line_start_before(char * text __attribute__((unused)), int pos __attribute__((unused))) {
    if ((pos <= 0)) {
    return 0;
    } else {
    if ((char_at(text, (pos - 1)) == 10)) {
    return pos;
    } else {
    return line_start_before(text, (pos - 1));
    }
    }
}

int line_end_after(char * text __attribute__((unused)), int pos __attribute__((unused)), int len __attribute__((unused))) {
    if ((pos >= len)) {
    return len;
    } else {
    if ((char_at(text, pos) == 10)) {
    return pos;
    } else {
    return line_end_after(text, (pos + 1), len);
    }
    }
}

Result delete_forward_at_cursor(Buffer * buf __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int pos __attribute__((unused)) = (buf)->cursor;
    char *cur __attribute__((unused)) = (buf)->text;
    int len __attribute__((unused)) = length(cur);
    if ((pos >= len)) {
    return result_err(BufferError_box(dest, BufferError_OutOfRange()));
    } else {
    char *before __attribute__((unused)) = substring(cur, 0, pos, dest);
    char *after __attribute__((unused)) = substring(cur, (pos + 1), len, dest);
    return result_ok(Buffer_box(dest, Buffer_new(concat(before, after, dest), pos, -1)));
    }
}

int has_selection_(Buffer * buf __attribute__((unused))) {
    return ((buf)->selection_anchor >= 0);
}

int selection_start(Buffer * buf __attribute__((unused))) {
    int a __attribute__((unused)) = (buf)->selection_anchor;
    int c __attribute__((unused)) = (buf)->cursor;
    if ((a < c)) {
    return a;
    } else {
    return c;
    }
}

int selection_end(Buffer * buf __attribute__((unused))) {
    int a __attribute__((unused)) = (buf)->selection_anchor;
    int c __attribute__((unused)) = (buf)->cursor;
    if ((a > c)) {
    return a;
    } else {
    return c;
    }
}

Buffer extend_selection_left(Buffer * buf __attribute__((unused))) {
    char *text __attribute__((unused)) = (buf)->text;
    int cursor __attribute__((unused)) = (buf)->cursor;
    int anchor __attribute__((unused)) = (buf)->selection_anchor;
    int real_anchor __attribute__((unused)) = ((anchor < 0) ? cursor : anchor);
    double new_cursor __attribute__((unused)) = ((cursor <= 0) ? 0 : (cursor - 1));
    return Buffer_new(text, new_cursor, real_anchor);
}

Buffer extend_selection_right(Buffer * buf __attribute__((unused))) {
    char *text __attribute__((unused)) = (buf)->text;
    int cursor __attribute__((unused)) = (buf)->cursor;
    int len __attribute__((unused)) = length(text);
    int anchor __attribute__((unused)) = (buf)->selection_anchor;
    int real_anchor __attribute__((unused)) = ((anchor < 0) ? cursor : anchor);
    int new_cursor __attribute__((unused)) = ((cursor >= len) ? len : (cursor + 1));
    return Buffer_new(text, new_cursor, real_anchor);
}

Buffer extend_selection_up(Buffer * buf __attribute__((unused))) {
    char *text __attribute__((unused)) = (buf)->text;
    int cursor __attribute__((unused)) = (buf)->cursor;
    int anchor __attribute__((unused)) = (buf)->selection_anchor;
    int real_anchor __attribute__((unused)) = ((anchor < 0) ? cursor : anchor);
    int cur_line_start __attribute__((unused)) = line_start_before(text, cursor);
    int column __attribute__((unused)) = (cursor - cur_line_start);
    if ((cur_line_start <= 0)) {
    return Buffer_new(text, cursor, real_anchor);
    } else {
    int prev_line_end __attribute__((unused)) = (cur_line_start - 1);
    int prev_line_start __attribute__((unused)) = line_start_before(text, prev_line_end);
    int prev_line_len __attribute__((unused)) = (prev_line_end - prev_line_start);
    int target_col __attribute__((unused)) = ((column < prev_line_len) ? column : prev_line_len);
    return Buffer_new(text, (prev_line_start + target_col), real_anchor);
    }
}

Buffer extend_selection_down(Buffer * buf __attribute__((unused))) {
    char *text __attribute__((unused)) = (buf)->text;
    int cursor __attribute__((unused)) = (buf)->cursor;
    int len __attribute__((unused)) = length(text);
    int anchor __attribute__((unused)) = (buf)->selection_anchor;
    int real_anchor __attribute__((unused)) = ((anchor < 0) ? cursor : anchor);
    int cur_line_start __attribute__((unused)) = line_start_before(text, cursor);
    int column __attribute__((unused)) = (cursor - cur_line_start);
    int cur_line_end __attribute__((unused)) = line_end_after(text, cursor, len);
    if ((cur_line_end >= len)) {
    return Buffer_new(text, cursor, real_anchor);
    } else {
    int next_line_start __attribute__((unused)) = (cur_line_end + 1);
    int next_line_end __attribute__((unused)) = line_end_after(text, next_line_start, len);
    int next_line_len __attribute__((unused)) = (next_line_end - next_line_start);
    int target_col __attribute__((unused)) = ((column < next_line_len) ? column : next_line_len);
    return Buffer_new(text, (next_line_start + target_col), real_anchor);
    }
}

Result delete_selection(Buffer * buf __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (has_selection_(buf)) {
    int start __attribute__((unused)) = selection_start(buf);
    int end __attribute__((unused)) = selection_end(buf);
    char *text __attribute__((unused)) = (buf)->text;
    int len __attribute__((unused)) = length(text);
    char *before __attribute__((unused)) = substring(text, 0, start, dest);
    char *after __attribute__((unused)) = substring(text, end, len, dest);
    return result_ok(Buffer_box(dest, Buffer_new(concat(before, after, dest), start, -1)));
    } else {
    return result_err(BufferError_box(dest, BufferError_OutOfRange()));
    }
}

Buffer set_cursor(Buffer * buf __attribute__((unused)), int pos __attribute__((unused))) {
    char *text __attribute__((unused)) = (buf)->text;
    int len __attribute__((unused)) = length(text);
    double clamped __attribute__((unused)) = ((pos < 0) ? 0 : ((pos > len) ? len : pos));
    return Buffer_new(text, clamped, -1);
}

Buffer set_selection(Buffer * buf __attribute__((unused)), int anchor __attribute__((unused)), int cursor __attribute__((unused))) {
    char *text __attribute__((unused)) = (buf)->text;
    int len __attribute__((unused)) = length(text);
    double clamped_anchor __attribute__((unused)) = ((anchor < 0) ? 0 : ((anchor > len) ? len : anchor));
    double clamped_cursor __attribute__((unused)) = ((cursor < 0) ? 0 : ((cursor > len) ? len : cursor));
    return Buffer_new(text, clamped_cursor, clamped_anchor);
}

int max_versions_per_note(void) {
    return 50;
}

int coalesce_window_seconds(void) {
    return 30;
}

int on_papercraft_should_coalesce_edit(int seconds_since_last_edit __attribute__((unused))) {
    return (seconds_since_last_edit < coalesce_window_seconds());
}

int on_papercraft_version_to_evict(int current_version_count __attribute__((unused))) {
    if ((current_version_count < max_versions_per_note())) {
    return -1;
    } else {
    return 0;
    }
}

int on_papercraft_has_version_conflict(int edit_based_on_version __attribute__((unused)), int current_version __attribute__((unused))) {
    return (!((edit_based_on_version == current_version)));
}

Document new_document(int now_epoch __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return Document_new(new(dest), 1, now_epoch);
}

Document apply_edit(Document doc __attribute__((unused)), char * new_text __attribute__((unused)), int now_epoch __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int seconds_since_last __attribute__((unused)) = (now_epoch - (doc).last_edit_epoch);
    Buffer new_buf __attribute__((unused)) = from_text(new_text);
    if (on_papercraft_should_coalesce_edit(seconds_since_last)) {
    return Document_new(new_buf, (doc).current_version, now_epoch);
    } else {
    return Document_new(new_buf, ((doc).current_version + 1), now_epoch);
    }
}

char * document_text(Document * doc __attribute__((unused))) {
    return active_text(&((doc)->buf));
}

int document_version(Document * doc __attribute__((unused))) {
    return (doc)->current_version;
}

int document_cursor(Document * doc __attribute__((unused))) {
    return cursor_pos(&((doc)->buf));
}

