/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline __attribute__((unused)) ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

typedef struct {
    Vec data;
    Vec shape;
    Vec strides;
} NDArray;
static inline __attribute__((unused)) NDArray NDArray_new(Vec data, Vec shape, Vec strides) {
    NDArray v;
    v.data = data;
    v.shape = shape;
    v.strides = strides;
    return v;
}

typedef struct {
    char * message;
} ShapeError;
static inline __attribute__((unused)) ShapeError ShapeError_new(char * message) {
    ShapeError v;
    v.message = message;
    return v;
}

typedef struct {
    char * message;
} IndexError;
static inline __attribute__((unused)) IndexError IndexError_new(char * message) {
    IndexError v;
    v.message = message;
    return v;
}

typedef struct {
    Vec slots;
    int capacity;
    int count;
} StringSet;
static inline __attribute__((unused)) StringSet StringSet_new(Vec slots, int capacity, int count) {
    StringSet v;
    v.slots = slots;
    v.capacity = capacity;
    v.count = count;
    return v;
}

typedef enum {
    SetError_TAG_Full,
} SetError_Tag;
typedef struct { SetError_Tag tag; void *value; } SetError;
static inline __attribute__((unused)) SetError SetError_Full(void) { SetError v; v.tag = SetError_TAG_Full; v.value = NULL; return v; }

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
char * char_from_code(int, Arena *);
char * i32_to_string(int, Arena *);
int contains_ci_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
double parse_f64_raw(char *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
int product(Vec *);
Vec strides_for(Vec *, Arena *);
NDArray zeros(Vec, Arena *);
Result from_vec(Vec, Vec, Arena *);
int flat_index(NDArray *, Vec *);
Result array_get(NDArray *, Vec, Arena *);
Result set_(NDArray *, Vec, double, Arena *);
Result reshape(NDArray *, Vec, Arena *);
int same_shape_(NDArray *, NDArray *);
Result elementwise(NDArray *, NDArray *, double (*)(double, double), Arena *);
Result add(NDArray *, NDArray *, Arena *);
Result mul_elementwise(NDArray *, NDArray *, Arena *);
int fnv_offset_basis();
int fnv1a_hash(char *, int);
void init_slots_(Vec *, int);
StringSet set_new(int, Arena *);
int find_slot(StringSet *, char *, int);
void maybe_insert_(StringSet *, int, char *, int);
Result set_add_(StringSet *, char *, Arena *);
int set_contains_(StringSet *, char *);
int set_size(StringSet *);
void maybe_push_member_(Vec *, char *);
Result maybe_add_member_(StringSet *, char *, Arena *);
Result maybe_add_if_in_(StringSet *, StringSet *, char *, Arena *);
Result maybe_add_if_not_in_(StringSet *, StringSet *, char *, Arena *);
Vec set_to_vec(StringSet *, Arena *);
StringSet set_intersect(StringSet *, StringSet *, Arena *);
StringSet set_union(StringSet *, StringSet *, Arena *);
StringSet set_difference(StringSet *, StringSet *, Arena *);

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

static inline NDArray *NDArray_box(Arena *dest, NDArray v) {
    NDArray *p = (NDArray *)arena_alloc(dest, sizeof(NDArray));
    *p = v;
    return p;
}

static inline ShapeError *ShapeError_box(Arena *dest, ShapeError v) {
    ShapeError *p = (ShapeError *)arena_alloc(dest, sizeof(ShapeError));
    *p = v;
    return p;
}

static inline IndexError *IndexError_box(Arena *dest, IndexError v) {
    IndexError *p = (IndexError *)arena_alloc(dest, sizeof(IndexError));
    *p = v;
    return p;
}

static inline double *double_box(Arena *dest, double v) {
    double *p = (double *)arena_alloc(dest, sizeof(double));
    *p = v;
    return p;
}

static inline SetError *SetError_box(Arena *dest, SetError v) {
    SetError *p = (SetError *)arena_alloc(dest, sizeof(SetError));
    *p = v;
    return p;
}

static inline int int_vec_eq(Vec *a, Vec *b) {
    if (vec_len(a) != vec_len(b)) return 0;
    for (int i = 0; i < vec_len(a); i++) {
        if (*(int *)vec_get(a, i) != *(int *)vec_get(b, i)) return 0;
    }
    return 1;
}

static double __lambda_0(double x, double y) {
    return (x + y);
}

static double __lambda_1(double x, double y) {
    return (x * y);
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

char * char_from_code(int code __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (1) + 1);
    out[0] = (char)code; out[1] = '\0';
    return out;
}

char * i32_to_string(int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (16) + 1);
    snprintf(out, 16, "%d", n);
    return out;
}

int contains_ci_(char * haystack __attribute__((unused)), char * needle __attribute__((unused))) {
    return (string_contains_ci_impl(haystack, needle) != 0);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

double parse_f64_raw(char * s __attribute__((unused))) {
    return (strtod(s, NULL));
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    double i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    double start = 0;
    double i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        double __recur_tmp_0 = start;
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

int product(Vec * shape __attribute__((unused))) {
    double __loop_result_2 __attribute__((unused));
    double i = 0;
    double acc = 1;
    while (1) {
        if ((i >= vec_len(shape))) {
        __loop_result_2 = acc;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (acc * (*((int *)(vec_get(shape, i)))));
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_2;
}

Vec strides_for(Vec * shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = vec_len(shape);
    int total __attribute__((unused)) = product(shape);
    Vec s __attribute__((unused)) = vec_new(dest);
    void * __loop_result_3 __attribute__((unused));
    double i = 0;
    int running = total;
    while (1) {
        if ((i < n)) {
        int next __attribute__((unused)) = (running / (*((int *)(vec_get(shape, i)))));
        (void)(vec_push_(&(s), vec_box_i32(&(s), next)));
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = next;
        i = __recur_tmp_0;
        running = __recur_tmp_1;
        continue;
        } else {
            break;
        }
    }
    return s;
}

NDArray zeros(Vec shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = product(&(shape));
    Vec data __attribute__((unused)) = vec_new(dest);
    void * __loop_result_4 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < n)) {
    (void)(vec_push_(&(data), vec_box_f64(&(data), 0.0)));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return NDArray_new(data, shape, strides_for(&(shape), dest));
}

Result from_vec(Vec data __attribute__((unused)), Vec shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((vec_len(&(data)) == product(&(shape)))) {
    return result_ok(NDArray_box(dest, NDArray_new(data, shape, strides_for(&(shape), dest))));
    } else {
    return result_err(ShapeError_box(dest, ShapeError_new("data length does not match shape product")));
    }
}

int flat_index(NDArray * a __attribute__((unused)), Vec * idx __attribute__((unused))) {
    double __loop_result_5 __attribute__((unused));
    double i = 0;
    double offset = 0;
    while (1) {
        if ((i >= vec_len(idx))) {
        __loop_result_5 = offset;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (offset + ((*((int *)(vec_get(idx, i)))) * (*((int *)(vec_get(&((a)->strides), i))))));
        i = __recur_tmp_0;
        offset = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_5;
}

Result array_get(NDArray * a __attribute__((unused)), Vec idx __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int off __attribute__((unused)) = flat_index(a, &(idx));
    if (((off < 0) || (off >= vec_len(&((a)->data))))) {
    return result_err(IndexError_box(dest, IndexError_new("out of bounds")));
    } else {
    return result_ok(double_box(dest, (*((double *)(vec_get(&((a)->data), off))))));
    }
}

Result set_(NDArray * a __attribute__((unused)), Vec idx __attribute__((unused)), double v __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int off __attribute__((unused)) = flat_index(a, &(idx));
    if (((off < 0) || (off >= vec_len(&((a)->data))))) {
    return result_err(IndexError_box(dest, IndexError_new("out of bounds")));
    } else {
    (void)(vec_set_at_(&((a)->data), off, vec_box_f64(&((a)->data), v)));
    return result_ok(NULL);
    }
}

Result reshape(NDArray * a __attribute__((unused)), Vec new_shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((product(&(new_shape)) == product(&((a)->shape)))) {
    return result_ok(NDArray_box(dest, NDArray_new((a)->data, new_shape, strides_for(&(new_shape), dest))));
    } else {
    return result_err(ShapeError_box(dest, ShapeError_new("reshape must preserve element count")));
    }
}

int same_shape_(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused))) {
    return int_vec_eq(&((a)->shape), &((b)->shape));
}

Result elementwise(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), double (*op)(double, double) __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!(same_shape_(a, b)))) {
    return result_err(ShapeError_box(dest, ShapeError_new("shape mismatch")));
    } else {
    int n __attribute__((unused)) = vec_len(&((a)->data));
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_6 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < n)) {
    (void)(vec_push_(&(out), vec_box_f64(&(out), op((*((double *)(vec_get(&((a)->data), i)))), (*((double *)(vec_get(&((b)->data), i))))))));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return result_ok(NDArray_box(dest, NDArray_new(out, (a)->shape, (a)->strides)));
    }
}

Result add(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return elementwise(a, b, __lambda_0, dest);
}

Result mul_elementwise(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return elementwise(a, b, __lambda_1, dest);
}

int fnv_offset_basis(void) {
    return -2128831035;
}

int fnv1a_hash(char * s __attribute__((unused)), int n __attribute__((unused))) {
    int __loop_result_7 __attribute__((unused));
    double i = 0;
    int h = fnv_offset_basis();
    while (1) {
        if ((i >= n)) {
        __loop_result_7 = h;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = ((h ^ char_at(s, i)) * 16777619);
        i = __recur_tmp_0;
        h = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_7;
}

void init_slots_(Vec * slots __attribute__((unused)), int remaining __attribute__((unused))) {
    void * __loop_result_8 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < remaining)) {
    (void)(vec_push_(slots, ""));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
}

StringSet set_new(int capacity __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec slots __attribute__((unused)) = vec_new(dest);
    (void)(init_slots_(&(slots), capacity));
    return StringSet_new(slots, capacity, 0);
}

int find_slot(StringSet * s __attribute__((unused)), char * key __attribute__((unused)), int n __attribute__((unused))) {
    int capacity __attribute__((unused)) = (s)->capacity;
    int start __attribute__((unused)) = ((fnv1a_hash(key, n) & 2147483647) % capacity);
    int __loop_result_9 __attribute__((unused));
    int i = start;
    double probes = 0;
    while (1) {
        char *slot_val __attribute__((unused)) = vec_get(&((s)->slots), i);
        if ((length(slot_val) == 0)) {
        __loop_result_9 = i;
        break;
        } else {
        if (str_eq_(slot_val, key)) {
        __loop_result_9 = i;
        break;
        } else {
        if (((probes + 1) >= capacity)) {
        __loop_result_9 = -1;
        break;
        } else {
        int __recur_tmp_0 = ((i + 1) % capacity);
        double __recur_tmp_1 = (probes + 1);
        i = __recur_tmp_0;
        probes = __recur_tmp_1;
        continue;
        }
        }
        }
    }
    return __loop_result_9;
}

void maybe_insert_(StringSet * s __attribute__((unused)), int slot __attribute__((unused)), char * key __attribute__((unused)), int was_empty __attribute__((unused))) {
    if (was_empty) {
    (void)(vec_set_at_(&((s)->slots), slot, key));
    (void)(((s)->count = ((s)->count + 1)));
    } else {
    (void)(NULL);
    }
}

Result set_add_(StringSet * s __attribute__((unused)), char * key __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = length(key);
    int slot __attribute__((unused)) = find_slot(s, key, n);
    if ((slot < 0)) {
    return result_err(SetError_box(dest, SetError_Full()));
    } else {
    char *existing __attribute__((unused)) = vec_get(&((s)->slots), slot);
    (void)(maybe_insert_(s, slot, key, (length(existing) == 0)));
    return result_ok(NULL);
    }
}

int set_contains_(StringSet * s __attribute__((unused)), char * key __attribute__((unused))) {
    int n __attribute__((unused)) = length(key);
    int slot __attribute__((unused)) = find_slot(s, key, n);
    return ((slot >= 0) && (length(vec_get(&((s)->slots), slot)) > 0));
}

int set_size(StringSet * s __attribute__((unused))) {
    return (s)->count;
}

void maybe_push_member_(Vec * out __attribute__((unused)), char * v __attribute__((unused))) {
    if ((length(v) > 0)) {
    (void)(vec_push_(out, v));
    } else {
    (void)(NULL);
    }
}

Result maybe_add_member_(StringSet * out __attribute__((unused)), char * v __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((length(v) > 0)) {
    return set_add_(out, v, dest);
    } else {
    return result_ok(NULL);
    }
}

Result maybe_add_if_in_(StringSet * out __attribute__((unused)), StringSet * b __attribute__((unused)), char * v __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (((length(v) > 0) && set_contains_(b, v))) {
    return set_add_(out, v, dest);
    } else {
    return result_ok(NULL);
    }
}

Result maybe_add_if_not_in_(StringSet * out __attribute__((unused)), StringSet * b __attribute__((unused)), char * v __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (((length(v) > 0) && (!(set_contains_(b, v))))) {
    return set_add_(out, v, dest);
    } else {
    return result_ok(NULL);
    }
}

Vec set_to_vec(StringSet * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_10 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < (s)->capacity)) {
    (void)(maybe_push_member_(&(out), vec_get(&((s)->slots), i)));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return out;
}

StringSet set_intersect(StringSet * a __attribute__((unused)), StringSet * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    StringSet out __attribute__((unused)) = set_new(((a)->count + 1), dest);
    void * __loop_result_11 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < (a)->capacity)) {
    (void)(maybe_add_if_in_(&(out), b, vec_get(&((a)->slots), i), dest));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return out;
}

StringSet set_union(StringSet * a __attribute__((unused)), StringSet * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    StringSet out __attribute__((unused)) = set_new((((a)->count + (b)->count) + 1), dest);
    void * __loop_result_12 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < (a)->capacity)) {
    (void)(maybe_add_member_(&(out), vec_get(&((a)->slots), i), dest));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    void * __loop_result_13 __attribute__((unused));
    double j = 0;
    while (1) {
        if ((j < (b)->capacity)) {
    (void)(maybe_add_member_(&(out), vec_get(&((b)->slots), j), dest));
        double __recur_tmp_0 = (j + 1);
        j = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return out;
}

StringSet set_difference(StringSet * a __attribute__((unused)), StringSet * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    StringSet out __attribute__((unused)) = set_new(((a)->count + 1), dest);
    void * __loop_result_14 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < (a)->capacity)) {
    (void)(maybe_add_if_not_in_(&(out), b, vec_get(&((a)->slots), i), dest));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return out;
}

