/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline __attribute__((unused)) ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

typedef struct {
    Bytes encapsulation_key;
    Bytes decapsulation_key;
} KemKeyPair;
static inline __attribute__((unused)) KemKeyPair KemKeyPair_new(Bytes encapsulation_key, Bytes decapsulation_key) {
    KemKeyPair v;
    v.encapsulation_key = encapsulation_key;
    v.decapsulation_key = decapsulation_key;
    return v;
}

typedef struct {
    Bytes ciphertext;
    Bytes shared_secret;
} KemEncaps;
static inline __attribute__((unused)) KemEncaps KemEncaps_new(Bytes ciphertext, Bytes shared_secret) {
    KemEncaps v;
    v.ciphertext = ciphertext;
    v.shared_secret = shared_secret;
    return v;
}

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
char * char_from_code(int, Arena *);
char * i32_to_string(int, Arena *);
int contains_ci_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
double parse_f64_raw(char *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
Bytes bytes_alloc(int, Arena *);
int bytes_len(Bytes);
int bytes_get(Bytes, int);
void bytes_set_(Bytes, int, int);
Bytes bytes_from_string(char *, Arena *);
char * bytes_to_string_lossy(Bytes, Arena *);
Bytes bytes_slice(Bytes, int, int, Arena *);
int aead_key_bytes();
int aead_nonce_bytes();
int aead_mac_bytes();
Bytes aead_seal(Bytes, Bytes, Bytes, Bytes, Arena *);
Bytes aead_open(Bytes, Bytes, Bytes, Bytes, Arena *);
Bytes aead_kdf(Bytes, Bytes, Arena *);
int lz4_max_input();
int lz4_compress_bound(int);
int lz4b_hash4(Bytes, int);
int lz4b_table_get(Bytes, int);
int lz4b_table_put_(Bytes, int, int);
int lz4b_zero_fill_(Bytes, int);
int lz4b_put_byte_(Bytes, int, int);
int lz4b_put_le16_(Bytes, int, int);
int lz4b_put_ext_(Bytes, int, int);
int lz4b_copy_bytes_(Bytes, int, Bytes, int, int);
int lz4b_emit_seq_(Bytes, int, Bytes, int, int, int, int);
int lz4b_emit_last_(Bytes, int, Bytes, int, int);
int lz4b_match_extend(Bytes, int, int, int);
int lz4b_same4_(Bytes, int, int);
Bytes lz4_compress_block(Bytes, Arena *);
int lz4b_ext_sum(Bytes, int, int);
int lz4b_ext_end(Bytes, int);
int lz4b_copy_match_(Bytes, int, int, int);
int lz4b_decode_loop(Bytes, int, Bytes, int);
Bytes lz4_decompress_block(Bytes, int, Arena *);
int mlkem_ek_bytes();
int mlkem_dk_bytes();
int mlkem_ct_bytes();
int mlkem_ss_bytes();
Bytes mlkem_raw_keygen(Arena *);
Bytes mlkem_raw_encaps(Bytes, Arena *);
Bytes mlkem_raw_decaps(Bytes, Bytes, Arena *);
KemKeyPair mlkem_keygen(Arena *);
KemEncaps mlkem_encaps(Bytes, Arena *);
Bytes mlkem_decaps(Bytes, Bytes, Arena *);
int sc_max_message();
int sc_dir_c2s();
int sc_dir_s2c();
Bytes sc_label(int, Arena *);
Bytes sc_derive_key(Bytes, int, Arena *);
Bytes sc_fingerprint(Bytes, Arena *);
int sc_put_byte_(Bytes, int, int);
int sc_put_le32_(Bytes, int, int);
int sc_get_le32(Bytes, int);
int sc_zero_(Bytes, int);
int sc_copy_into_(Bytes, int, Bytes, int);
Bytes sc_make_nonce(int, int, Arena *);
Bytes sc_make_ad(int, int, Arena *);
Bytes sc_frame_seal(Bytes, int, int, Bytes, Arena *);
Bytes sc_frame_open(Bytes, int, int, Bytes, Arena *);

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

char * char_from_code(int code __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (1) + 1);
    out[0] = (char)code; out[1] = '\0';
    return out;
}

char * i32_to_string(int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (16) + 1);
    snprintf(out, 16, "%d", n);
    return out;
}

int contains_ci_(char * haystack __attribute__((unused)), char * needle __attribute__((unused))) {
    return (string_contains_ci_impl(haystack, needle) != 0);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

double parse_f64_raw(char * s __attribute__((unused))) {
    return (strtod(s, NULL));
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    int i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        int __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    int start = 0;
    int i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        int __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        int __recur_tmp_0 = start;
        int __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

Bytes bytes_alloc(int len __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (bytes_alloc_impl(dest, len));
}

int bytes_len(Bytes b __attribute__((unused))) {
    return (bytes_len_impl(b));
}

int bytes_get(Bytes b __attribute__((unused)), int idx __attribute__((unused))) {
    return (bytes_get_impl(b, idx));
}

void bytes_set_(Bytes b __attribute__((unused)), int idx __attribute__((unused)), int val __attribute__((unused))) {
    bytes_set_impl(b, idx, val);
}

Bytes bytes_from_string(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (bytes_from_string_impl(dest, s));
}

char * bytes_to_string_lossy(Bytes b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (bytes_to_string_lossy_impl(b, dest));
}

Bytes bytes_slice(Bytes b __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (bytes_slice_impl(b, start, end, dest));
}

int aead_key_bytes(void) {
    return 32;
}

int aead_nonce_bytes(void) {
    return 24;
}

int aead_mac_bytes(void) {
    return 16;
}

Bytes aead_seal(Bytes key __attribute__((unused)), Bytes nonce __attribute__((unused)), Bytes ad __attribute__((unused)), Bytes plain __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (aead_seal_impl(key, nonce, ad, plain, dest));
}

Bytes aead_open(Bytes key __attribute__((unused)), Bytes nonce __attribute__((unused)), Bytes ad __attribute__((unused)), Bytes sealed __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (aead_open_impl(key, nonce, ad, sealed, dest));
}

Bytes aead_kdf(Bytes secret __attribute__((unused)), Bytes label __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (aead_kdf_impl(secret, label, dest));
}

int lz4_max_input(void) {
    return 65535;
}

int lz4_compress_bound(int n __attribute__((unused))) {
    return (n + ((n / 255) + 16));
}

int lz4b_hash4(Bytes src __attribute__((unused)), int p __attribute__((unused))) {
    return (((bytes_get(src, p) * 31) + ((bytes_get(src, (p + 1)) * 131) + ((bytes_get(src, (p + 2)) * 257) + (bytes_get(src, (p + 3)) * 521)))) % 4096);
}

int lz4b_table_get(Bytes t __attribute__((unused)), int h __attribute__((unused))) {
    return ((bytes_get(t, (h * 2)) + (bytes_get(t, ((h * 2) + 1)) * 256)) - 1);
}

int lz4b_table_put_(Bytes t __attribute__((unused)), int h __attribute__((unused)), int pos __attribute__((unused))) {
    if ((pos < 65535)) {
    (void)(bytes_set_(t, (h * 2), ((pos + 1) % 256)));
    (void)(bytes_set_(t, ((h * 2) + 1), ((pos + 1) / 256)));
    return 0;
    } else {
    return 0;
    }
}

int lz4b_zero_fill_(Bytes b __attribute__((unused)), int n __attribute__((unused))) {
    int __loop_result_2 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i >= n)) {
        __loop_result_2 = 0;
        break;
        } else {
        (void)(bytes_set_(b, i, 0));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
    }
    return __loop_result_2;
}

int lz4b_put_byte_(Bytes out __attribute__((unused)), int op __attribute__((unused)), int v __attribute__((unused))) {
    (void)(bytes_set_(out, op, v));
    return (op + 1);
}

int lz4b_put_le16_(Bytes out __attribute__((unused)), int op __attribute__((unused)), int v __attribute__((unused))) {
    (void)(bytes_set_(out, op, (v % 256)));
    (void)(bytes_set_(out, (op + 1), (v / 256)));
    return (op + 2);
}

int lz4b_put_ext_(Bytes out __attribute__((unused)), int op __attribute__((unused)), int rem __attribute__((unused))) {
    int __loop_result_3 __attribute__((unused));
    int o = op;
    int r = rem;
    while (1) {
        if ((r >= 255)) {
        (void)(bytes_set_(out, o, 255));
        int __recur_tmp_0 = (o + 1);
        int __recur_tmp_1 = (r - 255);
        o = __recur_tmp_0;
        r = __recur_tmp_1;
        continue;
        } else {
        (void)(bytes_set_(out, o, r));
        __loop_result_3 = (o + 1);
        break;
        }
    }
    return __loop_result_3;
}

int lz4b_copy_bytes_(Bytes out __attribute__((unused)), int op __attribute__((unused)), Bytes src __attribute__((unused)), int from __attribute__((unused)), int cnt __attribute__((unused))) {
    int __loop_result_4 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i >= cnt)) {
        __loop_result_4 = (op + cnt);
        break;
        } else {
        (void)(bytes_set_(out, (op + i), bytes_get(src, (from + i))));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
    }
    return __loop_result_4;
}

int lz4b_emit_seq_(Bytes out __attribute__((unused)), int op __attribute__((unused)), Bytes src __attribute__((unused)), int anchor __attribute__((unused)), int pos __attribute__((unused)), int offset __attribute__((unused)), int ml __attribute__((unused))) {
    int ll __attribute__((unused)) = (pos - anchor);
    int mlx __attribute__((unused)) = (ml - 4);
    int tok __attribute__((unused)) = ((((ll >= 15) ? 15 : ll) * 16) + ((mlx >= 15) ? 15 : mlx));
    int o1 __attribute__((unused)) = lz4b_put_byte_(out, op, tok);
    int o2 __attribute__((unused)) = ((ll >= 15) ? lz4b_put_ext_(out, o1, (ll - 15)) : o1);
    int o3 __attribute__((unused)) = lz4b_copy_bytes_(out, o2, src, anchor, ll);
    int o4 __attribute__((unused)) = lz4b_put_le16_(out, o3, offset);
    if ((mlx >= 15)) {
    return lz4b_put_ext_(out, o4, (mlx - 15));
    } else {
    return o4;
    }
}

int lz4b_emit_last_(Bytes out __attribute__((unused)), int op __attribute__((unused)), Bytes src __attribute__((unused)), int anchor __attribute__((unused)), int n __attribute__((unused))) {
    int ll __attribute__((unused)) = (n - anchor);
    int o1 __attribute__((unused)) = lz4b_put_byte_(out, op, (((ll >= 15) ? 15 : ll) * 16));
    int o2 __attribute__((unused)) = ((ll >= 15) ? lz4b_put_ext_(out, o1, (ll - 15)) : o1);
    return lz4b_copy_bytes_(out, o2, src, anchor, ll);
}

int lz4b_match_extend(Bytes src __attribute__((unused)), int cand __attribute__((unused)), int pos __attribute__((unused)), int limit __attribute__((unused))) {
    int __loop_result_5 __attribute__((unused));
    int l = 4;
    while (1) {
        if (((pos + l) >= limit)) {
        __loop_result_5 = l;
        break;
        } else {
        if ((bytes_get(src, (cand + l)) == bytes_get(src, (pos + l)))) {
        int __recur_tmp_0 = (l + 1);
        l = __recur_tmp_0;
        continue;
        } else {
        __loop_result_5 = l;
        break;
        }
        }
    }
    return __loop_result_5;
}

int lz4b_same4_(Bytes src __attribute__((unused)), int a __attribute__((unused)), int b __attribute__((unused))) {
    return ((bytes_get(src, a) == bytes_get(src, b)) && ((bytes_get(src, (a + 1)) == bytes_get(src, (b + 1))) && ((bytes_get(src, (a + 2)) == bytes_get(src, (b + 2))) && (bytes_get(src, (a + 3)) == bytes_get(src, (b + 3))))));
}

Bytes lz4_compress_block(Bytes src __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = bytes_len(src);
    if (((n == 0) || (n > 65535))) {
    return bytes_alloc(0, dest);
    } else {
    Bytes out __attribute__((unused)) = bytes_alloc(lz4_compress_bound(n), dest);
    Bytes table __attribute__((unused)) = bytes_alloc(8192, dest);
    int z __attribute__((unused)) = lz4b_zero_fill_(table, 8192);
    int last_match_start __attribute__((unused)) = (n - 12);
    int match_limit __attribute__((unused)) = (n - 5);
    Bytes __loop_result_6 __attribute__((unused));
    int pos = 0;
    int anchor = 0;
    int op = 0;
    while (1) {
        if ((pos > last_match_start)) {
        __loop_result_6 = bytes_slice(out, 0, lz4b_emit_last_(out, op, src, anchor, n), dest);
        break;
        } else {
        int h __attribute__((unused)) = lz4b_hash4(src, pos);
        int cand __attribute__((unused)) = lz4b_table_get(table, h);
        int z2 __attribute__((unused)) = lz4b_table_put_(table, h, pos);
        if (((cand >= 0) && (((pos - cand) <= 65535) && lz4b_same4_(src, cand, pos)))) {
        int ml __attribute__((unused)) = lz4b_match_extend(src, cand, pos, match_limit);
        int op2 __attribute__((unused)) = lz4b_emit_seq_(out, op, src, anchor, pos, (pos - cand), ml);
        int __recur_tmp_0 = (pos + ml);
        int __recur_tmp_1 = (pos + ml);
        int __recur_tmp_2 = op2;
        pos = __recur_tmp_0;
        anchor = __recur_tmp_1;
        op = __recur_tmp_2;
        continue;
        } else {
        int __recur_tmp_0 = (pos + 1);
        int __recur_tmp_1 = anchor;
        int __recur_tmp_2 = op;
        pos = __recur_tmp_0;
        anchor = __recur_tmp_1;
        op = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_6;
    }
}

int lz4b_ext_sum(Bytes src __attribute__((unused)), int ip __attribute__((unused)), int n __attribute__((unused))) {
    int __loop_result_7 __attribute__((unused));
    int i = ip;
    int acc = 0;
    while (1) {
        if ((i >= n)) {
        __loop_result_7 = -1;
        break;
        } else {
        int b __attribute__((unused)) = bytes_get(src, i);
        if ((b == 255)) {
        int __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (acc + 255);
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        } else {
        __loop_result_7 = (acc + b);
        break;
        }
        }
    }
    return __loop_result_7;
}

int lz4b_ext_end(Bytes src __attribute__((unused)), int ip __attribute__((unused))) {
    int __loop_result_8 __attribute__((unused));
    int i = ip;
    while (1) {
        if ((bytes_get(src, i) == 255)) {
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
        __loop_result_8 = (i + 1);
        break;
        }
    }
    return __loop_result_8;
}

int lz4b_copy_match_(Bytes out __attribute__((unused)), int op __attribute__((unused)), int offset __attribute__((unused)), int ml __attribute__((unused))) {
    int __loop_result_9 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i >= ml)) {
        __loop_result_9 = (op + ml);
        break;
        } else {
        (void)(bytes_set_(out, (op + i), bytes_get(out, ((op + i) - offset))));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
    }
    return __loop_result_9;
}

int lz4b_decode_loop(Bytes src __attribute__((unused)), int n __attribute__((unused)), Bytes out __attribute__((unused)), int olen __attribute__((unused))) {
    int __loop_result_10 __attribute__((unused));
    int ip = 0;
    int op = 0;
    while (1) {
        if ((ip >= n)) {
        __loop_result_10 = -1;
        break;
        } else {
        int tok __attribute__((unused)) = bytes_get(src, ip);
        int ll0 __attribute__((unused)) = (tok / 16);
        int ip1 __attribute__((unused)) = (ip + 1);
        int llx __attribute__((unused)) = ((ll0 == 15) ? lz4b_ext_sum(src, ip1, n) : 0);
        if ((llx < 0)) {
        __loop_result_10 = -1;
        break;
        } else {
        int ll __attribute__((unused)) = (ll0 + llx);
        int ip2 __attribute__((unused)) = ((ll0 == 15) ? lz4b_ext_end(src, ip1) : ip1);
        if ((((ip2 + ll) > n) || ((op + ll) > olen))) {
        __loop_result_10 = -1;
        break;
        } else {
        int op1 __attribute__((unused)) = lz4b_copy_bytes_(out, op, src, ip2, ll);
        int ip3 __attribute__((unused)) = (ip2 + ll);
        if ((ip3 == n)) {
        __loop_result_10 = op1;
        break;
        } else {
        if (((ip3 + 2) > n)) {
        __loop_result_10 = -1;
        break;
        } else {
        int offset __attribute__((unused)) = (bytes_get(src, ip3) + (bytes_get(src, (ip3 + 1)) * 256));
        int ip4 __attribute__((unused)) = (ip3 + 2);
        int ml0 __attribute__((unused)) = (tok % 16);
        int mlx __attribute__((unused)) = ((ml0 == 15) ? lz4b_ext_sum(src, ip4, n) : 0);
        if (((mlx < 0) || ((offset == 0) || (offset > op1)))) {
        __loop_result_10 = -1;
        break;
        } else {
        int ml __attribute__((unused)) = ((ml0 + mlx) + 4);
        int ip5 __attribute__((unused)) = ((ml0 == 15) ? lz4b_ext_end(src, ip4) : ip4);
        if (((op1 + ml) > olen)) {
        __loop_result_10 = -1;
        break;
        } else {
        int __recur_tmp_0 = ip5;
        int __recur_tmp_1 = lz4b_copy_match_(out, op1, offset, ml);
        ip = __recur_tmp_0;
        op = __recur_tmp_1;
        continue;
        }
        }
        }
        }
        }
        }
        }
    }
    return __loop_result_10;
}

Bytes lz4_decompress_block(Bytes src __attribute__((unused)), int out_len __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = bytes_len(src);
    if (((out_len <= 0) || ((n == 0) || (out_len > 4194304)))) {
    return bytes_alloc(0, dest);
    } else {
    Bytes out __attribute__((unused)) = bytes_alloc(out_len, dest);
    int end __attribute__((unused)) = lz4b_decode_loop(src, n, out, out_len);
    if ((end == out_len)) {
    return out;
    } else {
    return bytes_alloc(0, dest);
    }
    }
}

int mlkem_ek_bytes(void) {
    return 1184;
}

int mlkem_dk_bytes(void) {
    return 2400;
}

int mlkem_ct_bytes(void) {
    return 1088;
}

int mlkem_ss_bytes(void) {
    return 32;
}

Bytes mlkem_raw_keygen(Arena *dest __attribute__((unused))) {
    return (mlkem_keygen_impl(dest));
}

Bytes mlkem_raw_encaps(Bytes ek __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (mlkem_encaps_impl(ek, dest));
}

Bytes mlkem_raw_decaps(Bytes ct __attribute__((unused)), Bytes dk __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (mlkem_decaps_impl(ct, dk, dest));
}

KemKeyPair mlkem_keygen(Arena *dest __attribute__((unused))) {
    Bytes blob __attribute__((unused)) = mlkem_raw_keygen(dest);
    return KemKeyPair_new(bytes_slice(blob, 0, mlkem_ek_bytes(), dest), bytes_slice(blob, mlkem_ek_bytes(), (mlkem_ek_bytes() + mlkem_dk_bytes()), dest));
}

KemEncaps mlkem_encaps(Bytes ek __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Bytes blob __attribute__((unused)) = mlkem_raw_encaps(ek, dest);
    if ((bytes_len(blob) == 0)) {
    return KemEncaps_new(blob, blob);
    } else {
    return KemEncaps_new(bytes_slice(blob, 0, mlkem_ct_bytes(), dest), bytes_slice(blob, mlkem_ct_bytes(), (mlkem_ct_bytes() + mlkem_ss_bytes()), dest));
    }
}

Bytes mlkem_decaps(Bytes ct __attribute__((unused)), Bytes dk __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return mlkem_raw_decaps(ct, dk, dest);
}

int sc_max_message(void) {
    return 60000;
}

int sc_dir_c2s(void) {
    return 1;
}

int sc_dir_s2c(void) {
    return 2;
}

Bytes sc_label(int dir __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Bytes b __attribute__((unused)) = bytes_alloc(8, dest);
    (void)(bytes_set_(b, 0, 101));
    (void)(bytes_set_(b, 1, 100));
    (void)(bytes_set_(b, 2, 103));
    (void)(bytes_set_(b, 3, 101));
    (void)(bytes_set_(b, 4, 45));
    (void)(bytes_set_(b, 5, ((dir == 1) ? 99 : 115)));
    (void)(bytes_set_(b, 6, 50));
    (void)(bytes_set_(b, 7, ((dir == 1) ? 115 : 99)));
    return b;
}

Bytes sc_derive_key(Bytes shared_secret __attribute__((unused)), int dir __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return aead_kdf(shared_secret, sc_label(dir, dest), dest);
}

Bytes sc_fingerprint(Bytes ek __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Bytes tag __attribute__((unused)) = bytes_alloc(4, dest);
    (void)(bytes_set_(tag, 0, 112));
    (void)(bytes_set_(tag, 1, 105));
    (void)(bytes_set_(tag, 2, 110));
    (void)(bytes_set_(tag, 3, 49));
    return aead_kdf(ek, tag, dest);
}

int sc_put_byte_(Bytes b __attribute__((unused)), int off __attribute__((unused)), int v __attribute__((unused))) {
    (void)(bytes_set_(b, off, v));
    return 0;
}

int sc_put_le32_(Bytes b __attribute__((unused)), int off __attribute__((unused)), int v __attribute__((unused))) {
    (void)(bytes_set_(b, off, (v % 256)));
    (void)(bytes_set_(b, (off + 1), ((v / 256) % 256)));
    (void)(bytes_set_(b, (off + 2), ((v / 65536) % 256)));
    (void)(bytes_set_(b, (off + 3), ((v / 16777216) % 256)));
    return 0;
}

int sc_get_le32(Bytes b __attribute__((unused)), int off __attribute__((unused))) {
    return (bytes_get(b, off) + ((bytes_get(b, (off + 1)) * 256) + ((bytes_get(b, (off + 2)) * 65536) + (bytes_get(b, (off + 3)) * 16777216))));
}

int sc_zero_(Bytes b __attribute__((unused)), int n __attribute__((unused))) {
    int __loop_result_11 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i >= n)) {
        __loop_result_11 = 0;
        break;
        } else {
        (void)(bytes_set_(b, i, 0));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
    }
    return __loop_result_11;
}

int sc_copy_into_(Bytes out __attribute__((unused)), int op __attribute__((unused)), Bytes src __attribute__((unused)), int cnt __attribute__((unused))) {
    int __loop_result_12 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i >= cnt)) {
        __loop_result_12 = (op + cnt);
        break;
        } else {
        (void)(bytes_set_(out, (op + i), bytes_get(src, i)));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
    }
    return __loop_result_12;
}

Bytes sc_make_nonce(int dir __attribute__((unused)), int ctr __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Bytes n __attribute__((unused)) = bytes_alloc(24, dest);
    int z __attribute__((unused)) = sc_zero_(n, 24);
    (void)(bytes_set_(n, 0, dir));
    (void)(sc_put_le32_(n, 20, ctr));
    return n;
}

Bytes sc_make_ad(int dir __attribute__((unused)), int ctr __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Bytes a __attribute__((unused)) = bytes_alloc(5, dest);
    (void)(bytes_set_(a, 0, dir));
    (void)(sc_put_le32_(a, 1, ctr));
    return a;
}

Bytes sc_frame_seal(Bytes key __attribute__((unused)), int dir __attribute__((unused)), int ctr __attribute__((unused)), Bytes msg __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = bytes_len(msg);
    if (((n < 1) || ((n > sc_max_message()) || ((ctr < 0) || (!((bytes_len(key) == 32))))))) {
    return bytes_alloc(0, dest);
    } else {
    Bytes lz __attribute__((unused)) = lz4_compress_block(msg, dest);
    int use_lz __attribute__((unused)) = ((bytes_len(lz) > 0) && (bytes_len(lz) < n));
    int blen __attribute__((unused)) = (use_lz ? bytes_len(lz) : n);
    Bytes plain __attribute__((unused)) = bytes_alloc((5 + blen), dest);
    int z __attribute__((unused)) = sc_put_byte_(plain, 0, (use_lz ? 1 : 0));
    int z2 __attribute__((unused)) = sc_put_le32_(plain, 1, n);
    int z3 __attribute__((unused)) = sc_copy_into_(plain, 5, (use_lz ? lz : msg), blen);
    Bytes sealed __attribute__((unused)) = aead_seal(key, sc_make_nonce(dir, ctr, dest), sc_make_ad(dir, ctr, dest), plain, dest);
    if ((bytes_len(sealed) == 0)) {
    return sealed;
    } else {
    Bytes wire __attribute__((unused)) = bytes_alloc((4 + bytes_len(sealed)), dest);
    int w1 __attribute__((unused)) = sc_put_le32_(wire, 0, ctr);
    int w2 __attribute__((unused)) = sc_copy_into_(wire, 4, sealed, bytes_len(sealed));
    return wire;
    }
    }
}

Bytes sc_frame_open(Bytes key __attribute__((unused)), int dir __attribute__((unused)), int expect_ctr __attribute__((unused)), Bytes wire __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (((bytes_len(wire) < 22) || ((!((bytes_len(key) == 32))) || (!((sc_get_le32(wire, 0) == expect_ctr)))))) {
    return bytes_alloc(0, dest);
    } else {
    Bytes sealed __attribute__((unused)) = bytes_slice(wire, 4, bytes_len(wire), dest);
    Bytes plain __attribute__((unused)) = aead_open(key, sc_make_nonce(dir, expect_ctr, dest), sc_make_ad(dir, expect_ctr, dest), sealed, dest);
    int pl __attribute__((unused)) = bytes_len(plain);
    if ((pl < 6)) {
    return bytes_alloc(0, dest);
    } else {
    int flag __attribute__((unused)) = bytes_get(plain, 0);
    int rawlen __attribute__((unused)) = sc_get_le32(plain, 1);
    Bytes body __attribute__((unused)) = bytes_slice(plain, 5, pl, dest);
    if (((rawlen < 1) || (rawlen > sc_max_message()))) {
    return bytes_alloc(0, dest);
    } else {
    if ((flag == 0)) {
    if ((bytes_len(body) == rawlen)) {
    return body;
    } else {
    return bytes_alloc(0, dest);
    }
    } else {
    if ((flag == 1)) {
    return lz4_decompress_block(body, rawlen, dest);
    } else {
    return bytes_alloc(0, dest);
    }
    }
    }
    }
    }
}

