/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline __attribute__((unused)) ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

typedef struct {
    int kind;
    char * text;
} JsToken;
static inline __attribute__((unused)) JsToken JsToken_new(int kind, char * text) {
    JsToken v;
    v.kind = kind;
    v.text = text;
    return v;
}

typedef struct {
    int kind;
    char * text;
    int a;
    int b;
} AstExpr;
static inline __attribute__((unused)) AstExpr AstExpr_new(int kind, char * text, int a, int b) {
    AstExpr v;
    v.kind = kind;
    v.text = text;
    v.a = a;
    v.b = b;
    return v;
}

typedef struct {
    int expr;
    int next;
} AstArg;
static inline __attribute__((unused)) AstArg AstArg_new(int expr, int next) {
    AstArg v;
    v.expr = expr;
    v.next = next;
    return v;
}

typedef struct {
    Vec toks;
    int pos;
    Vec exprs;
    Vec args;
} PState;
static inline __attribute__((unused)) PState PState_new(Vec toks, int pos, Vec exprs, Vec args) {
    PState v;
    v.toks = toks;
    v.pos = pos;
    v.exprs = exprs;
    v.args = args;
    return v;
}

typedef struct {
    PState state;
    int root;
} ParseResult;
static inline __attribute__((unused)) ParseResult ParseResult_new(PState state, int root) {
    ParseResult v;
    v.state = state;
    v.root = root;
    return v;
}

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
char * char_from_code(int, Arena *);
char * i32_to_string(int, Arena *);
int contains_ci_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
double parse_f64_raw(char *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
int tok_number();
int tok_string();
int tok_ident();
int tok_punct();
int tok_eof();
int is_alpha_(int);
int is_ident_char_(int);
int is_punct_(int);
int is_space_(int);
int scan_number(char *, int, int);
int scan_ident(char *, int, int);
int scan_string(char *, int, int);
Vec lex(char *, Arena *);
int expr_num();
int expr_str();
int expr_ident();
int expr_binary();
int expr_call();
JsToken * cur_tok(PState *);
void advance_(PState *);
int tok_is_punct_(PState *, char *);
int push_expr_(PState *, Arena *, int, char *, int, int);
int parse_args(PState *, Arena *);
void link_prev_arg_(PState *, int, int);
void parse_args_rest_body_(PState *, Arena *, int);
void parse_args_rest_(PState *, Arena *, int);
int parse_call_body(PState *, Arena *, char *);
int parse_call(PState *, Arena *, char *);
int parse_paren_body(PState *, Arena *);
int parse_paren_expr(PState *, Arena *);
int parse_number_lit(PState *, Arena *, JsToken *);
int parse_string_lit(PState *, Arena *, JsToken *);
int parse_ident_or_call(PState *, Arena *, JsToken *);
int parse_primary(PState *, Arena *);
int mul_op_step(PState *, Arena *, char *, int);
int add_op_step(PState *, Arena *, char *, int);
int cmp_op_step(PState *, Arena *, char *, int);
int parse_multiplicative(PState *, Arena *);
int parse_additive(PState *, Arena *);
int parse_comparison(PState *, Arena *);
ParseResult parse(Vec, Arena *);

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

static inline JsToken *JsToken_box(Arena *dest, JsToken v) {
    JsToken *p = (JsToken *)arena_alloc(dest, sizeof(JsToken));
    *p = v;
    return p;
}

static inline AstExpr *AstExpr_box(Arena *dest, AstExpr v) {
    AstExpr *p = (AstExpr *)arena_alloc(dest, sizeof(AstExpr));
    *p = v;
    return p;
}

static inline AstArg *AstArg_box(Arena *dest, AstArg v) {
    AstArg *p = (AstArg *)arena_alloc(dest, sizeof(AstArg));
    *p = v;
    return p;
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

char * char_from_code(int code __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (1) + 1);
    out[0] = (char)code; out[1] = '\0';
    return out;
}

char * i32_to_string(int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (16) + 1);
    snprintf(out, 16, "%d", n);
    return out;
}

int contains_ci_(char * haystack __attribute__((unused)), char * needle __attribute__((unused))) {
    return (string_contains_ci_impl(haystack, needle) != 0);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

double parse_f64_raw(char * s __attribute__((unused))) {
    return (strtod(s, NULL));
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    double i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    double start = 0;
    double i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        double __recur_tmp_0 = start;
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

int tok_number(void) {
    return 0;
}

int tok_string(void) {
    return 1;
}

int tok_ident(void) {
    return 2;
}

int tok_punct(void) {
    return 3;
}

int tok_eof(void) {
    return 4;
}

int is_alpha_(int c __attribute__((unused))) {
    return ((((c >= 65) && (c <= 90)) || ((c >= 97) && (c <= 122))) || (c == 95));
}

int is_ident_char_(int c __attribute__((unused))) {
    return (is_alpha_(c) || is_digit_(c));
}

int is_punct_(int c __attribute__((unused))) {
    return (((((((((((((c == 40) || (c == 41)) || (c == 123)) || (c == 125)) || (c == 59)) || (c == 44)) || (c == 43)) || (c == 45)) || (c == 42)) || (c == 47)) || (c == 61)) || (c == 60)) || (c == 62));
}

int is_space_(int c __attribute__((unused))) {
    return ((((c == 32) || (c == 9)) || (c == 10)) || (c == 13));
}

int scan_number(char * src __attribute__((unused)), int i __attribute__((unused)), int n __attribute__((unused))) {
    int __loop_result_2 __attribute__((unused));
    int j = i;
    while (1) {
        if (((j >= n) || (!(is_digit_(char_at(src, j)))))) {
        __loop_result_2 = j;
        break;
        } else {
        int __recur_tmp_0 = (j + 1);
        j = __recur_tmp_0;
        continue;
        }
    }
    return __loop_result_2;
}

int scan_ident(char * src __attribute__((unused)), int i __attribute__((unused)), int n __attribute__((unused))) {
    int __loop_result_3 __attribute__((unused));
    int j = i;
    while (1) {
        if (((j >= n) || (!(is_ident_char_(char_at(src, j)))))) {
        __loop_result_3 = j;
        break;
        } else {
        int __recur_tmp_0 = (j + 1);
        j = __recur_tmp_0;
        continue;
        }
    }
    return __loop_result_3;
}

int scan_string(char * src __attribute__((unused)), int i __attribute__((unused)), int n __attribute__((unused))) {
    int __loop_result_4 __attribute__((unused));
    int j = i;
    while (1) {
        if (((j >= n) || (char_at(src, j) == 34))) {
        __loop_result_4 = j;
        break;
        } else {
        int __recur_tmp_0 = (j + 1);
        j = __recur_tmp_0;
        continue;
        }
    }
    return __loop_result_4;
}

Vec lex(char * src __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = length(src);
    Vec toks __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_5 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(toks), JsToken_box(dest, JsToken_new(tok_eof(), ""))));
        __loop_result_5 = toks;
        break;
        } else {
        if (is_space_(char_at(src, i))) {
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
        if (is_digit_(char_at(src, i))) {
        int end __attribute__((unused)) = scan_number(src, i, n);
        (void)(vec_push_(&(toks), JsToken_box(dest, JsToken_new(tok_number(), substring(src, i, end, dest)))));
        double __recur_tmp_0 = end;
        i = __recur_tmp_0;
        continue;
        } else {
        if (is_alpha_(char_at(src, i))) {
        int end __attribute__((unused)) = scan_ident(src, i, n);
        (void)(vec_push_(&(toks), JsToken_box(dest, JsToken_new(tok_ident(), substring(src, i, end, dest)))));
        double __recur_tmp_0 = end;
        i = __recur_tmp_0;
        continue;
        } else {
        if ((char_at(src, i) == 34)) {
        int end __attribute__((unused)) = scan_string(src, (i + 1), n);
        (void)(vec_push_(&(toks), JsToken_box(dest, JsToken_new(tok_string(), substring(src, (i + 1), end, dest)))));
        if ((end < n)) {
        double __recur_tmp_0 = (end + 1);
        i = __recur_tmp_0;
        continue;
        } else {
        double __recur_tmp_0 = end;
        i = __recur_tmp_0;
        continue;
        }
        } else {
        if (is_punct_(char_at(src, i))) {
        (void)(vec_push_(&(toks), JsToken_box(dest, JsToken_new(tok_punct(), substring(src, i, (i + 1), dest)))));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
        }
        }
        }
        }
    }
    return __loop_result_5;
}

int expr_num(void) {
    return 0;
}

int expr_str(void) {
    return 1;
}

int expr_ident(void) {
    return 2;
}

int expr_binary(void) {
    return 3;
}

int expr_call(void) {
    return 4;
}

JsToken * cur_tok(PState * p __attribute__((unused))) {
    JsToken *t __attribute__((unused)) = vec_get(&((p)->toks), (p)->pos);
    return t;
}

void advance_(PState * p __attribute__((unused))) {
    (void)(((p)->pos = ((p)->pos + 1)));
}

int tok_is_punct_(PState * p __attribute__((unused)), char * ch __attribute__((unused))) {
    JsToken *t __attribute__((unused)) = cur_tok(p);
    return (((t)->kind == tok_punct()) && str_eq_((t)->text, ch));
}

int push_expr_(PState * p __attribute__((unused)), Arena *dest __attribute__((unused)), int kind __attribute__((unused)), char * text __attribute__((unused)), int a __attribute__((unused)), int b __attribute__((unused))) {
    int idx __attribute__((unused)) = vec_len(&((p)->exprs));
    (void)(vec_push_(&((p)->exprs), AstExpr_box(dest, AstExpr_new(kind, text, a, b))));
    return idx;
}

int parse_args(PState * p __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (tok_is_punct_(p, ")")) {
    (void)(advance_(p));
    return -1;
    } else {
    int first_expr __attribute__((unused)) = parse_comparison(p, dest);
    int first_idx __attribute__((unused)) = vec_len(&((p)->args));
    (void)(vec_push_(&((p)->args), AstArg_box(dest, AstArg_new(first_expr, -1))));
    (void)(parse_args_rest_(p, dest, first_idx));
    return first_idx;
    }
}

void link_prev_arg_(PState * p __attribute__((unused)), int prev_idx __attribute__((unused)), int next_idx __attribute__((unused))) {
    AstArg *prev_arg __attribute__((unused)) = vec_get(&((p)->args), prev_idx);
    (void)(((prev_arg)->next = next_idx));
}

void parse_args_rest_body_(PState * p __attribute__((unused)), Arena *dest __attribute__((unused)), int prev_idx __attribute__((unused))) {
    int next_expr __attribute__((unused)) = parse_comparison(p, dest);
    int next_idx __attribute__((unused)) = vec_len(&((p)->args));
    (void)(vec_push_(&((p)->args), AstArg_box(dest, AstArg_new(next_expr, -1))));
    (void)(link_prev_arg_(p, prev_idx, next_idx));
    (void)(parse_args_rest_(p, dest, next_idx));
}

void parse_args_rest_(PState * p __attribute__((unused)), Arena *dest __attribute__((unused)), int prev_idx __attribute__((unused))) {
    if (tok_is_punct_(p, ",")) {
    (void)(advance_(p));
    (void)(parse_args_rest_body_(p, dest, prev_idx));
    } else {
    (void)(advance_(p));
    }
}

int parse_call_body(PState * p __attribute__((unused)), Arena *dest __attribute__((unused)), char * callee_name __attribute__((unused))) {
    int callee_idx __attribute__((unused)) = push_expr_(p, dest, expr_ident(), callee_name, -1, -1);
    int first_arg __attribute__((unused)) = parse_args(p, dest);
    return push_expr_(p, dest, expr_call(), "", callee_idx, first_arg);
}

int parse_call(PState * p __attribute__((unused)), Arena *dest __attribute__((unused)), char * callee_name __attribute__((unused))) {
    (void)(advance_(p));
    return parse_call_body(p, dest, callee_name);
}

int parse_paren_body(PState * p __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int inner __attribute__((unused)) = parse_comparison(p, dest);
    (void)(advance_(p));
    return inner;
}

int parse_paren_expr(PState * p __attribute__((unused)), Arena *dest __attribute__((unused))) {
    (void)(advance_(p));
    return parse_paren_body(p, dest);
}

int parse_number_lit(PState * p __attribute__((unused)), Arena *dest __attribute__((unused)), JsToken * t __attribute__((unused))) {
    (void)(advance_(p));
    return push_expr_(p, dest, expr_num(), (t)->text, -1, -1);
}

int parse_string_lit(PState * p __attribute__((unused)), Arena *dest __attribute__((unused)), JsToken * t __attribute__((unused))) {
    (void)(advance_(p));
    return push_expr_(p, dest, expr_str(), (t)->text, -1, -1);
}

int parse_ident_or_call(PState * p __attribute__((unused)), Arena *dest __attribute__((unused)), JsToken * t __attribute__((unused))) {
    (void)(advance_(p));
    if (tok_is_punct_(p, "(")) {
    return parse_call(p, dest, (t)->text);
    } else {
    return push_expr_(p, dest, expr_ident(), (t)->text, -1, -1);
    }
}

int parse_primary(PState * p __attribute__((unused)), Arena *dest __attribute__((unused))) {
    JsToken *t __attribute__((unused)) = cur_tok(p);
    return (((t)->kind == tok_number()) ? parse_number_lit(p, dest, t) : (((t)->kind == tok_string()) ? parse_string_lit(p, dest, t) : (((t)->kind == tok_ident()) ? parse_ident_or_call(p, dest, t) : (tok_is_punct_(p, "(") ? parse_paren_expr(p, dest) : -1))));
}

int mul_op_step(PState * p __attribute__((unused)), Arena *dest __attribute__((unused)), char * op __attribute__((unused)), int acc __attribute__((unused))) {
    int right __attribute__((unused)) = parse_primary(p, dest);
    return push_expr_(p, dest, expr_binary(), op, acc, right);
}

int add_op_step(PState * p __attribute__((unused)), Arena *dest __attribute__((unused)), char * op __attribute__((unused)), int acc __attribute__((unused))) {
    int right __attribute__((unused)) = parse_multiplicative(p, dest);
    return push_expr_(p, dest, expr_binary(), op, acc, right);
}

int cmp_op_step(PState * p __attribute__((unused)), Arena *dest __attribute__((unused)), char * op __attribute__((unused)), int acc __attribute__((unused))) {
    int right __attribute__((unused)) = parse_additive(p, dest);
    return push_expr_(p, dest, expr_binary(), op, acc, right);
}

int parse_multiplicative(PState * p __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int left __attribute__((unused)) = parse_primary(p, dest);
    int __loop_result_6 __attribute__((unused));
    int acc = left;
    while (1) {
        if ((tok_is_punct_(p, "*") || tok_is_punct_(p, "/"))) {
        char *op __attribute__((unused)) = (cur_tok(p))->text;
        (void)(advance_(p));
        int __recur_tmp_0 = mul_op_step(p, dest, op, acc);
        acc = __recur_tmp_0;
        continue;
        } else {
        __loop_result_6 = acc;
        break;
        }
    }
    return __loop_result_6;
}

int parse_additive(PState * p __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int left __attribute__((unused)) = parse_multiplicative(p, dest);
    int __loop_result_7 __attribute__((unused));
    int acc = left;
    while (1) {
        if ((tok_is_punct_(p, "+") || tok_is_punct_(p, "-"))) {
        char *op __attribute__((unused)) = (cur_tok(p))->text;
        (void)(advance_(p));
        int __recur_tmp_0 = add_op_step(p, dest, op, acc);
        acc = __recur_tmp_0;
        continue;
        } else {
        __loop_result_7 = acc;
        break;
        }
    }
    return __loop_result_7;
}

int parse_comparison(PState * p __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int left __attribute__((unused)) = parse_additive(p, dest);
    int __loop_result_8 __attribute__((unused));
    int acc = left;
    while (1) {
        if ((tok_is_punct_(p, "<") || tok_is_punct_(p, ">"))) {
        char *op __attribute__((unused)) = (cur_tok(p))->text;
        (void)(advance_(p));
        int __recur_tmp_0 = cmp_op_step(p, dest, op, acc);
        acc = __recur_tmp_0;
        continue;
        } else {
        __loop_result_8 = acc;
        break;
        }
    }
    return __loop_result_8;
}

ParseResult parse(Vec toks __attribute__((unused)), Arena *dest __attribute__((unused))) {
    PState p0 __attribute__((unused)) = PState_new(toks, 0, vec_new(dest), vec_new(dest));
    JsToken *first __attribute__((unused)) = cur_tok(&(p0));
    if (((first)->kind == tok_eof())) {
    return ParseResult_new(p0, -1);
    } else {
    int root __attribute__((unused)) = parse_comparison(&(p0), dest);
    return ParseResult_new(p0, root);
    }
}

