/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int harvest_clamp(int, int, int);
int harvest_foe_count();
int harvest_kind(int);
int harvest_base_tokens(int);
int harvest_base_grade(int);
int harvest_extract_ticks(int);
int harvest_extract_stain(int);
int harvest_precision_bonus(int);
int harvest_contamination_penalty(int);
int harvest_grade(int, int, int);
int harvest_tokens(int, int);
int harvest_extract_ticks_adjusted(int, int);
int harvest_stain_gain(int, int);
int harvest_apply_stains(int, int);
int harvest_disposal_decay(int);
int harvest_disposal_cost_ticks(int);
int harvest_witness_weight_pm(int);
int harvest_extraction_bonus(int, int);

int harvest_clamp(int v __attribute__((unused)), int lo __attribute__((unused)), int hi __attribute__((unused))) {
    if ((v < lo)) {
    return lo;
    } else {
    if ((v > hi)) {
    return hi;
    } else {
    return v;
    }
    }
}

int harvest_foe_count(void) {
    return 6;
}

int harvest_kind(int k __attribute__((unused))) {
    return harvest_clamp(k, 0, 5);
}

int harvest_base_tokens(int k __attribute__((unused))) {
    if ((harvest_kind(k) == 0)) {
    return 2;
    } else {
    if ((harvest_kind(k) == 1)) {
    return 5;
    } else {
    if ((harvest_kind(k) == 2)) {
    return 4;
    } else {
    if ((harvest_kind(k) == 3)) {
    return 2;
    } else {
    if ((harvest_kind(k) == 4)) {
    return 3;
    } else {
    return 12;
    }
    }
    }
    }
    }
}

int harvest_base_grade(int k __attribute__((unused))) {
    if ((harvest_kind(k) == 0)) {
    return 3;
    } else {
    if ((harvest_kind(k) == 1)) {
    return 5;
    } else {
    if ((harvest_kind(k) == 2)) {
    return 4;
    } else {
    if ((harvest_kind(k) == 3)) {
    return 2;
    } else {
    if ((harvest_kind(k) == 4)) {
    return 4;
    } else {
    return 8;
    }
    }
    }
    }
    }
}

int harvest_extract_ticks(int k __attribute__((unused))) {
    if ((harvest_kind(k) == 0)) {
    return 96;
    } else {
    if ((harvest_kind(k) == 1)) {
    return 160;
    } else {
    if ((harvest_kind(k) == 2)) {
    return 128;
    } else {
    if ((harvest_kind(k) == 3)) {
    return 64;
    } else {
    if ((harvest_kind(k) == 4)) {
    return 96;
    } else {
    return 320;
    }
    }
    }
    }
    }
}

int harvest_extract_stain(int k __attribute__((unused))) {
    if ((harvest_kind(k) == 0)) {
    return 2;
    } else {
    if ((harvest_kind(k) == 1)) {
    return 4;
    } else {
    if ((harvest_kind(k) == 2)) {
    return 3;
    } else {
    if ((harvest_kind(k) == 3)) {
    return 1;
    } else {
    if ((harvest_kind(k) == 4)) {
    return 2;
    } else {
    return 9;
    }
    }
    }
    }
    }
}

int harvest_precision_bonus(int precision_pm __attribute__((unused))) {
    return (harvest_clamp(precision_pm, 0, 1000) / 250);
}

int harvest_contamination_penalty(int distinct_kinds_carried __attribute__((unused))) {
    return harvest_clamp((harvest_clamp(distinct_kinds_carried, 1, 6) - 1), 0, 5);
}

int harvest_grade(int k __attribute__((unused)), int precision_pm __attribute__((unused)), int distinct_kinds_carried __attribute__((unused))) {
    return harvest_clamp(((harvest_base_grade(k) + harvest_precision_bonus(precision_pm)) - harvest_contamination_penalty(distinct_kinds_carried)), 0, 9);
}

int harvest_tokens(int k __attribute__((unused)), int grade __attribute__((unused))) {
    return ((harvest_base_tokens(k) * (10 + harvest_clamp(grade, 0, 9))) / 10);
}

int harvest_extract_ticks_adjusted(int k __attribute__((unused)), int rush __attribute__((unused))) {
    if ((rush == 1)) {
    return (harvest_extract_ticks(k) / 2);
    } else {
    return harvest_extract_ticks(k);
    }
}

int harvest_stain_gain(int k __attribute__((unused)), int rush __attribute__((unused))) {
    if ((rush == 1)) {
    return (harvest_extract_stain(k) * 2);
    } else {
    return harvest_extract_stain(k);
    }
}

int harvest_apply_stains(int stains __attribute__((unused)), int gain __attribute__((unused))) {
    return harvest_clamp((harvest_clamp(stains, 0, 100) + harvest_clamp(gain, 0, 100)), 0, 100);
}

int harvest_disposal_decay(int site __attribute__((unused))) {
    if ((harvest_clamp(site, 0, 2) == 0)) {
    return 2;
    } else {
    if ((harvest_clamp(site, 0, 2) == 1)) {
    return 5;
    } else {
    return 12;
    }
    }
}

int harvest_disposal_cost_ticks(int site __attribute__((unused))) {
    if ((harvest_clamp(site, 0, 2) == 0)) {
    return 64;
    } else {
    if ((harvest_clamp(site, 0, 2) == 1)) {
    return 192;
    } else {
    return 480;
    }
    }
}

int harvest_witness_weight_pm(int stains __attribute__((unused))) {
    return harvest_clamp((100 + (8 * harvest_clamp(stains, 0, 100))), 100, 1000);
}

int harvest_extraction_bonus(int tokens_carried __attribute__((unused)), int time_left_pm __attribute__((unused))) {
    return (((harvest_clamp(tokens_carried, 0, 9999) / 5) * harvest_clamp(time_left_pm, 0, 1000)) / 1000);
}

