/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

typedef enum {
    JsonValue_TAG_JNull,
    JsonValue_TAG_JBool,
    JsonValue_TAG_JNumber,
    JsonValue_TAG_JString,
    JsonValue_TAG_JArray,
    JsonValue_TAG_JObject,
} JsonValue_Tag;
typedef struct { JsonValue_Tag tag; void *value; } JsonValue;
static inline JsonValue JsonValue_JNull(void) { JsonValue v; v.tag = JsonValue_TAG_JNull; v.value = NULL; return v; }
static inline JsonValue JsonValue_JBool(void *value) { JsonValue v; v.tag = JsonValue_TAG_JBool; v.value = value; return v; }
static inline JsonValue JsonValue_JNumber(void *value) { JsonValue v; v.tag = JsonValue_TAG_JNumber; v.value = value; return v; }
static inline JsonValue JsonValue_JString(void *value) { JsonValue v; v.tag = JsonValue_TAG_JString; v.value = value; return v; }
static inline JsonValue JsonValue_JArray(void *value) { JsonValue v; v.tag = JsonValue_TAG_JArray; v.value = value; return v; }
typedef struct {
    Vec keys;
    Vec values;
} JsonValue_JObject_Payload;
static inline JsonValue JsonValue_JObject(Arena *dest, Vec keys, Vec values) {
    JsonValue_JObject_Payload *p = (JsonValue_JObject_Payload *)arena_alloc(dest, sizeof(JsonValue_JObject_Payload));
    p->keys = keys;
    p->values = values;
    JsonValue v; v.tag = JsonValue_TAG_JObject; v.value = p; return v;
}

typedef struct {
    char * message;
    int pos;
} JsonError;
static inline JsonError JsonError_new(char * message, int pos) {
    JsonError v;
    v.message = message;
    v.pos = pos;
    return v;
}

typedef struct {
    JsonValue value;
    int next;
} JsonStep;
static inline JsonStep JsonStep_new(JsonValue value, int next) {
    JsonStep v;
    v.value = value;
    v.next = next;
    return v;
}

typedef struct {
    char * key;
    JsonValue value;
    int next;
} MemberStep;
static inline MemberStep MemberStep_new(char * key, JsonValue value, int next) {
    MemberStep v;
    v.key = key;
    v.value = value;
    v.next = next;
    return v;
}

typedef struct {
    int fd;
} TcpListener;
static inline TcpListener TcpListener_new(int fd) {
    TcpListener v;
    v.fd = fd;
    return v;
}

typedef struct {
    int fd;
} TcpStream;
static inline TcpStream TcpStream_new(int fd) {
    TcpStream v;
    v.fd = fd;
    return v;
}

typedef enum {
    NetError_TAG_ConnectionRefused,
    NetError_TAG_Timeout,
    NetError_TAG_AddressInUse,
    NetError_TAG_Other,
} NetError_Tag;
typedef struct { NetError_Tag tag; void *value; } NetError;
static inline NetError NetError_ConnectionRefused(void) { NetError v; v.tag = NetError_TAG_ConnectionRefused; v.value = NULL; return v; }
static inline NetError NetError_Timeout(void) { NetError v; v.tag = NetError_TAG_Timeout; v.value = NULL; return v; }
static inline NetError NetError_AddressInUse(void) { NetError v; v.tag = NetError_TAG_AddressInUse; v.value = NULL; return v; }
static inline NetError NetError_Other(void) { NetError v; v.tag = NetError_TAG_Other; v.value = NULL; return v; }

typedef struct {
    int status;
    Vec header_names;
    Vec header_values;
    char * body;
} HttpResponse;
static inline HttpResponse HttpResponse_new(int status, Vec header_names, Vec header_values, char * body) {
    HttpResponse v;
    v.status = status;
    v.header_names = header_names;
    v.header_values = header_values;
    v.body = body;
    return v;
}

typedef struct {
    char * host;
    int port;
    char * session_id;
} Session;
static inline Session Session_new(char * host, int port, char * session_id) {
    Session v;
    v.host = host;
    v.port = port;
    v.session_id = session_id;
    return v;
}

typedef enum {
    WebDriverError_TAG_ConnectFailed,
    WebDriverError_TAG_BadResponse,
    WebDriverError_TAG_ProtocolError,
} WebDriverError_Tag;
typedef struct { WebDriverError_Tag tag; void *value; } WebDriverError;
static inline WebDriverError WebDriverError_ConnectFailed(void) { WebDriverError v; v.tag = WebDriverError_TAG_ConnectFailed; v.value = NULL; return v; }
static inline WebDriverError WebDriverError_BadResponse(void) { WebDriverError v; v.tag = WebDriverError_TAG_BadResponse; v.value = NULL; return v; }
static inline WebDriverError WebDriverError_ProtocolError(void *value) { WebDriverError v; v.tag = WebDriverError_TAG_ProtocolError; v.value = value; return v; }

typedef enum {
    ProcessError_TAG_SpawnFailed,
    ProcessError_TAG_KillFailed,
} ProcessError_Tag;
typedef struct { ProcessError_Tag tag; void *value; } ProcessError;
static inline ProcessError ProcessError_SpawnFailed(void) { ProcessError v; v.tag = ProcessError_TAG_SpawnFailed; v.value = NULL; return v; }
static inline ProcessError ProcessError_KillFailed(void) { ProcessError v; v.tag = ProcessError_TAG_KillFailed; v.value = NULL; return v; }

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
char * json_unescape(char *, int, int, Arena *);
double parse_f64_raw(char *);
int is_whitespace_(int);
int skip_ws(char *, int);
Result parse(char *, Arena *);
Result parse_value(char *, int, Arena *);
Result parse_literal(char *, int, char *, JsonValue, Arena *);
Result parse_number(char *, int, Arena *);
int find_string_end(char *, int);
Result parse_string_value(char *, int, Arena *);
Result parse_array(char *, int, Arena *);
Result parse_object(char *, int, Arena *);
Result parse_member(char *, int, Arena *);
Option get(JsonValue, char *);
Option as_string(JsonValue);
int raw_connect(char *, int);
int raw_listen(int);
int raw_accept(int);
char * raw_read(int, Arena *);
int raw_write(int, char *);
int raw_close(int);
Result tcp_connect(char *, int, Arena *);
Result tcp_listen(int, Arena *);
Result tcp_accept(TcpListener *, Arena *);
Result tcp_read(TcpStream *, Arena *);
Result tcp_write(TcpStream *, char *, Arena *);
Result tcp_close(TcpStream *, Arena *);
int find_crlfcrlf(char *);
int find_colon(char *);
char * trim_trailing_cr(char *, Arena *);
char * trim_leading_space(char *, Arena *);
char * build_request(char *, char *, char *, Option, Arena *);
char * i32_to_string(int, Arena *);
int parse_status_line(char *, Arena *);
HttpResponse parse_http_response(char *, Arena *);
Result http_request(char *, char *, int, char *, Option, Arena *);
Result http_get(char *, int, char *, Arena *);
Result http_post(char *, int, char *, char *, Arena *);
char * element_ref_key();
char * json_escape_string(char *, Arena *);
Result do_request(char *, char *, int, char *, Option, Arena *);
Result new_session(char *, int, Arena *);
Result navigate_to(Session *, char *, Arena *);
Result find_element(Session *, char *, Arena *);
Result element_click(Session *, char *, Arena *);
Result element_send_keys(Session *, char *, char *, Arena *);
Result element_text(Session *, char *, Arena *);
Result page_title(Session *, Arena *);
Result quit_session(Session *, Arena *);
int raw_spawn(char *, char *);
int raw_kill(int);
Result process_spawn(char *, char *, Arena *);
Result process_kill(int, Arena *);

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

static inline JsonError *JsonError_box(Arena *dest, JsonError v) {
    JsonError *p = (JsonError *)arena_alloc(dest, sizeof(JsonError));
    *p = v;
    return p;
}

static inline JsonValue *JsonValue_box(Arena *dest, JsonValue v) {
    JsonValue *p = (JsonValue *)arena_alloc(dest, sizeof(JsonValue));
    *p = v;
    return p;
}

static inline JsonStep *JsonStep_box(Arena *dest, JsonStep v) {
    JsonStep *p = (JsonStep *)arena_alloc(dest, sizeof(JsonStep));
    *p = v;
    return p;
}

static inline double *double_box(Arena *dest, double v) {
    double *p = (double *)arena_alloc(dest, sizeof(double));
    *p = v;
    return p;
}

static inline Vec *Vec_box(Arena *dest, Vec v) {
    Vec *p = (Vec *)arena_alloc(dest, sizeof(Vec));
    *p = v;
    return p;
}

static inline MemberStep *MemberStep_box(Arena *dest, MemberStep v) {
    MemberStep *p = (MemberStep *)arena_alloc(dest, sizeof(MemberStep));
    *p = v;
    return p;
}

static inline NetError *NetError_box(Arena *dest, NetError v) {
    NetError *p = (NetError *)arena_alloc(dest, sizeof(NetError));
    *p = v;
    return p;
}

static inline TcpStream *TcpStream_box(Arena *dest, TcpStream v) {
    TcpStream *p = (TcpStream *)arena_alloc(dest, sizeof(TcpStream));
    *p = v;
    return p;
}

static inline HttpResponse *HttpResponse_box(Arena *dest, HttpResponse v) {
    HttpResponse *p = (HttpResponse *)arena_alloc(dest, sizeof(HttpResponse));
    *p = v;
    return p;
}

static inline WebDriverError *WebDriverError_box(Arena *dest, WebDriverError v) {
    WebDriverError *p = (WebDriverError *)arena_alloc(dest, sizeof(WebDriverError));
    *p = v;
    return p;
}

static inline Session *Session_box(Arena *dest, Session v) {
    Session *p = (Session *)arena_alloc(dest, sizeof(Session));
    *p = v;
    return p;
}

static inline ProcessError *ProcessError_box(Arena *dest, ProcessError v) {
    ProcessError *p = (ProcessError *)arena_alloc(dest, sizeof(ProcessError));
    *p = v;
    return p;
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    double i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    double start = 0;
    double i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        double __recur_tmp_0 = start;
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

char * json_unescape(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    host_json_unescape(s, start, end, out);
    return out;
}

double parse_f64_raw(char * s __attribute__((unused))) {
    return (strtod(s, NULL));
}

int is_whitespace_(int c __attribute__((unused))) {
    return ((c == 32) || ((c == 9) || ((c == 10) || (c == 13))));
}

int skip_ws(char * s __attribute__((unused)), int pos __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    int __loop_result_2 __attribute__((unused));
    int p = pos;
    while (1) {
        if (((p < n) && is_whitespace_(char_at(s, p)))) {
        int __recur_tmp_0 = (p + 1);
        p = __recur_tmp_0;
        continue;
        } else {
        __loop_result_2 = p;
        break;
        }
    }
    return __loop_result_2;
}

Result parse(char * text __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = length(text);
    Result __match_result_0 __attribute__((unused));
    Result __match_tmp_0 = parse_value(text, skip_ws(text, 0), dest);
    if (__match_tmp_0.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_0.value;
        __match_result_0 = result_err(e);
    }
    else if (__match_tmp_0.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_0.value;
        int after __attribute__((unused)) = skip_ws(text, ((*((JsonStep *)(step)))).next);
        if ((after < n)) {
        __match_result_0 = result_err(JsonError_box(dest, JsonError_new("trailing data after top-level value", after)));
        } else {
        __match_result_0 = result_ok(JsonValue_box(dest, ((*((JsonStep *)(step)))).value));
        }
    }
    return __match_result_0;
}

Result parse_value(char * s __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((pos >= n)) {
    return result_err(JsonError_box(dest, JsonError_new("unexpected end of input", pos)));
    } else {
    int c __attribute__((unused)) = char_at(s, pos);
    return ((c == 123) ? parse_object(s, pos, dest) : ((c == 91) ? parse_array(s, pos, dest) : ((c == 34) ? parse_string_value(s, pos, dest) : ((c == 116) ? parse_literal(s, pos, "true", JsonValue_JBool(int_box(dest, 1)), dest) : ((c == 102) ? parse_literal(s, pos, "false", JsonValue_JBool(int_box(dest, 0)), dest) : ((c == 110) ? parse_literal(s, pos, "null", JsonValue_JNull(), dest) : ((is_digit_(c) || (c == 45)) ? parse_number(s, pos, dest) : result_err(JsonError_box(dest, JsonError_new("unexpected character", pos))))))))));
    }
}

Result parse_literal(char * s __attribute__((unused)), int pos __attribute__((unused)), char * word __attribute__((unused)), JsonValue value __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int wlen __attribute__((unused)) = length(word);
    int n __attribute__((unused)) = length(s);
    if (((pos + wlen) > n)) {
    return result_err(JsonError_box(dest, JsonError_new("unexpected end of input", pos)));
    } else {
    char *slice __attribute__((unused)) = substring(s, pos, (pos + wlen), dest);
    if (str_eq_(slice, word)) {
    return result_ok(JsonStep_box(dest, JsonStep_new(value, (pos + wlen))));
    } else {
    return result_err(JsonError_box(dest, JsonError_new("invalid literal", pos)));
    }
    }
}

Result parse_number(char * s __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    Result __loop_result_3 __attribute__((unused));
    int p = ((char_at(s, pos) == 45) ? (pos + 1) : pos);
    while (1) {
        if (((p < n) && is_digit_(char_at(s, p)))) {
        int __recur_tmp_0 = (p + 1);
        p = __recur_tmp_0;
        continue;
        } else {
        if (((p < n) && (char_at(s, p) == 46))) {
        int __recur_tmp_0 = (p + 1);
        p = __recur_tmp_0;
        continue;
        } else {
        if (((p < n) && ((char_at(s, p) == 101) || (char_at(s, p) == 69)))) {
        int __recur_tmp_0 = (p + 1);
        p = __recur_tmp_0;
        continue;
        } else {
        if (((p < n) && ((char_at(s, p) == 43) || (char_at(s, p) == 45)))) {
        int __recur_tmp_0 = (p + 1);
        p = __recur_tmp_0;
        continue;
        } else {
        if ((p == pos)) {
        __loop_result_3 = result_err(JsonError_box(dest, JsonError_new("invalid number", pos)));
        break;
        } else {
        char *slice __attribute__((unused)) = substring(s, pos, p, dest);
        __loop_result_3 = result_ok(JsonStep_box(dest, JsonStep_new(JsonValue_JNumber(double_box(dest, parse_f64_raw(slice))), p)));
        break;
        }
        }
        }
        }
        }
    }
    return __loop_result_3;
}

int find_string_end(char * s __attribute__((unused)), int pos __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    double __loop_result_4 __attribute__((unused));
    int p = (pos + 1);
    while (1) {
        if ((p >= n)) {
        __loop_result_4 = -1;
        break;
        } else {
        if ((char_at(s, p) == 34)) {
        __loop_result_4 = p;
        break;
        } else {
        if ((char_at(s, p) == 92)) {
        int __recur_tmp_0 = (p + 2);
        p = __recur_tmp_0;
        continue;
        } else {
        int __recur_tmp_0 = (p + 1);
        p = __recur_tmp_0;
        continue;
        }
        }
        }
    }
    return __loop_result_4;
}

Result parse_string_value(char * s __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int close __attribute__((unused)) = find_string_end(s, pos);
    if ((close < 0)) {
    return result_err(JsonError_box(dest, JsonError_new("unterminated string", pos)));
    } else {
    return result_ok(JsonStep_box(dest, JsonStep_new(JsonValue_JString(json_unescape(s, (pos + 1), close, dest)), (close + 1))));
    }
}

Result parse_array(char * s __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    Vec items __attribute__((unused)) = vec_new(dest);
    int p1 __attribute__((unused)) = skip_ws(s, (pos + 1));
    if (((p1 < n) && (char_at(s, p1) == 93))) {
    return result_ok(JsonStep_box(dest, JsonStep_new(JsonValue_JArray(Vec_box(dest, items)), (p1 + 1))));
    } else {
    Result __match_result_1 __attribute__((unused));
    Result __match_tmp_1 = parse_value(s, p1, dest);
    if (__match_tmp_1.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_1.value;
        __match_result_1 = result_err(e);
    }
    else if (__match_tmp_1.tag == 1) {
        void *first __attribute__((unused)) = __match_tmp_1.value;
    (void)(vec_push_(&(items), JsonValue_box(dest, ((*((JsonStep *)(first)))).value)));
    int p = skip_ws(s, ((*((JsonStep *)(first)))).next);
    while (1) {
        if ((p >= n)) {
        __match_result_1 = result_err(JsonError_box(dest, JsonError_new("unterminated array", pos)));
        break;
        } else {
        if ((char_at(s, p) == 93)) {
        __match_result_1 = result_ok(JsonStep_box(dest, JsonStep_new(JsonValue_JArray(Vec_box(dest, items)), (p + 1))));
        break;
        } else {
        if ((char_at(s, p) == 44)) {
    Result __match_tmp_2 = parse_value(s, skip_ws(s, (p + 1)), dest);
    if (__match_tmp_2.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_2.value;
        __match_result_1 = result_err(e);
        break;
    }
    else if (__match_tmp_2.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_2.value;
    (void)(vec_push_(&(items), JsonValue_box(dest, ((*((JsonStep *)(step)))).value)));
        int __recur_tmp_0 = skip_ws(s, ((*((JsonStep *)(step)))).next);
        p = __recur_tmp_0;
        continue;
    }
        } else {
        __match_result_1 = result_err(JsonError_box(dest, JsonError_new("expected ',' or ']'", p)));
        break;
        }
        }
        }
    }
    }
    return __match_result_1;
    }
}

Result parse_object(char * s __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    Vec keys __attribute__((unused)) = vec_new(dest);
    Vec values __attribute__((unused)) = vec_new(dest);
    int p1 __attribute__((unused)) = skip_ws(s, (pos + 1));
    if (((p1 < n) && (char_at(s, p1) == 125))) {
    return result_ok(JsonStep_box(dest, JsonStep_new(JsonValue_JObject(dest, keys, values), (p1 + 1))));
    } else {
    Result __match_result_2 __attribute__((unused));
    Result __match_tmp_3 = parse_member(s, p1, dest);
    if (__match_tmp_3.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_3.value;
        __match_result_2 = result_err(e);
    }
    else if (__match_tmp_3.tag == 1) {
        void *first __attribute__((unused)) = __match_tmp_3.value;
    (void)(vec_push_(&(keys), ((*((MemberStep *)(first)))).key));
    (void)(vec_push_(&(values), JsonValue_box(dest, ((*((MemberStep *)(first)))).value)));
    int p = skip_ws(s, ((*((MemberStep *)(first)))).next);
    while (1) {
        if ((p >= n)) {
        __match_result_2 = result_err(JsonError_box(dest, JsonError_new("unterminated object", pos)));
        break;
        } else {
        if ((char_at(s, p) == 125)) {
        __match_result_2 = result_ok(JsonStep_box(dest, JsonStep_new(JsonValue_JObject(dest, keys, values), (p + 1))));
        break;
        } else {
        if ((char_at(s, p) == 44)) {
    Result __match_tmp_4 = parse_member(s, skip_ws(s, (p + 1)), dest);
    if (__match_tmp_4.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_4.value;
        __match_result_2 = result_err(e);
        break;
    }
    else if (__match_tmp_4.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_4.value;
    (void)(vec_push_(&(keys), ((*((MemberStep *)(step)))).key));
    (void)(vec_push_(&(values), JsonValue_box(dest, ((*((MemberStep *)(step)))).value)));
        int __recur_tmp_0 = skip_ws(s, ((*((MemberStep *)(step)))).next);
        p = __recur_tmp_0;
        continue;
    }
        } else {
        __match_result_2 = result_err(JsonError_box(dest, JsonError_new("expected ',' or '}'", p)));
        break;
        }
        }
        }
    }
    }
    return __match_result_2;
    }
}

Result parse_member(char * s __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if (((pos >= n) || (!((char_at(s, pos) == 34))))) {
    return result_err(JsonError_box(dest, JsonError_new("expected string key", pos)));
    } else {
    int close __attribute__((unused)) = find_string_end(s, pos);
    if ((close < 0)) {
    return result_err(JsonError_box(dest, JsonError_new("unterminated key string", pos)));
    } else {
    char *key __attribute__((unused)) = json_unescape(s, (pos + 1), close, dest);
    int p1 __attribute__((unused)) = skip_ws(s, (close + 1));
    if (((p1 >= n) || (!((char_at(s, p1) == 58))))) {
    return result_err(JsonError_box(dest, JsonError_new("expected ':' after key", p1)));
    } else {
    Result __match_result_3 __attribute__((unused));
    Result __match_tmp_5 = parse_value(s, skip_ws(s, (p1 + 1)), dest);
    if (__match_tmp_5.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_5.value;
        __match_result_3 = result_err(e);
    }
    else if (__match_tmp_5.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_5.value;
        __match_result_3 = result_ok(MemberStep_box(dest, MemberStep_new(key, ((*((JsonStep *)(step)))).value, ((*((JsonStep *)(step)))).next)));
    }
    return __match_result_3;
    }
    }
    }
}

Option get(JsonValue v __attribute__((unused)), char * key __attribute__((unused))) {
    Option __match_result_4 __attribute__((unused));
    JsonValue __match_tmp_6 = v;
    if (__match_tmp_6.tag == 5) {
        JsonValue_JObject_Payload *__match_payload_6 = (JsonValue_JObject_Payload *)(__match_tmp_6.value);
        Vec keys __attribute__((unused)) = __match_payload_6->keys;
        Vec values __attribute__((unused)) = __match_payload_6->values;
        int n __attribute__((unused)) = vec_len(&(keys));
    double i = 0;
    while (1) {
        if ((i >= n)) {
        __match_result_4 = option_none();
        break;
        } else {
        if (str_eq_(vec_get(&(keys), i), key)) {
        __match_result_4 = option_some(vec_get(&(values), i));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    }
    else if (1) {
        __match_result_4 = option_none();
    }
    return __match_result_4;
}

Option as_string(JsonValue v __attribute__((unused))) {
    Option __match_result_5 __attribute__((unused));
    JsonValue __match_tmp_7 = v;
    if (__match_tmp_7.tag == 3) {
        void *s __attribute__((unused)) = __match_tmp_7.value;
        __match_result_5 = option_some(s);
    }
    else if (1) {
        __match_result_5 = option_none();
    }
    return __match_result_5;
}

int raw_connect(char * host __attribute__((unused)), int port __attribute__((unused))) {
    return (tcp_connect_impl(host, port));
}

int raw_listen(int port __attribute__((unused))) {
    return (tcp_listen_impl(port));
}

int raw_accept(int listener_fd __attribute__((unused))) {
    return (tcp_accept_impl(listener_fd));
}

char * raw_read(int fd __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (tcp_read_impl(fd, dest));
}

int raw_write(int fd __attribute__((unused)), char * data __attribute__((unused))) {
    return (tcp_write_impl(fd, data));
}

int raw_close(int fd __attribute__((unused))) {
    return (tcp_close_impl(fd));
}

Result tcp_connect(char * host __attribute__((unused)), int port __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int fd __attribute__((unused)) = raw_connect(host, port);
    if ((fd < 0)) {
    return result_err(NetError_box(dest, NetError_ConnectionRefused()));
    } else {
    return result_ok(TcpStream_box(dest, TcpStream_new(fd)));
    }
}

Result tcp_listen(int port __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int fd __attribute__((unused)) = raw_listen(port);
    if ((fd < 0)) {
    return result_err(NetError_box(dest, NetError_AddressInUse()));
    } else {
    return result_ok(TcpStream_box(dest, TcpStream_new(fd)));
    }
}

Result tcp_accept(TcpListener * l __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int fd __attribute__((unused)) = raw_accept((l)->fd);
    if ((fd < 0)) {
    return result_err(NetError_box(dest, NetError_Other()));
    } else {
    return result_ok(TcpStream_box(dest, TcpStream_new(fd)));
    }
}

Result tcp_read(TcpStream * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return result_ok(raw_read((s)->fd, dest));
}

Result tcp_write(TcpStream * s __attribute__((unused)), char * data __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((raw_write((s)->fd, data) < 0)) {
    return result_err(NetError_box(dest, NetError_Other()));
    } else {
    return result_ok(double_box(dest, 0));
    }
}

Result tcp_close(TcpStream * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((raw_close((s)->fd) < 0)) {
    return result_err(NetError_box(dest, NetError_Other()));
    } else {
    return result_ok(NULL);
    }
}

int find_crlfcrlf(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    double __loop_result_5 __attribute__((unused));
    double i = 0;
    while (1) {
        if (((i + 4) > n)) {
        __loop_result_5 = -1;
        break;
        } else {
        if (((char_at(s, i) == 13) && ((char_at(s, (i + 1)) == 10) && ((char_at(s, (i + 2)) == 13) && (char_at(s, (i + 3)) == 10))))) {
        __loop_result_5 = i;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_5;
}

int find_colon(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    double __loop_result_6 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i >= n)) {
        __loop_result_6 = -1;
        break;
        } else {
        if ((char_at(s, i) == 58)) {
        __loop_result_6 = i;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_6;
}

char * trim_trailing_cr(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if (((n > 0) && (char_at(s, (n - 1)) == 13))) {
    return substring(s, 0, (n - 1), dest);
    } else {
    return s;
    }
}

char * trim_leading_space(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (((length(s) > 0) && (char_at(s, 0) == 32))) {
    return substring(s, 1, length(s), dest);
    } else {
    return s;
    }
}

char * build_request(char * method __attribute__((unused)), char * host __attribute__((unused)), char * path __attribute__((unused)), Option body __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *head __attribute__((unused)) = concat(concat(concat(concat(concat(method, " ", dest), path, dest), " HTTP/1.1\nHost: ", dest), host, dest), "\nConnection: close\n", dest);
    char * __match_result_6 __attribute__((unused));
    Option __match_tmp_8 = body;
    if (__match_tmp_8.tag == 1) {
        void *b __attribute__((unused)) = __match_tmp_8.value;
        __match_result_6 = concat(concat(concat(concat(head, "Content-Type: application/json\nContent-Length: ", dest), i32_to_string(length(b), dest), dest), "\n\n", dest), b, dest);
    }
    else if (__match_tmp_8.tag == 0) {
        __match_result_6 = concat(head, "\n", dest);
    }
    return __match_result_6;
}

char * i32_to_string(int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (({ char buf[16]; snprintf(buf, sizeof buf, "%d", n); arena_strdup(dest, buf, strlen(buf)); }));
}

int parse_status_line(char * line __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec parts __attribute__((unused)) = split(line, " ", dest);
    if ((vec_len(&(parts)) < 2)) {
    return 0;
    } else {
    int __match_result_7 __attribute__((unused));
    Result __match_tmp_9 = parse_i32(vec_get(&(parts), 1), dest);
    if (__match_tmp_9.tag == 1) {
        void *n __attribute__((unused)) = __match_tmp_9.value;
        __match_result_7 = (*((int *)(n)));
    }
    else if (__match_tmp_9.tag == 0) {
        void *_ __attribute__((unused)) = __match_tmp_9.value;
        __match_result_7 = 0;
    }
    return __match_result_7;
    }
}

HttpResponse parse_http_response(char * raw __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int boundary __attribute__((unused)) = find_crlfcrlf(raw);
    char *head_text __attribute__((unused)) = ((boundary >= 0) ? substring(raw, 0, boundary, dest) : raw);
    char *body __attribute__((unused)) = ((boundary >= 0) ? substring(raw, (boundary + 4), length(raw), dest) : "");
    Vec lines __attribute__((unused)) = split(head_text, "\n", dest);
    Vec names __attribute__((unused)) = vec_new(dest);
    Vec values __attribute__((unused)) = vec_new(dest);
    int n_lines __attribute__((unused)) = vec_len(&(lines));
    int status __attribute__((unused)) = ((n_lines > 0) ? parse_status_line(trim_trailing_cr(vec_get(&(lines), 0), dest), dest) : 0);
    double __let_val_0 __attribute__((unused));
    double i = 1;
    while (1) {
        if ((i >= n_lines)) {
        __let_val_0 = 0;
        break;
        } else {
        char *line __attribute__((unused)) = trim_trailing_cr(vec_get(&(lines), i), dest);
        int colon __attribute__((unused)) = find_colon(line);
        if ((colon < 0)) {
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
        (void)(vec_push_(&(names), substring(line, 0, colon, dest)));
        (void)(vec_push_(&(values), trim_leading_space(substring(line, (colon + 1), length(line), dest), dest)));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    double scan __attribute__((unused)) = __let_val_0;
    (void)(scan);
    return HttpResponse_new(status, names, values, body);
}

Result http_request(char * method __attribute__((unused)), char * host __attribute__((unused)), int port __attribute__((unused)), char * path __attribute__((unused)), Option body __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __match_result_8 __attribute__((unused));
    Result __match_tmp_10 = tcp_connect(host, port, dest);
    if (__match_tmp_10.tag == 1) {
        void *stream __attribute__((unused)) = __match_tmp_10.value;
    (void)(tcp_write(stream, build_request(method, host, path, body, dest), dest));
    Result __match_tmp_11 = tcp_read(stream, dest);
    if (__match_tmp_11.tag == 1) {
        void *raw __attribute__((unused)) = __match_tmp_11.value;
    (void)(tcp_close(stream, dest));
        __match_result_8 = result_ok(HttpResponse_box(dest, parse_http_response(raw, dest)));
    }
    else if (__match_tmp_11.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_11.value;
        __match_result_8 = result_err(e);
    }
    }
    else if (__match_tmp_10.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_10.value;
        __match_result_8 = result_err(e);
    }
    return __match_result_8;
}

Result http_get(char * host __attribute__((unused)), int port __attribute__((unused)), char * path __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return http_request("GET", host, port, path, option_none(), dest);
}

Result http_post(char * host __attribute__((unused)), int port __attribute__((unused)), char * path __attribute__((unused)), char * body __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return http_request("POST", host, port, path, option_some(body), dest);
}

char * element_ref_key(void) {
    return "element-6066-11e4-a52e-4f735466cecf";
}

char * json_escape_string(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    char * __loop_result_7 __attribute__((unused));
    double i = 0;
    char * acc = "";
    while (1) {
        if ((i >= n)) {
        __loop_result_7 = acc;
        break;
        } else {
        if ((char_at(s, i) == 34)) {
        double __recur_tmp_0 = (i + 1);
        char * __recur_tmp_1 = concat(acc, "\\\"", dest);
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        } else {
        if ((char_at(s, i) == 92)) {
        double __recur_tmp_0 = (i + 1);
        char * __recur_tmp_1 = concat(acc, "\\\\", dest);
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        } else {
        double __recur_tmp_0 = (i + 1);
        char * __recur_tmp_1 = concat(acc, substring(s, i, (i + 1), dest), dest);
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        }
        }
        }
    }
    return __loop_result_7;
}

Result do_request(char * method __attribute__((unused)), char * host __attribute__((unused)), int port __attribute__((unused)), char * path __attribute__((unused)), Option body __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __match_result_9 __attribute__((unused));
    Result __match_tmp_12 = http_request(method, host, port, path, body, dest);
    if (__match_tmp_12.tag == 0) {
        void *_ __attribute__((unused)) = __match_tmp_12.value;
        __match_result_9 = result_err(WebDriverError_box(dest, WebDriverError_ConnectFailed()));
    }
    else if (__match_tmp_12.tag == 1) {
        void *resp __attribute__((unused)) = __match_tmp_12.value;
        HttpResponse r __attribute__((unused)) = (*((HttpResponse *)(resp)));
        int status __attribute__((unused)) = (r).status;
        if (((status < 200) || (status >= 300))) {
        __match_result_9 = result_err(WebDriverError_box(dest, WebDriverError_ProtocolError((r).body)));
        } else {
    Result __match_tmp_13 = parse((r).body, dest);
    if (__match_tmp_13.tag == 0) {
        void *_ __attribute__((unused)) = __match_tmp_13.value;
        __match_result_9 = result_err(WebDriverError_box(dest, WebDriverError_BadResponse()));
    }
    else if (__match_tmp_13.tag == 1) {
        void *parsed __attribute__((unused)) = __match_tmp_13.value;
    Option __match_tmp_14 = get((*((JsonValue *)(parsed))), "value");
    if (__match_tmp_14.tag == 1) {
        void *v __attribute__((unused)) = __match_tmp_14.value;
        __match_result_9 = result_ok(JsonValue_box(dest, (*((JsonValue *)(v)))));
    }
    else if (__match_tmp_14.tag == 0) {
        __match_result_9 = result_err(WebDriverError_box(dest, WebDriverError_BadResponse()));
    }
    }
        }
    }
    return __match_result_9;
}

Result new_session(char * host __attribute__((unused)), int port __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __match_result_10 __attribute__((unused));
    Result __match_tmp_15 = do_request("POST", host, port, "/session", option_some("{\"capabilities\":{\"alwaysMatch\":{}}}"), dest);
    if (__match_tmp_15.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_15.value;
        __match_result_10 = result_err(e);
    }
    else if (__match_tmp_15.tag == 1) {
        void *value __attribute__((unused)) = __match_tmp_15.value;
    Option __match_tmp_16 = get((*((JsonValue *)(value))), "sessionId");
    if (__match_tmp_16.tag == 1) {
        void *sid __attribute__((unused)) = __match_tmp_16.value;
    Option __match_tmp_17 = as_string((*((JsonValue *)(sid))));
    if (__match_tmp_17.tag == 1) {
        void *id __attribute__((unused)) = __match_tmp_17.value;
        __match_result_10 = result_ok(Session_box(dest, Session_new(host, port, id)));
    }
    else if (__match_tmp_17.tag == 0) {
        __match_result_10 = result_err(WebDriverError_box(dest, WebDriverError_BadResponse()));
    }
    }
    else if (__match_tmp_16.tag == 0) {
        __match_result_10 = result_err(WebDriverError_box(dest, WebDriverError_BadResponse()));
    }
    }
    return __match_result_10;
}

Result navigate_to(Session * sess __attribute__((unused)), char * url __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *path __attribute__((unused)) = concat(concat("/session/", (sess)->session_id, dest), "/url", dest);
    char *body __attribute__((unused)) = concat(concat("{\"url\":\"", json_escape_string(url, dest), dest), "\"}", dest);
    Result __match_result_11 __attribute__((unused));
    Result __match_tmp_18 = do_request("POST", (sess)->host, (sess)->port, path, option_some(body), dest);
    if (__match_tmp_18.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_18.value;
        __match_result_11 = result_err(e);
    }
    else if (__match_tmp_18.tag == 1) {
        void *_ __attribute__((unused)) = __match_tmp_18.value;
        __match_result_11 = result_ok(NULL);
    }
    return __match_result_11;
}

Result find_element(Session * sess __attribute__((unused)), char * css_selector __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *path __attribute__((unused)) = concat(concat("/session/", (sess)->session_id, dest), "/element", dest);
    char *body __attribute__((unused)) = concat(concat("{\"using\":\"css selector\",\"value\":\"", json_escape_string(css_selector, dest), dest), "\"}", dest);
    Result __match_result_12 __attribute__((unused));
    Result __match_tmp_19 = do_request("POST", (sess)->host, (sess)->port, path, option_some(body), dest);
    if (__match_tmp_19.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_19.value;
        __match_result_12 = result_err(e);
    }
    else if (__match_tmp_19.tag == 1) {
        void *value __attribute__((unused)) = __match_tmp_19.value;
    Option __match_tmp_20 = get((*((JsonValue *)(value))), element_ref_key());
    if (__match_tmp_20.tag == 1) {
        void *eid __attribute__((unused)) = __match_tmp_20.value;
    Option __match_tmp_21 = as_string((*((JsonValue *)(eid))));
    if (__match_tmp_21.tag == 1) {
        void *id __attribute__((unused)) = __match_tmp_21.value;
        __match_result_12 = result_ok(id);
    }
    else if (__match_tmp_21.tag == 0) {
        __match_result_12 = result_err(WebDriverError_box(dest, WebDriverError_BadResponse()));
    }
    }
    else if (__match_tmp_20.tag == 0) {
        __match_result_12 = result_err(WebDriverError_box(dest, WebDriverError_BadResponse()));
    }
    }
    return __match_result_12;
}

Result element_click(Session * sess __attribute__((unused)), char * element_id __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *path __attribute__((unused)) = concat(concat(concat(concat("/session/", (sess)->session_id, dest), "/element/", dest), element_id, dest), "/click", dest);
    Result __match_result_13 __attribute__((unused));
    Result __match_tmp_22 = do_request("POST", (sess)->host, (sess)->port, path, option_some("{}"), dest);
    if (__match_tmp_22.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_22.value;
        __match_result_13 = result_err(e);
    }
    else if (__match_tmp_22.tag == 1) {
        void *_ __attribute__((unused)) = __match_tmp_22.value;
        __match_result_13 = result_ok(NULL);
    }
    return __match_result_13;
}

Result element_send_keys(Session * sess __attribute__((unused)), char * element_id __attribute__((unused)), char * text __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *path __attribute__((unused)) = concat(concat(concat(concat("/session/", (sess)->session_id, dest), "/element/", dest), element_id, dest), "/value", dest);
    char *body __attribute__((unused)) = concat(concat("{\"text\":\"", json_escape_string(text, dest), dest), "\"}", dest);
    Result __match_result_14 __attribute__((unused));
    Result __match_tmp_23 = do_request("POST", (sess)->host, (sess)->port, path, option_some(body), dest);
    if (__match_tmp_23.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_23.value;
        __match_result_14 = result_err(e);
    }
    else if (__match_tmp_23.tag == 1) {
        void *_ __attribute__((unused)) = __match_tmp_23.value;
        __match_result_14 = result_ok(NULL);
    }
    return __match_result_14;
}

Result element_text(Session * sess __attribute__((unused)), char * element_id __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *path __attribute__((unused)) = concat(concat(concat(concat("/session/", (sess)->session_id, dest), "/element/", dest), element_id, dest), "/text", dest);
    Result __match_result_15 __attribute__((unused));
    Result __match_tmp_24 = do_request("GET", (sess)->host, (sess)->port, path, option_none(), dest);
    if (__match_tmp_24.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_24.value;
        __match_result_15 = result_err(e);
    }
    else if (__match_tmp_24.tag == 1) {
        void *value __attribute__((unused)) = __match_tmp_24.value;
    Option __match_tmp_25 = as_string((*((JsonValue *)(value))));
    if (__match_tmp_25.tag == 1) {
        void *s __attribute__((unused)) = __match_tmp_25.value;
        __match_result_15 = result_ok(s);
    }
    else if (__match_tmp_25.tag == 0) {
        __match_result_15 = result_err(WebDriverError_box(dest, WebDriverError_BadResponse()));
    }
    }
    return __match_result_15;
}

Result page_title(Session * sess __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *path __attribute__((unused)) = concat(concat("/session/", (sess)->session_id, dest), "/title", dest);
    Result __match_result_16 __attribute__((unused));
    Result __match_tmp_26 = do_request("GET", (sess)->host, (sess)->port, path, option_none(), dest);
    if (__match_tmp_26.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_26.value;
        __match_result_16 = result_err(e);
    }
    else if (__match_tmp_26.tag == 1) {
        void *value __attribute__((unused)) = __match_tmp_26.value;
    Option __match_tmp_27 = as_string((*((JsonValue *)(value))));
    if (__match_tmp_27.tag == 1) {
        void *s __attribute__((unused)) = __match_tmp_27.value;
        __match_result_16 = result_ok(s);
    }
    else if (__match_tmp_27.tag == 0) {
        __match_result_16 = result_err(WebDriverError_box(dest, WebDriverError_BadResponse()));
    }
    }
    return __match_result_16;
}

Result quit_session(Session * sess __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *path __attribute__((unused)) = concat("/session/", (sess)->session_id, dest);
    Result __match_result_17 __attribute__((unused));
    Result __match_tmp_28 = do_request("DELETE", (sess)->host, (sess)->port, path, option_none(), dest);
    if (__match_tmp_28.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_28.value;
        __match_result_17 = result_err(e);
    }
    else if (__match_tmp_28.tag == 1) {
        void *_ __attribute__((unused)) = __match_tmp_28.value;
        __match_result_17 = result_ok(NULL);
    }
    return __match_result_17;
}

int raw_spawn(char * path __attribute__((unused)), char * arg1 __attribute__((unused))) {
    return (spawn_detached_impl(path, arg1));
}

int raw_kill(int pid __attribute__((unused))) {
    return (process_kill_impl(pid));
}

Result process_spawn(char * path __attribute__((unused)), char * arg1 __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int pid __attribute__((unused)) = raw_spawn(path, arg1);
    if ((pid < 0)) {
    return result_err(ProcessError_box(dest, ProcessError_SpawnFailed()));
    } else {
    return result_ok(int_box(dest, pid));
    }
}

Result process_kill(int pid __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((raw_kill(pid) < 0)) {
    return result_err(ProcessError_box(dest, ProcessError_KillFailed()));
    } else {
    return result_ok(NULL);
    }
}

