/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

typedef struct {
    Vec data;
    Vec shape;
    Vec strides;
} NDArray;
static inline NDArray NDArray_new(Vec data, Vec shape, Vec strides) {
    NDArray v;
    v.data = data;
    v.shape = shape;
    v.strides = strides;
    return v;
}

typedef struct {
    char * message;
} ShapeError;
static inline ShapeError ShapeError_new(char * message) {
    ShapeError v;
    v.message = message;
    return v;
}

typedef struct {
    char * message;
} IndexError;
static inline IndexError IndexError_new(char * message) {
    IndexError v;
    v.message = message;
    return v;
}

typedef struct {
    int fd;
} FileHandle;
static inline FileHandle FileHandle_new(int fd) {
    FileHandle v;
    v.fd = fd;
    return v;
}

typedef enum {
    IoError_TAG_NotFound,
    IoError_TAG_PermissionDenied,
    IoError_TAG_AlreadyExists,
    IoError_TAG_Other,
} IoError_Tag;
typedef struct { IoError_Tag tag; void *value; } IoError;
static inline IoError IoError_NotFound(void) { IoError v; v.tag = IoError_TAG_NotFound; v.value = NULL; return v; }
static inline IoError IoError_PermissionDenied(void) { IoError v; v.tag = IoError_TAG_PermissionDenied; v.value = NULL; return v; }
static inline IoError IoError_AlreadyExists(void) { IoError v; v.tag = IoError_TAG_AlreadyExists; v.value = NULL; return v; }
static inline IoError IoError_Other(void) { IoError v; v.tag = IoError_TAG_Other; v.value = NULL; return v; }

typedef enum {
    OpenMode_TAG_Read,
    OpenMode_TAG_Write,
    OpenMode_TAG_Append,
} OpenMode_Tag;
typedef struct { OpenMode_Tag tag; void *value; } OpenMode;
static inline OpenMode OpenMode_Read(void) { OpenMode v; v.tag = OpenMode_TAG_Read; v.value = NULL; return v; }
static inline OpenMode OpenMode_Write(void) { OpenMode v; v.tag = OpenMode_TAG_Write; v.value = NULL; return v; }
static inline OpenMode OpenMode_Append(void) { OpenMode v; v.tag = OpenMode_TAG_Append; v.value = NULL; return v; }

typedef struct {
    int fd;
} Pty;
static inline Pty Pty_new(int fd) {
    Pty v;
    v.fd = fd;
    return v;
}

typedef enum {
    PtyError_TAG_SpawnFailed,
    PtyError_TAG_ResizeFailed,
    PtyError_TAG_PtyIoError,
} PtyError_Tag;
typedef struct { PtyError_Tag tag; void *value; } PtyError;
static inline PtyError PtyError_SpawnFailed(void) { PtyError v; v.tag = PtyError_TAG_SpawnFailed; v.value = NULL; return v; }
static inline PtyError PtyError_ResizeFailed(void) { PtyError v; v.tag = PtyError_TAG_ResizeFailed; v.value = NULL; return v; }
static inline PtyError PtyError_PtyIoError(void) { PtyError v; v.tag = PtyError_TAG_PtyIoError; v.value = NULL; return v; }

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
int contains_ci_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
int product(Vec *);
Vec strides_for(Vec *, Arena *);
NDArray zeros(Vec, Arena *);
Result from_vec(Vec, Vec, Arena *);
int flat_index(NDArray *, Vec *);
Result get(NDArray *, Vec, Arena *);
Result set_(NDArray *, Vec, double, Arena *);
Result reshape(NDArray *, Vec, Arena *);
int same_shape_(NDArray *, NDArray *);
Result elementwise(NDArray *, NDArray *, double (*)(double, double), Arena *);
Result add(NDArray *, NDArray *, Arena *);
Result mul_elementwise(NDArray *, NDArray *, Arena *);
int raw_open(char *, int);
int raw_close(int);
int raw_write(int, char *);
char * raw_read_all(int, Arena *);
int raw_at_eof_(int);
char * raw_read_line(int, Arena *);
int raw_errno();
int mode_tag_of(OpenMode);
IoError errno_to_io_error(int);
Result file_open(char *, OpenMode, Arena *);
Result file_close(FileHandle, Arena *);
int path_exists_(char *);
Result write_string(FileHandle, char *, Arena *);
Result read_string(FileHandle, Arena *);
Result read_line(FileHandle, Arena *);
double raw_read_f64(int);
Result read_floats(FileHandle, int, Arena *);
int pty_raw_open(char *, int, int);
char * pty_raw_read(int, Arena *);
int pty_raw_write(int, char *);
int pty_raw_resize(int, int, int);
int pty_raw_close(int);
Result pty_open(char *, int, int, Arena *);
Result pty_read(Pty *, Arena *);
Result pty_write(Pty *, char *, Arena *);
Result pty_resize(Pty *, int, int, Arena *);
Result pty_close(Pty, Arena *);
char * raw_env_get(char *, Arena *);
Option env_lookup(char *, Arena *);
char * raw_lookup_path(char *, Arena *);
Option lookup_path(char *, Arena *);
int is_wsl_stub_(char *);
Option find_git_bash(Arena *);
Option find_git_bash_under(char *, Arena *);
char * platform_fallback_shell();
char * resolve(Option, Arena *);
char * resolve_past_wsl_stub(Arena *);
Result spawn_bash(int, int, Arena *);
Result spawn_zsh(int, int, Arena *);

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

static inline NDArray *NDArray_box(Arena *dest, NDArray v) {
    NDArray *p = (NDArray *)arena_alloc(dest, sizeof(NDArray));
    *p = v;
    return p;
}

static inline ShapeError *ShapeError_box(Arena *dest, ShapeError v) {
    ShapeError *p = (ShapeError *)arena_alloc(dest, sizeof(ShapeError));
    *p = v;
    return p;
}

static inline IndexError *IndexError_box(Arena *dest, IndexError v) {
    IndexError *p = (IndexError *)arena_alloc(dest, sizeof(IndexError));
    *p = v;
    return p;
}

static inline double *double_box(Arena *dest, double v) {
    double *p = (double *)arena_alloc(dest, sizeof(double));
    *p = v;
    return p;
}

static inline IoError *IoError_box(Arena *dest, IoError v) {
    IoError *p = (IoError *)arena_alloc(dest, sizeof(IoError));
    *p = v;
    return p;
}

static inline Pty *Pty_box(Arena *dest, Pty v) {
    Pty *p = (Pty *)arena_alloc(dest, sizeof(Pty));
    *p = v;
    return p;
}

static inline Option *Option_box(Arena *dest, Option v) {
    Option *p = (Option *)arena_alloc(dest, sizeof(Option));
    *p = v;
    return p;
}

static inline PtyError *PtyError_box(Arena *dest, PtyError v) {
    PtyError *p = (PtyError *)arena_alloc(dest, sizeof(PtyError));
    *p = v;
    return p;
}

static inline int int_vec_eq(Vec *a, Vec *b) {
    if (vec_len(a) != vec_len(b)) return 0;
    for (int i = 0; i < vec_len(a); i++) {
        if (*(int *)vec_get(a, i) != *(int *)vec_get(b, i)) return 0;
    }
    return 1;
}

static double __lambda_0(double x, double y) {
    return (x + y);
}

static double __lambda_1(double x, double y) {
    return (x * y);
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

int contains_ci_(char * haystack __attribute__((unused)), char * needle __attribute__((unused))) {
    return (strcasestr(haystack, needle) != NULL);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    double i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    double start = 0;
    double i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        double __recur_tmp_0 = start;
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

int product(Vec * shape __attribute__((unused))) {
    double __loop_result_2 __attribute__((unused));
    double i = 0;
    double acc = 1;
    while (1) {
        if ((i >= vec_len(shape))) {
        __loop_result_2 = acc;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (acc * (*((int *)(vec_get(shape, i)))));
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_2;
}

Vec strides_for(Vec * shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = vec_len(shape);
    int total __attribute__((unused)) = product(shape);
    Vec s __attribute__((unused)) = vec_new(dest);
    void * __loop_result_3 __attribute__((unused));
    double i = 0;
    int running = total;
    while (1) {
        if ((i < n)) {
        int next __attribute__((unused)) = (running / (*((int *)(vec_get(shape, i)))));
        (void)(vec_push_(&(s), vec_box_i32(&(s), next)));
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = next;
        i = __recur_tmp_0;
        running = __recur_tmp_1;
        continue;
        } else {
            break;
        }
    }
    return s;
}

NDArray zeros(Vec shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = product(&(shape));
    Vec data __attribute__((unused)) = vec_new(dest);
    void * __loop_result_4 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < n)) {
    (void)(vec_push_(&(data), vec_box_f64(&(data), 0.0)));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return NDArray_new(data, shape, strides_for(&(shape), dest));
}

Result from_vec(Vec data __attribute__((unused)), Vec shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((vec_len(&(data)) == product(&(shape)))) {
    return result_ok(NDArray_box(dest, NDArray_new(data, shape, strides_for(&(shape), dest))));
    } else {
    return result_err(ShapeError_box(dest, ShapeError_new("data length does not match shape product")));
    }
}

int flat_index(NDArray * a __attribute__((unused)), Vec * idx __attribute__((unused))) {
    double __loop_result_5 __attribute__((unused));
    double i = 0;
    double offset = 0;
    while (1) {
        if ((i >= vec_len(idx))) {
        __loop_result_5 = offset;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (offset + ((*((int *)(vec_get(idx, i)))) * (*((int *)(vec_get(&((a)->strides), i))))));
        i = __recur_tmp_0;
        offset = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_5;
}

Result get(NDArray * a __attribute__((unused)), Vec idx __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int off __attribute__((unused)) = flat_index(a, &(idx));
    if (((off < 0) || (off >= vec_len(&((a)->data))))) {
    return result_err(IndexError_box(dest, IndexError_new("out of bounds")));
    } else {
    return result_ok(double_box(dest, (*((double *)(vec_get(&((a)->data), off))))));
    }
}

Result set_(NDArray * a __attribute__((unused)), Vec idx __attribute__((unused)), double v __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int off __attribute__((unused)) = flat_index(a, &(idx));
    if (((off < 0) || (off >= vec_len(&((a)->data))))) {
    return result_err(IndexError_box(dest, IndexError_new("out of bounds")));
    } else {
    (void)(vec_set_at_(&((a)->data), off, vec_box_f64(&((a)->data), v)));
    return result_ok(NULL);
    }
}

Result reshape(NDArray * a __attribute__((unused)), Vec new_shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((product(&(new_shape)) == product(&((a)->shape)))) {
    return result_ok(NDArray_box(dest, NDArray_new((a)->data, new_shape, strides_for(&(new_shape), dest))));
    } else {
    return result_err(ShapeError_box(dest, ShapeError_new("reshape must preserve element count")));
    }
}

int same_shape_(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused))) {
    return int_vec_eq(&((a)->shape), &((b)->shape));
}

Result elementwise(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), double (*op)(double, double) __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!(same_shape_(a, b)))) {
    return result_err(ShapeError_box(dest, ShapeError_new("shape mismatch")));
    } else {
    int n __attribute__((unused)) = vec_len(&((a)->data));
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_6 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < n)) {
    (void)(vec_push_(&(out), vec_box_f64(&(out), op((*((double *)(vec_get(&((a)->data), i)))), (*((double *)(vec_get(&((b)->data), i))))))));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return result_ok(NDArray_box(dest, NDArray_new(out, (a)->shape, (a)->strides)));
    }
}

Result add(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return elementwise(a, b, __lambda_0, dest);
}

Result mul_elementwise(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return elementwise(a, b, __lambda_1, dest);
}

int raw_open(char * path __attribute__((unused)), int mode_tag __attribute__((unused))) {
    return (raw_open_impl(path, mode_tag));
}

int raw_close(int fd __attribute__((unused))) {
    return (raw_close_impl(fd));
}

int raw_write(int fd __attribute__((unused)), char * s __attribute__((unused))) {
    return (raw_write_impl(fd, s));
}

char * raw_read_all(int fd __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (raw_read_all_impl(fd, dest));
}

int raw_at_eof_(int fd __attribute__((unused))) {
    return (raw_at_eof_impl(fd));
}

char * raw_read_line(int fd __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (raw_read_line_impl(fd, dest));
}

int raw_errno(void) {
    return (errno);
}

int mode_tag_of(OpenMode mode __attribute__((unused))) {
    double __match_result_0 __attribute__((unused));
    OpenMode __match_tmp_0 = mode;
    if (__match_tmp_0.tag == 0) {
        __match_result_0 = 0;
    }
    else if (__match_tmp_0.tag == 1) {
        __match_result_0 = 1;
    }
    else if (__match_tmp_0.tag == 2) {
        __match_result_0 = 2;
    }
    return __match_result_0;
}

IoError errno_to_io_error(int e __attribute__((unused))) {
    return ((e == 2) ? IoError_NotFound() : ((e == 13) ? IoError_PermissionDenied() : ((e == 17) ? IoError_AlreadyExists() : IoError_Other())));
}

Result file_open(char * path __attribute__((unused)), OpenMode mode __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int fd __attribute__((unused)) = raw_open(path, mode_tag_of(mode));
    if ((fd < 0)) {
    return result_err(IoError_box(dest, errno_to_io_error(raw_errno())));
    } else {
    return result_ok(Pty_box(dest, Pty_new(fd)));
    }
}

Result file_close(FileHandle f __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((raw_close((f).fd) < 0)) {
    return result_err(IoError_box(dest, errno_to_io_error(raw_errno())));
    } else {
    return result_ok(NULL);
    }
}

int path_exists_(char * path __attribute__((unused))) {
    return (file_exists_impl(path) != 0);
}

Result write_string(FileHandle f __attribute__((unused)), char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((raw_write((f).fd, s) < 0)) {
    return result_err(IoError_box(dest, errno_to_io_error(raw_errno())));
    } else {
    return result_ok(NULL);
    }
}

Result read_string(FileHandle f __attribute__((unused)), Arena *buf __attribute__((unused))) {
    return result_ok(raw_read_all((f).fd, buf));
}

Result read_line(FileHandle f __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (raw_at_eof_((f).fd)) {
    return result_ok(Option_box(dest, option_none()));
    } else {
    return result_ok(Option_box(dest, option_some(raw_read_line((f).fd, dest))));
    }
}

double raw_read_f64(int fd __attribute__((unused))) {
    return (raw_read_f64_impl(fd));
}

Result read_floats(FileHandle f __attribute__((unused)), int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec data __attribute__((unused)) = vec_new(dest);
    void * __loop_result_7 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < n)) {
        (void)(vec_push_(&(data), vec_box_f64(&(data), raw_read_f64((f).fd))));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    Vec shape __attribute__((unused)) = vec_new(dest);
    Vec strides __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(shape), vec_box_i32(&(shape), n)));
    (void)(vec_push_(&(strides), vec_box_f64(&(strides), 1)));
    return result_ok(NDArray_box(dest, NDArray_new(data, shape, strides)));
}

int pty_raw_open(char * shell __attribute__((unused)), int cols __attribute__((unused)), int rows __attribute__((unused))) {
    return (pty_open_impl(shell, cols, rows));
}

char * pty_raw_read(int fd __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (pty_read_impl(fd, dest));
}

int pty_raw_write(int fd __attribute__((unused)), char * data __attribute__((unused))) {
    return (pty_write_impl(fd, data));
}

int pty_raw_resize(int fd __attribute__((unused)), int cols __attribute__((unused)), int rows __attribute__((unused))) {
    return (pty_resize_impl(fd, cols, rows));
}

int pty_raw_close(int fd __attribute__((unused))) {
    return (pty_close_impl(fd));
}

Result pty_open(char * shell __attribute__((unused)), int cols __attribute__((unused)), int rows __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int fd __attribute__((unused)) = pty_raw_open(shell, cols, rows);
    if ((fd < 0)) {
    return result_err(PtyError_box(dest, PtyError_SpawnFailed()));
    } else {
    return result_ok(Pty_box(dest, Pty_new(fd)));
    }
}

Result pty_read(Pty * p __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return result_ok(pty_raw_read((p)->fd, dest));
}

Result pty_write(Pty * p __attribute__((unused)), char * data __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((pty_raw_write((p)->fd, data) < 0)) {
    return result_err(PtyError_box(dest, PtyError_PtyIoError()));
    } else {
    return result_ok(double_box(dest, 0));
    }
}

Result pty_resize(Pty * p __attribute__((unused)), int cols __attribute__((unused)), int rows __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((pty_raw_resize((p)->fd, cols, rows) < 0)) {
    return result_err(PtyError_box(dest, PtyError_ResizeFailed()));
    } else {
    return result_ok(NULL);
    }
}

Result pty_close(Pty p __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((pty_raw_close((p).fd) < 0)) {
    return result_err(PtyError_box(dest, PtyError_PtyIoError()));
    } else {
    return result_ok(NULL);
    }
}

char * raw_env_get(char * name __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (env_get_impl(name, dest));
}

Option env_lookup(char * name __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *v __attribute__((unused)) = raw_env_get(name, dest);
    if (str_eq_(v, "")) {
    return option_none();
    } else {
    return option_some(v);
    }
}

char * raw_lookup_path(char * name __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (exec_lookpath_impl(name, dest));
}

Option lookup_path(char * name __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *v __attribute__((unused)) = raw_lookup_path(name, dest);
    if (str_eq_(v, "")) {
    return option_none();
    } else {
    return option_some(v);
    }
}

int is_wsl_stub_(char * path __attribute__((unused))) {
    return contains_ci_(path, "\\system32\\bash.exe");
}

Option find_git_bash(Arena *dest __attribute__((unused))) {
    Option __match_result_1 __attribute__((unused));
    Option __match_tmp_1 = env_lookup("ProgramFiles", dest);
    if (__match_tmp_1.tag == 1) {
        void *root __attribute__((unused)) = __match_tmp_1.value;
        __match_result_1 = find_git_bash_under(root, dest);
    }
    else if (__match_tmp_1.tag == 0) {
    Option __match_tmp_2 = env_lookup("ProgramFiles(x86)", dest);
    if (__match_tmp_2.tag == 1) {
        void *root __attribute__((unused)) = __match_tmp_2.value;
        __match_result_1 = find_git_bash_under(root, dest);
    }
    else if (__match_tmp_2.tag == 0) {
    Option __match_tmp_3 = env_lookup("LocalAppData", dest);
    if (__match_tmp_3.tag == 1) {
        void *root __attribute__((unused)) = __match_tmp_3.value;
        __match_result_1 = find_git_bash_under(concat(root, "/Programs", dest), dest);
    }
    else if (__match_tmp_3.tag == 0) {
        __match_result_1 = option_none();
    }
    }
    }
    return __match_result_1;
}

Option find_git_bash_under(char * root __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *c1 __attribute__((unused)) = concat(root, "/Git/bin/bash.exe", dest);
    if (path_exists_(c1)) {
    return option_some(c1);
    } else {
    char *c2 __attribute__((unused)) = concat(root, "/Git/usr/bin/bash.exe", dest);
    if (path_exists_(c2)) {
    return option_some(c2);
    } else {
    return option_none();
    }
    }
}

char * platform_fallback_shell(void) {
    return "/bin/sh";
}

char * resolve(Option explicit __attribute__((unused)), Arena *dest __attribute__((unused))) {
    void * __match_result_2 __attribute__((unused));
    Option __match_tmp_4 = explicit;
    if (__match_tmp_4.tag == 1) {
        void *s __attribute__((unused)) = __match_tmp_4.value;
        __match_result_2 = s;
    }
    else if (__match_tmp_4.tag == 0) {
    Option __match_tmp_5 = env_lookup("SHELL", dest);
    if (__match_tmp_5.tag == 1) {
        void *s __attribute__((unused)) = __match_tmp_5.value;
        __match_result_2 = s;
    }
    else if (__match_tmp_5.tag == 0) {
    Option __match_tmp_6 = lookup_path("bash.exe", dest);
    if (__match_tmp_6.tag == 1) {
        void *p __attribute__((unused)) = __match_tmp_6.value;
        if (is_wsl_stub_(p)) {
        __match_result_2 = resolve_past_wsl_stub(dest);
        } else {
        __match_result_2 = p;
        }
    }
    else if (__match_tmp_6.tag == 0) {
        __match_result_2 = resolve_past_wsl_stub(dest);
    }
    }
    }
    return __match_result_2;
}

char * resolve_past_wsl_stub(Arena *dest __attribute__((unused))) {
    char * __match_result_3 __attribute__((unused));
    Option __match_tmp_7 = find_git_bash(dest);
    if (__match_tmp_7.tag == 1) {
        void *p __attribute__((unused)) = __match_tmp_7.value;
        __match_result_3 = p;
    }
    else if (__match_tmp_7.tag == 0) {
        __match_result_3 = platform_fallback_shell();
    }
    return __match_result_3;
}

Result spawn_bash(int cols __attribute__((unused)), int rows __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return pty_open("bash", cols, rows, dest);
}

Result spawn_zsh(int cols __attribute__((unused)), int rows __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return pty_open("zsh", cols, rows, dest);
}

