/* tests/test_audio_jive_rules.c -- stdlib/audio/jive_rules.prn (jivetalking's adaptive tuning,
 * PARENA-ified, founder real-time 2026-09-27) replayed against golden vectors generated by the
 * ORIGINAL Go implementation (emilyspringerton/jivetalking internal/processor
 * TestWriteParenaVectors -> tests/audio_jive_vectors.txt). Every branch decision must match
 * exactly; the only tolerance is 1e-12 relative on jive_gate_threshold, whose dB->linear step
 * is libm pow() here vs Go math.Pow there (last-bit differences between the two libraries --
 * jivetalking itself does that conversion in Go and is bit-exact).
 */
#include "parena_runtime.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "test_audio_jive_rules_gen.c"

static double call(const char *fn, const double *a, int *known) {
    *known = 1;
    if (!strcmp(fn, "jive_gate_aggression")) return jive_gate_aggression(a[0], a[1]);
    if (!strcmp(fn, "jive_gate_ratio")) return jive_gate_ratio(a[0]);
    if (!strcmp(fn, "jive_gate_attack")) return jive_gate_attack(a[0], a[1], a[2]);
    if (!strcmp(fn, "jive_gate_release")) return jive_gate_release(a[0], a[1], a[2], a[3]);
    if (!strcmp(fn, "jive_gate_range_db")) return jive_gate_range_db(a[0], a[1]);
    if (!strcmp(fn, "jive_gate_knee")) return jive_gate_knee(a[0]);
    if (!strcmp(fn, "jive_gate_detection")) return (double)jive_gate_detection(a[0], a[1]);
    if (!strcmp(fn, "jive_gate_threshold"))
        return jive_gate_threshold(a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7]);
    if (!strcmp(fn, "jive_nr_expansion")) return jive_nr_expansion((int)a[0], a[1]);
    *known = 0;
    return 0;
}

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: %s vectors.txt\n", argv[0]); return 2; }
    FILE *fp = fopen(argv[1], "r");
    if (!fp) { perror(argv[1]); return 2; }
    char line[1024];
    long n = 0, failures = 0;
    while (fgets(line, sizeof line, fp)) {
        if (line[0] == '#' || line[0] == '\n') continue;
        char *save = NULL, *tok = strtok_r(line, " \n", &save);
        char fn[64];
        snprintf(fn, sizeof fn, "%s", tok);
        double v[16];
        int k = 0;
        while ((tok = strtok_r(NULL, " \n", &save)) && k < 16) v[k++] = strtod(tok, NULL);
        int known;
        double got = call(fn, v, &known), want = v[k - 1];
        if (!known) { printf("FAIL: unknown vector fn %s\n", fn); failures++; continue; }
        double tol = strcmp(fn, "jive_gate_threshold") ? 0.0 : 1e-12 * fabs(want);
        if (fabs(got - want) > tol) {
            if (failures < 20) printf("FAIL: %s line %ld: got %.17g want %.17g\n", fn, n, got, want);
            failures++;
        }
        n++;
    }
    fclose(fp);
    printf("%ld vectors, %ld failures\n", n, failures);
    return failures ? 1 : (n > 0 ? 0 : 1);
}
