/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

double random_f64();
double floor(double);
double sqrt(double);
double log(double);
double cos(double);
double cos_2t(double, double);
double sin_2t(double, double);
double cos_3t(double);
double cos_5t(double);

double random_f64(void) {
    return (math_random_impl());
}

double floor(double x __attribute__((unused))) {
    return 0.0;
}

double sqrt(double x __attribute__((unused))) {
    return 0.0;
}

double log(double x __attribute__((unused))) {
    return 0.0;
}

double cos(double x __attribute__((unused))) {
    return 0.0;
}

double cos_2t(double c __attribute__((unused)), double s __attribute__((unused))) {
    return ((c * c) - (s * s));
}

double sin_2t(double c __attribute__((unused)), double s __attribute__((unused))) {
    return (2.0 * (c * s));
}

double cos_3t(double c __attribute__((unused))) {
    return ((4.0 * (c * (c * c))) - (3.0 * c));
}

double cos_5t(double c __attribute__((unused))) {
    return (((16.0 * (c * (c * (c * (c * c))))) - (20.0 * (c * (c * c)))) + (5.0 * c));
}

