/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline __attribute__((unused)) ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

typedef enum {
    ProcessError_TAG_SpawnFailed,
    ProcessError_TAG_KillFailed,
} ProcessError_Tag;
typedef struct { ProcessError_Tag tag; void *value; } ProcessError;
static inline __attribute__((unused)) ProcessError ProcessError_SpawnFailed(void) { ProcessError v; v.tag = ProcessError_TAG_SpawnFailed; v.value = NULL; return v; }
static inline __attribute__((unused)) ProcessError ProcessError_KillFailed(void) { ProcessError v; v.tag = ProcessError_TAG_KillFailed; v.value = NULL; return v; }

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
char * char_from_code(int, Arena *);
char * i32_to_string(int, Arena *);
int contains_ci_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
double parse_f64_raw(char *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
int raw_spawn(char *, char *);
int raw_kill(int);
Result process_spawn(char *, char *, Arena *);
Result process_kill(int, Arena *);
char * run_capture(char *, Arena *);
int run_capture_exit_code();

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

static inline ProcessError *ProcessError_box(Arena *dest, ProcessError v) {
    ProcessError *p = (ProcessError *)arena_alloc(dest, sizeof(ProcessError));
    *p = v;
    return p;
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

char * char_from_code(int code __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (1) + 1);
    out[0] = (char)code; out[1] = '\0';
    return out;
}

char * i32_to_string(int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (16) + 1);
    snprintf(out, 16, "%d", n);
    return out;
}

int contains_ci_(char * haystack __attribute__((unused)), char * needle __attribute__((unused))) {
    return (string_contains_ci_impl(haystack, needle) != 0);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

double parse_f64_raw(char * s __attribute__((unused))) {
    return (strtod(s, NULL));
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    double i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    double start = 0;
    double i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        double __recur_tmp_0 = start;
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

int raw_spawn(char * path __attribute__((unused)), char * arg1 __attribute__((unused))) {
    return (spawn_detached_impl(path, arg1));
}

int raw_kill(int pid __attribute__((unused))) {
    return (process_kill_impl(pid));
}

Result process_spawn(char * path __attribute__((unused)), char * arg1 __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int pid __attribute__((unused)) = raw_spawn(path, arg1);
    if ((pid < 0)) {
    return result_err(ProcessError_box(dest, ProcessError_SpawnFailed()));
    } else {
    return result_ok(int_box(dest, pid));
    }
}

Result process_kill(int pid __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((raw_kill(pid) < 0)) {
    return result_err(ProcessError_box(dest, ProcessError_KillFailed()));
    } else {
    return result_ok(NULL);
    }
}

char * run_capture(char * cmd __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (run_capture_impl(cmd, dest));
}

int run_capture_exit_code(void) {
    return (run_capture_last_exit_code_impl());
}

