/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline __attribute__((unused)) ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

typedef struct {
    int fd;
} L2Socket;
static inline __attribute__((unused)) L2Socket L2Socket_new(int fd) {
    L2Socket v;
    v.fd = fd;
    return v;
}

typedef enum {
    L2Error_TAG_PermissionDenied,
    L2Error_TAG_OpenFailed,
    L2Error_TAG_InterfaceNotFound,
    L2Error_TAG_BindFailed,
    L2Error_TAG_SendFailed,
} L2Error_Tag;
typedef struct { L2Error_Tag tag; void *value; } L2Error;
static inline __attribute__((unused)) L2Error L2Error_PermissionDenied(void) { L2Error v; v.tag = L2Error_TAG_PermissionDenied; v.value = NULL; return v; }
static inline __attribute__((unused)) L2Error L2Error_OpenFailed(void) { L2Error v; v.tag = L2Error_TAG_OpenFailed; v.value = NULL; return v; }
static inline __attribute__((unused)) L2Error L2Error_InterfaceNotFound(void) { L2Error v; v.tag = L2Error_TAG_InterfaceNotFound; v.value = NULL; return v; }
static inline __attribute__((unused)) L2Error L2Error_BindFailed(void) { L2Error v; v.tag = L2Error_TAG_BindFailed; v.value = NULL; return v; }
static inline __attribute__((unused)) L2Error L2Error_SendFailed(void) { L2Error v; v.tag = L2Error_TAG_SendFailed; v.value = NULL; return v; }

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
char * char_from_code(int, Arena *);
char * i32_to_string(int, Arena *);
int contains_ci_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
double parse_f64_raw(char *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
int raw_errno();
int raw_l2_open();
int raw_l2_bind(int, char *);
int raw_l2_send(int, char *, int);
int raw_l2_close(int);
L2Error errno_to_l2_error(int);
Result l2_open(Arena *);
Result l2_bind(L2Socket *, char *, Arena *);
Result l2_send(L2Socket *, char *, int, Arena *);
Result l2_close(L2Socket *, Arena *);

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

static inline L2Error *L2Error_box(Arena *dest, L2Error v) {
    L2Error *p = (L2Error *)arena_alloc(dest, sizeof(L2Error));
    *p = v;
    return p;
}

static inline L2Socket *L2Socket_box(Arena *dest, L2Socket v) {
    L2Socket *p = (L2Socket *)arena_alloc(dest, sizeof(L2Socket));
    *p = v;
    return p;
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

char * char_from_code(int code __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (1) + 1);
    out[0] = (char)code; out[1] = '\0';
    return out;
}

char * i32_to_string(int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (16) + 1);
    snprintf(out, 16, "%d", n);
    return out;
}

int contains_ci_(char * haystack __attribute__((unused)), char * needle __attribute__((unused))) {
    return (string_contains_ci_impl(haystack, needle) != 0);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

double parse_f64_raw(char * s __attribute__((unused))) {
    return (strtod(s, NULL));
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    int i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        int __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    int start = 0;
    int i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        int __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        int __recur_tmp_0 = start;
        int __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

int raw_errno(void) {
    return (errno);
}

int raw_l2_open(void) {
    return (l2socket_open_impl());
}

int raw_l2_bind(int fd __attribute__((unused)), char * iface __attribute__((unused))) {
    return (l2socket_bind_impl(fd, iface));
}

int raw_l2_send(int fd __attribute__((unused)), char * data __attribute__((unused)), int len __attribute__((unused))) {
    return (l2socket_send_impl(fd, data, len));
}

int raw_l2_close(int fd __attribute__((unused))) {
    return (l2socket_close_impl(fd));
}

L2Error errno_to_l2_error(int e __attribute__((unused))) {
    if ((e == 1)) {
    return L2Error_PermissionDenied();
    } else {
    return L2Error_OpenFailed();
    }
}

Result l2_open(Arena *dest __attribute__((unused))) {
    int fd __attribute__((unused)) = raw_l2_open();
    if ((fd < 0)) {
    return result_err(L2Error_box(dest, errno_to_l2_error(raw_errno())));
    } else {
    return result_ok(L2Socket_box(dest, L2Socket_new(fd)));
    }
}

Result l2_bind(L2Socket * s __attribute__((unused)), char * iface __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int rc __attribute__((unused)) = raw_l2_bind((s)->fd, iface);
    if ((rc >= 0)) {
    return result_ok(NULL);
    } else {
    if ((rc == -2)) {
    return result_err(L2Error_box(dest, L2Error_InterfaceNotFound()));
    } else {
    return result_err(L2Error_box(dest, L2Error_BindFailed()));
    }
    }
}

Result l2_send(L2Socket * s __attribute__((unused)), char * data __attribute__((unused)), int data_len __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = raw_l2_send((s)->fd, data, data_len);
    if ((n < 0)) {
    return result_err(L2Error_box(dest, L2Error_SendFailed()));
    } else {
    return result_ok(int_box(dest, n));
    }
}

Result l2_close(L2Socket * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((raw_l2_close((s)->fd) < 0)) {
    return result_err(L2Error_box(dest, L2Error_SendFailed()));
    } else {
    return result_ok(NULL);
    }
}

