/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef enum {
    Quant_TAG_One,
    Quant_TAG_ZeroOrMore,
    Quant_TAG_OneOrMore,
    Quant_TAG_Optional,
} Quant_Tag;
typedef struct { Quant_Tag tag; void *value; } Quant;
static inline __attribute__((unused)) Quant Quant_One(void) { Quant v; v.tag = Quant_TAG_One; v.value = NULL; return v; }
static inline __attribute__((unused)) Quant Quant_ZeroOrMore(void) { Quant v; v.tag = Quant_TAG_ZeroOrMore; v.value = NULL; return v; }
static inline __attribute__((unused)) Quant Quant_OneOrMore(void) { Quant v; v.tag = Quant_TAG_OneOrMore; v.value = NULL; return v; }
static inline __attribute__((unused)) Quant Quant_Optional(void) { Quant v; v.tag = Quant_TAG_Optional; v.value = NULL; return v; }

typedef struct {
    int is_wild;
    int state;
    Quant quant;
} PatternElem;
static inline __attribute__((unused)) PatternElem PatternElem_new(int is_wild, int state, Quant quant) {
    PatternElem v;
    v.is_wild = is_wild;
    v.state = state;
    v.quant = quant;
    return v;
}

int vec_i32_at(Vec *, int);
void push_i32_(Vec *, int);
PatternElem elem_lit(int, Quant);
PatternElem elem_wild(Quant);
int match_one(PatternElem *, Vec *, int);
Vec match_elem(PatternElem *, Vec *, int, Arena *);
int count_reps(PatternElem *, Vec *, int);
int match_seq(Vec *, int, Vec *, int, Arena *);
int is_match(Vec *, int, int, Vec *, Arena *);
int self_test(Arena *);

static inline PatternElem *PatternElem_box(Arena *dest, PatternElem v) {
    PatternElem *p = (PatternElem *)arena_alloc(dest, sizeof(PatternElem));
    *p = v;
    return p;
}

int vec_i32_at(Vec * v __attribute__((unused)), int idx __attribute__((unused))) {
    return (*(int *)vec_get(v, idx));
}

void push_i32_(Vec * v __attribute__((unused)), int val __attribute__((unused))) {
    vec_push_(v, vec_box_i32(v, val));
}

PatternElem elem_lit(int state __attribute__((unused)), Quant quant __attribute__((unused))) {
    return PatternElem_new(0, state, quant);
}

PatternElem elem_wild(Quant quant __attribute__((unused))) {
    return PatternElem_new(1, 0, quant);
}

int match_one(PatternElem * elem __attribute__((unused)), Vec * target __attribute__((unused)), int pos __attribute__((unused))) {
    if ((pos >= vec_len(target))) {
    return 0;
    } else {
    if ((elem)->is_wild) {
    return 1;
    } else {
    return ((elem)->state == (*((int *)(vec_get(target, pos)))));
    }
    }
}

Vec match_elem(PatternElem * elem __attribute__((unused)), Vec * target __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec __match_result_0 __attribute__((unused)) = {0};
    Quant __match_tmp_0 = (elem)->quant;
    if (__match_tmp_0.tag == 0) {
        Vec out __attribute__((unused)) = vec_new(dest);
    if (match_one(elem, target, pos)) {
        (void)(vec_push_(&(out), vec_box_i32(&(out), (pos + 1))));
    }
        __match_result_0 = out;
    }
    else if (__match_tmp_0.tag == 3) {
        Vec out __attribute__((unused)) = vec_new(dest);
    if (match_one(elem, target, pos)) {
        (void)(vec_push_(&(out), vec_box_i32(&(out), (pos + 1))));
    }
    (void)(vec_push_(&(out), vec_box_i32(&(out), pos)));
        __match_result_0 = out;
    }
    else if (__match_tmp_0.tag == 2) {
        if ((!(match_one(elem, target, pos)))) {
        __match_result_0 = vec_new(dest);
        } else {
        int reps __attribute__((unused)) = count_reps(elem, target, (pos + 1));
        Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_0 __attribute__((unused));
    int k = reps;
    while (1) {
        if ((k >= 0)) {
    (void)(vec_push_(&(out), vec_box_i32(&(out), (pos + (1 + k)))));
        int __recur_tmp_0 = (k - 1);
        k = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
        __match_result_0 = out;
        }
    }
    else if (__match_tmp_0.tag == 1) {
        int reps __attribute__((unused)) = count_reps(elem, target, pos);
        Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_1 __attribute__((unused));
    int n = reps;
    while (1) {
        if ((n >= 0)) {
    (void)(vec_push_(&(out), vec_box_i32(&(out), (pos + n))));
        int __recur_tmp_0 = (n - 1);
        n = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
        __match_result_0 = out;
    }
    return __match_result_0;
}

int count_reps(PatternElem * elem __attribute__((unused)), Vec * target __attribute__((unused)), int pos __attribute__((unused))) {
    double __loop_result_2 __attribute__((unused));
    double n = 0;
    while (1) {
        if (match_one(elem, target, (pos + n))) {
        double __recur_tmp_0 = (n + 1);
        n = __recur_tmp_0;
        continue;
        } else {
        __loop_result_2 = n;
        break;
        }
    }
    return __loop_result_2;
}

int match_seq(Vec * elems __attribute__((unused)), int i __attribute__((unused)), Vec * target __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((i >= vec_len(elems))) {
    return pos;
    } else {
    Vec candidates __attribute__((unused)) = match_elem(vec_get(elems, i), target, pos, dest);
    double __loop_result_3 __attribute__((unused));
    double ci = 0;
    while (1) {
        if ((ci >= vec_len(&(candidates)))) {
        __loop_result_3 = -1;
        break;
        } else {
        int rest __attribute__((unused)) = match_seq(elems, (i + 1), target, vec_i32_at(&(candidates), ci), dest);
        if ((rest >= 0)) {
        __loop_result_3 = rest;
        break;
        } else {
        double __recur_tmp_0 = (ci + 1);
        ci = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_3;
    }
}

int is_match(Vec * elems __attribute__((unused)), int anchored_start __attribute__((unused)), int anchored_end __attribute__((unused)), Vec * target __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (anchored_start) {
    int end __attribute__((unused)) = match_seq(elems, 0, target, 0, dest);
    if ((end < 0)) {
    return 0;
    } else {
    if (anchored_end) {
    return (end == vec_len(target));
    } else {
    return 1;
    }
    }
    } else {
    int __loop_result_4 __attribute__((unused));
    double start = 0;
    while (1) {
        if ((start > vec_len(target))) {
        __loop_result_4 = 0;
        break;
        } else {
        int end __attribute__((unused)) = match_seq(elems, 0, target, start, dest);
        if ((end < 0)) {
        double __recur_tmp_0 = (start + 1);
        start = __recur_tmp_0;
        continue;
        } else {
        if (anchored_end) {
        __loop_result_4 = (end == vec_len(target));
        break;
        } else {
        __loop_result_4 = 1;
        break;
        }
        }
        }
    }
    return __loop_result_4;
    }
}

int self_test(Arena *dest __attribute__((unused))) {
    PatternElem e0 __attribute__((unused)) = elem_lit(1, Quant_One());
    PatternElem e1 __attribute__((unused)) = elem_lit(2, Quant_OneOrMore());
    PatternElem e2 __attribute__((unused)) = elem_lit(3, Quant_One());
    Vec pattern __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(pattern), PatternElem_box(dest, e0)));
    (void)(vec_push_(&(pattern), PatternElem_box(dest, e1)));
    (void)(vec_push_(&(pattern), PatternElem_box(dest, e2)));
    Vec target_ok __attribute__((unused)) = vec_new(dest);
    (void)(push_i32_(&(target_ok), 1));
    (void)(push_i32_(&(target_ok), 2));
    (void)(push_i32_(&(target_ok), 2));
    (void)(push_i32_(&(target_ok), 3));
    int case1 __attribute__((unused)) = is_match(&(pattern), 1, 1, &(target_ok), dest);
    Vec target_bad __attribute__((unused)) = vec_new(dest);
    (void)(push_i32_(&(target_bad), 1));
    (void)(push_i32_(&(target_bad), 3));
    int case2 __attribute__((unused)) = (!(is_match(&(pattern), 1, 1, &(target_bad), dest)));
    PatternElem wild_elem __attribute__((unused)) = elem_wild(Quant_One());
    Vec wild_pattern __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(wild_pattern), PatternElem_box(dest, wild_elem)));
    Vec target_single __attribute__((unused)) = vec_new(dest);
    (void)(push_i32_(&(target_single), 0));
    int case3 __attribute__((unused)) = is_match(&(wild_pattern), 1, 1, &(target_single), dest);
    PatternElem opt_elem __attribute__((unused)) = elem_lit(0, Quant_Optional());
    Vec opt_pattern __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(opt_pattern), PatternElem_box(dest, opt_elem)));
    Vec empty_target __attribute__((unused)) = vec_new(dest);
    int case4 __attribute__((unused)) = is_match(&(opt_pattern), 1, 1, &(empty_target), dest);
    return (case1 && (case2 && (case3 && case4)));
}

