/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

int symbol_zero();
int symbol_one();
int symbol_minus();
int symbol_plus();
int base4_xor(int, int);
int base4_and(int, int);
int base4_or(int, int);
int base4_add(int, int);
int base4_subtract(int, int);
int base4_iterate(int, int (*)(int, int), int);
int base4_cycle_length(int, int (*)(int, int));
int dimlen(Vec *);
int vec_eq(Vec *, Vec *);
Option vec_xor(Vec *, Vec *, Arena *);
Option vec_and(Vec *, Vec *, Arena *);
Option vec_or(Vec *, Vec *, Arena *);
Option vec_add(Vec *, Vec *, Arena *);
Option vec_subtract(Vec *, Vec *, Arena *);
Option dot(Vec *, Vec *, Arena *);

static inline Vec *Vec_box(Arena *dest, Vec v) {
    Vec *p = (Vec *)arena_alloc(dest, sizeof(Vec));
    *p = v;
    return p;
}

static inline double *double_box(Arena *dest, double v) {
    double *p = (double *)arena_alloc(dest, sizeof(double));
    *p = v;
    return p;
}

int symbol_zero(void) {
    return 0;
}

int symbol_one(void) {
    return 1;
}

int symbol_minus(void) {
    return 2;
}

int symbol_plus(void) {
    return 3;
}

int base4_xor(int a __attribute__((unused)), int b __attribute__((unused))) {
    return (a ^ b);
}

int base4_and(int a __attribute__((unused)), int b __attribute__((unused))) {
    return (a & b);
}

int base4_or(int a __attribute__((unused)), int b __attribute__((unused))) {
    return (a | b);
}

int base4_add(int a __attribute__((unused)), int b __attribute__((unused))) {
    return ((a + b) % 4);
}

int base4_subtract(int a __attribute__((unused)), int b __attribute__((unused))) {
    return (((a - b) + 4) % 4);
}

int base4_iterate(int start __attribute__((unused)), int (*op)(int, int) __attribute__((unused)), int steps __attribute__((unused))) {
    int __loop_result_0 __attribute__((unused));
    int state = start;
    double i = 0;
    while (1) {
        if ((i >= steps)) {
        __loop_result_0 = state;
        break;
        } else {
        int __recur_tmp_0 = op(state, start);
        double __recur_tmp_1 = (i + 1);
        state = __recur_tmp_0;
        i = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
}

int base4_cycle_length(int start __attribute__((unused)), int (*op)(int, int) __attribute__((unused))) {
    double __loop_result_1 __attribute__((unused));
    int state = op(start, start);
    double i = 1;
    while (1) {
        if ((state == start)) {
        __loop_result_1 = i;
        break;
        } else {
        if ((i >= 5)) {
        __loop_result_1 = -1;
        break;
        } else {
        int __recur_tmp_0 = op(state, start);
        double __recur_tmp_1 = (i + 1);
        state = __recur_tmp_0;
        i = __recur_tmp_1;
        continue;
        }
        }
    }
    return __loop_result_1;
}

int dimlen(Vec * v __attribute__((unused))) {
    return vec_len(v);
}

int vec_eq(Vec * a __attribute__((unused)), Vec * b __attribute__((unused))) {
    if ((!((vec_len(a) == vec_len(b))))) {
    return 0;
    } else {
    int __loop_result_2 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i >= vec_len(a))) {
        __loop_result_2 = 1;
        break;
        } else {
        if ((!(((*((int *)(vec_get(a, i)))) == (*((int *)(vec_get(b, i)))))))) {
        __loop_result_2 = 0;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_2;
    }
}

Option vec_xor(Vec * a __attribute__((unused)), Vec * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!((vec_len(a) == vec_len(b))))) {
    return option_none();
    } else {
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_3 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < vec_len(a))) {
    (void)(vec_push_(&(out), vec_box_i32(&(out), base4_xor((*((int *)(vec_get(a, i)))), (*((int *)(vec_get(b, i))))))));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return option_some(Vec_box(dest, out));
    }
}

Option vec_and(Vec * a __attribute__((unused)), Vec * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!((vec_len(a) == vec_len(b))))) {
    return option_none();
    } else {
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_4 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < vec_len(a))) {
    (void)(vec_push_(&(out), vec_box_i32(&(out), base4_and((*((int *)(vec_get(a, i)))), (*((int *)(vec_get(b, i))))))));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return option_some(Vec_box(dest, out));
    }
}

Option vec_or(Vec * a __attribute__((unused)), Vec * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!((vec_len(a) == vec_len(b))))) {
    return option_none();
    } else {
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_5 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < vec_len(a))) {
    (void)(vec_push_(&(out), vec_box_i32(&(out), base4_or((*((int *)(vec_get(a, i)))), (*((int *)(vec_get(b, i))))))));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return option_some(Vec_box(dest, out));
    }
}

Option vec_add(Vec * a __attribute__((unused)), Vec * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!((vec_len(a) == vec_len(b))))) {
    return option_none();
    } else {
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_6 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < vec_len(a))) {
    (void)(vec_push_(&(out), vec_box_i32(&(out), base4_add((*((int *)(vec_get(a, i)))), (*((int *)(vec_get(b, i))))))));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return option_some(Vec_box(dest, out));
    }
}

Option vec_subtract(Vec * a __attribute__((unused)), Vec * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!((vec_len(a) == vec_len(b))))) {
    return option_none();
    } else {
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_7 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < vec_len(a))) {
    (void)(vec_push_(&(out), vec_box_i32(&(out), base4_subtract((*((int *)(vec_get(a, i)))), (*((int *)(vec_get(b, i))))))));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return option_some(Vec_box(dest, out));
    }
}

Option dot(Vec * a __attribute__((unused)), Vec * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!((vec_len(a) == vec_len(b))))) {
    return option_none();
    } else {
    Option __loop_result_8 __attribute__((unused));
    double i = 0;
    double acc = 0;
    while (1) {
        if ((i >= vec_len(a))) {
        __loop_result_8 = option_some(double_box(dest, acc));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = base4_add(acc, base4_and((*((int *)(vec_get(a, i)))), (*((int *)(vec_get(b, i))))));
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_8;
    }
}

