/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    Vec data;
    Vec shape;
    Vec strides;
} NDArray;
static inline __attribute__((unused)) NDArray NDArray_new(Vec data, Vec shape, Vec strides) {
    NDArray v;
    v.data = data;
    v.shape = shape;
    v.strides = strides;
    return v;
}

typedef struct {
    char * message;
} ShapeError;
static inline __attribute__((unused)) ShapeError ShapeError_new(char * message) {
    ShapeError v;
    v.message = message;
    return v;
}

typedef struct {
    char * message;
} IndexError;
static inline __attribute__((unused)) IndexError IndexError_new(char * message) {
    IndexError v;
    v.message = message;
    return v;
}

typedef enum {
    LinalgError_TAG_NotImplemented,
} LinalgError_Tag;
typedef struct { LinalgError_Tag tag; void *value; } LinalgError;
static inline __attribute__((unused)) LinalgError LinalgError_NotImplemented(void) { LinalgError v; v.tag = LinalgError_TAG_NotImplemented; v.value = NULL; return v; }

typedef struct {
    int rows;
    int cols;
    Vec values;
    Vec col_indices;
    Vec row_ptr;
} CsrMatrix;
static inline __attribute__((unused)) CsrMatrix CsrMatrix_new(int rows, int cols, Vec values, Vec col_indices, Vec row_ptr) {
    CsrMatrix v;
    v.rows = rows;
    v.cols = cols;
    v.values = values;
    v.col_indices = col_indices;
    v.row_ptr = row_ptr;
    return v;
}

typedef enum {
    SparseError_TAG_ShapeMismatch,
    SparseError_TAG_IndexOutOfRange,
} SparseError_Tag;
typedef struct { SparseError_Tag tag; void *value; } SparseError;
static inline __attribute__((unused)) SparseError SparseError_ShapeMismatch(void) { SparseError v; v.tag = SparseError_TAG_ShapeMismatch; v.value = NULL; return v; }
static inline __attribute__((unused)) SparseError SparseError_IndexOutOfRange(void) { SparseError v; v.tag = SparseError_TAG_IndexOutOfRange; v.value = NULL; return v; }

int product(Vec *);
Vec strides_for(Vec *, Arena *);
NDArray zeros(Vec, Arena *);
Result from_vec(Vec, Vec, Arena *);
int flat_index(NDArray *, Vec *);
Result array_get(NDArray *, Vec, Arena *);
Result set_(NDArray *, Vec, double, Arena *);
Result reshape(NDArray *, Vec, Arena *);
int same_shape_(NDArray *, NDArray *);
Result elementwise(NDArray *, NDArray *, double (*)(double, double), Arena *);
Result add(NDArray *, NDArray *, Arena *);
Result mul_elementwise(NDArray *, NDArray *, Arena *);
Result matmul(NDArray *, NDArray *, Arena *);
NDArray transpose(NDArray *, Arena *);
Result dot(NDArray *, NDArray *, Arena *);
Result inverse(NDArray *, Arena *);
Result solve(NDArray *, NDArray *, Arena *);
int as_i32(int);
void init_i32_zeros_(Vec *, int);
void init_f64_zeros_(Vec *, int);
void copy_first_n_(Vec *, Vec *, int);
Result count_per_row(Vec *, Vec *, int, int, Arena *);
void prefix_sum_into_(Vec *, Vec *, int);
void scatter_into_(Vec *, Vec *, Vec *, Vec *, Vec *, Vec *, int);
Result csr_from_coo(int, int, Vec *, Vec *, Vec *, Arena *);
int csr_nnz(CsrMatrix *);
double find_in_row(Vec *, Vec *, int, int, int);
double csr_get(CsrMatrix *, int, int);
double row_dot(Vec *, Vec *, Vec *, int, int);
void matvec_rows_(Vec *, Vec *, Vec *, Vec *, Vec *, int);
Result csr_matvec(CsrMatrix *, Vec *, Arena *);

static inline NDArray *NDArray_box(Arena *dest, NDArray v) {
    NDArray *p = (NDArray *)arena_alloc(dest, sizeof(NDArray));
    *p = v;
    return p;
}

static inline ShapeError *ShapeError_box(Arena *dest, ShapeError v) {
    ShapeError *p = (ShapeError *)arena_alloc(dest, sizeof(ShapeError));
    *p = v;
    return p;
}

static inline IndexError *IndexError_box(Arena *dest, IndexError v) {
    IndexError *p = (IndexError *)arena_alloc(dest, sizeof(IndexError));
    *p = v;
    return p;
}

static inline double *double_box(Arena *dest, double v) {
    double *p = (double *)arena_alloc(dest, sizeof(double));
    *p = v;
    return p;
}

static inline LinalgError *LinalgError_box(Arena *dest, LinalgError v) {
    LinalgError *p = (LinalgError *)arena_alloc(dest, sizeof(LinalgError));
    *p = v;
    return p;
}

static inline SparseError *SparseError_box(Arena *dest, SparseError v) {
    SparseError *p = (SparseError *)arena_alloc(dest, sizeof(SparseError));
    *p = v;
    return p;
}

static inline CsrMatrix *CsrMatrix_box(Arena *dest, CsrMatrix v) {
    CsrMatrix *p = (CsrMatrix *)arena_alloc(dest, sizeof(CsrMatrix));
    *p = v;
    return p;
}

static inline Vec *Vec_box(Arena *dest, Vec v) {
    Vec *p = (Vec *)arena_alloc(dest, sizeof(Vec));
    *p = v;
    return p;
}

static inline int int_vec_eq(Vec *a, Vec *b) {
    if (vec_len(a) != vec_len(b)) return 0;
    for (int i = 0; i < vec_len(a); i++) {
        if (*(int *)vec_get(a, i) != *(int *)vec_get(b, i)) return 0;
    }
    return 1;
}

static inline Vec __veclit_0(Arena *dest, int e0, int e1) {
    Vec v = vec_new(dest);
    vec_push_(&v, vec_box_i32(&v, e0));
    vec_push_(&v, vec_box_i32(&v, e1));
    return v;
}

static inline Vec __veclit_1(Arena *dest, int e0, int e1) {
    Vec v = vec_new(dest);
    vec_push_(&v, vec_box_i32(&v, e0));
    vec_push_(&v, vec_box_i32(&v, e1));
    return v;
}

static inline Vec __veclit_2(Arena *dest, int e0, int e1) {
    Vec v = vec_new(dest);
    vec_push_(&v, vec_box_i32(&v, e0));
    vec_push_(&v, vec_box_i32(&v, e1));
    return v;
}

static inline Vec __veclit_3(Arena *dest, int e0, int e1) {
    Vec v = vec_new(dest);
    vec_push_(&v, vec_box_i32(&v, e0));
    vec_push_(&v, vec_box_i32(&v, e1));
    return v;
}

static inline Vec __veclit_4(Arena *dest, int e0, int e1) {
    Vec v = vec_new(dest);
    vec_push_(&v, vec_box_i32(&v, e0));
    vec_push_(&v, vec_box_i32(&v, e1));
    return v;
}

static inline Vec __veclit_5(Arena *dest, int e0, int e1) {
    Vec v = vec_new(dest);
    vec_push_(&v, vec_box_i32(&v, e0));
    vec_push_(&v, vec_box_i32(&v, e1));
    return v;
}

static inline Vec __veclit_6(Arena *dest, int e0, int e1) {
    Vec v = vec_new(dest);
    vec_push_(&v, vec_box_i32(&v, e0));
    vec_push_(&v, vec_box_i32(&v, e1));
    return v;
}

static double __lambda_0(double x, double y) {
    return (x + y);
}

static double __lambda_1(double x, double y) {
    return (x * y);
}

int product(Vec * shape __attribute__((unused))) {
    int __loop_result_0 __attribute__((unused));
    int i = 0;
    int acc = 1;
    while (1) {
        if ((i >= vec_len(shape))) {
        __loop_result_0 = acc;
        break;
        } else {
        int __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (acc * (*((int *)(vec_get(shape, i)))));
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
}

Vec strides_for(Vec * shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = vec_len(shape);
    int total __attribute__((unused)) = product(shape);
    Vec s __attribute__((unused)) = vec_new(dest);
    void * __loop_result_1 __attribute__((unused));
    int i = 0;
    int running = total;
    while (1) {
        if ((i < n)) {
        int next __attribute__((unused)) = (running / (*((int *)(vec_get(shape, i)))));
        (void)(vec_push_(&(s), vec_box_i32(&(s), next)));
        int __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = next;
        i = __recur_tmp_0;
        running = __recur_tmp_1;
        continue;
        } else {
            break;
        }
    }
    return s;
}

NDArray zeros(Vec shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = product(&(shape));
    Vec data __attribute__((unused)) = vec_new(dest);
    void * __loop_result_2 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i < n)) {
    (void)(vec_push_(&(data), vec_box_f64(&(data), 0.0)));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return NDArray_new(data, shape, strides_for(&(shape), dest));
}

Result from_vec(Vec data __attribute__((unused)), Vec shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((vec_len(&(data)) == product(&(shape)))) {
    return result_ok(NDArray_box(dest, NDArray_new(data, shape, strides_for(&(shape), dest))));
    } else {
    return result_err(ShapeError_box(dest, ShapeError_new("data length does not match shape product")));
    }
}

int flat_index(NDArray * a __attribute__((unused)), Vec * idx __attribute__((unused))) {
    int __loop_result_3 __attribute__((unused));
    int i = 0;
    int offset = 0;
    while (1) {
        if ((i >= vec_len(idx))) {
        __loop_result_3 = offset;
        break;
        } else {
        int __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (offset + ((*((int *)(vec_get(idx, i)))) * (*((int *)(vec_get(&((a)->strides), i))))));
        i = __recur_tmp_0;
        offset = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_3;
}

Result array_get(NDArray * a __attribute__((unused)), Vec idx __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int off __attribute__((unused)) = flat_index(a, &(idx));
    if (((off < 0) || (off >= vec_len(&((a)->data))))) {
    return result_err(IndexError_box(dest, IndexError_new("out of bounds")));
    } else {
    return result_ok(double_box(dest, (*((double *)(vec_get(&((a)->data), off))))));
    }
}

Result set_(NDArray * a __attribute__((unused)), Vec idx __attribute__((unused)), double v __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int off __attribute__((unused)) = flat_index(a, &(idx));
    if (((off < 0) || (off >= vec_len(&((a)->data))))) {
    return result_err(IndexError_box(dest, IndexError_new("out of bounds")));
    } else {
    (void)(vec_set_at_(&((a)->data), off, vec_box_f64(&((a)->data), v)));
    return result_ok(NULL);
    }
}

Result reshape(NDArray * a __attribute__((unused)), Vec new_shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((product(&(new_shape)) == product(&((a)->shape)))) {
    return result_ok(NDArray_box(dest, NDArray_new((a)->data, new_shape, strides_for(&(new_shape), dest))));
    } else {
    return result_err(ShapeError_box(dest, ShapeError_new("reshape must preserve element count")));
    }
}

int same_shape_(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused))) {
    return int_vec_eq(&((a)->shape), &((b)->shape));
}

Result elementwise(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), double (*op)(double, double) __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!(same_shape_(a, b)))) {
    return result_err(ShapeError_box(dest, ShapeError_new("shape mismatch")));
    } else {
    int n __attribute__((unused)) = vec_len(&((a)->data));
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_4 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i < n)) {
    (void)(vec_push_(&(out), vec_box_f64(&(out), op((*((double *)(vec_get(&((a)->data), i)))), (*((double *)(vec_get(&((b)->data), i))))))));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return result_ok(NDArray_box(dest, NDArray_new(out, (a)->shape, (a)->strides)));
    }
}

Result add(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return elementwise(a, b, __lambda_0, dest);
}

Result mul_elementwise(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return elementwise(a, b, __lambda_1, dest);
}

Result matmul(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int a_rows __attribute__((unused)) = (*((int *)(vec_get(&((a)->shape), 0))));
    int a_cols __attribute__((unused)) = (*((int *)(vec_get(&((a)->shape), 1))));
    int b_cols __attribute__((unused)) = (*((int *)(vec_get(&((b)->shape), 1))));
    if ((!((a_cols == (*((int *)(vec_get(&((b)->shape), 0)))))))) {
    return result_err(ShapeError_box(dest, ShapeError_new("inner dimensions must match")));
    } else {
    NDArray out __attribute__((unused)) = zeros(__veclit_0(dest, a_rows, b_cols), dest);
    void * __loop_result_5 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i < a_rows)) {
    void * __loop_result_6 __attribute__((unused));
    int j = 0;
    while (1) {
        if ((j < b_cols)) {
    Result __loop_result_7 __attribute__((unused));
    int k = 0;
    double sum = 0.0;
    while (1) {
        if ((k >= a_cols)) {
        __loop_result_7 = set_(&(out), __veclit_1(dest, i, j), sum, dest);
        break;
        } else {
        int __recur_tmp_0 = (k + 1);
        double __recur_tmp_1 = (sum + ((*((double *)(result_unwrap_check(array_get(a, __veclit_2(dest, i, k), dest)).value))) * (*((double *)(result_unwrap_check(array_get(b, __veclit_3(dest, k, j), dest)).value)))));
        k = __recur_tmp_0;
        sum = __recur_tmp_1;
        continue;
        }
    }
        int __recur_tmp_0 = (j + 1);
        j = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return result_ok(NDArray_box(dest, out));
    }
}

NDArray transpose(NDArray * a __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int rows __attribute__((unused)) = (*((int *)(vec_get(&((a)->shape), 0))));
    int cols __attribute__((unused)) = (*((int *)(vec_get(&((a)->shape), 1))));
    NDArray out __attribute__((unused)) = zeros(__veclit_4(dest, cols, rows), dest);
    void * __loop_result_8 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i < rows)) {
    void * __loop_result_9 __attribute__((unused));
    int j = 0;
    while (1) {
        if ((j < cols)) {
    (void)(set_(&(out), __veclit_5(dest, j, i), (*((double *)(result_unwrap_check(array_get(a, __veclit_6(dest, i, j), dest)).value))), dest));
        int __recur_tmp_0 = (j + 1);
        j = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return out;
}

Result dot(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!((vec_len(&((a)->data)) == vec_len(&((b)->data)))))) {
    return result_err(ShapeError_box(dest, ShapeError_new("length mismatch")));
    } else {
    Result __loop_result_10 __attribute__((unused));
    int i = 0;
    double sum = 0.0;
    while (1) {
        if ((i >= vec_len(&((a)->data)))) {
        __loop_result_10 = result_ok(double_box(dest, sum));
        break;
        } else {
        int __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (sum + ((*((double *)(vec_get(&((a)->data), i)))) * (*((double *)(vec_get(&((b)->data), i))))));
        i = __recur_tmp_0;
        sum = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_10;
    }
}

Result inverse(NDArray * a __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return result_err(LinalgError_box(dest, LinalgError_NotImplemented()));
}

Result solve(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return result_err(LinalgError_box(dest, LinalgError_NotImplemented()));
}

int as_i32(int x __attribute__((unused))) {
    return x;
}

void init_i32_zeros_(Vec * v __attribute__((unused)), int count __attribute__((unused))) {
    void * __loop_result_11 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i < count)) {
    (void)(vec_push_(v, vec_box_i32(v, as_i32(0))));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
}

void init_f64_zeros_(Vec * v __attribute__((unused)), int count __attribute__((unused))) {
    void * __loop_result_12 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i < count)) {
    (void)(vec_push_(v, vec_box_f64(v, 0.0)));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
}

void copy_first_n_(Vec * dst __attribute__((unused)), Vec * src __attribute__((unused)), int n __attribute__((unused))) {
    void * __loop_result_13 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i < n)) {
    (void)(vec_push_(dst, vec_box_i32(dst, as_i32((*((int *)(vec_get(src, i))))))));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
}

Result count_per_row(Vec * counts __attribute__((unused)), Vec * coo_rows __attribute__((unused)), int rows __attribute__((unused)), int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __loop_result_14 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i >= n)) {
        __loop_result_14 = result_ok(NULL);
        break;
        } else {
        int r __attribute__((unused)) = (*((int *)(vec_get(coo_rows, i))));
        if (((r < 0) || (r >= rows))) {
        __loop_result_14 = result_err(SparseError_box(dest, SparseError_IndexOutOfRange()));
        break;
        } else {
        (void)(vec_set_at_(counts, r, vec_box_i32(counts, as_i32(((*((int *)(vec_get(counts, r)))) + 1)))));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_14;
}

void prefix_sum_into_(Vec * row_ptr __attribute__((unused)), Vec * counts __attribute__((unused)), int rows __attribute__((unused))) {
    void * __loop_result_15 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i < rows)) {
    (void)(vec_set_at_(row_ptr, as_i32((i + 1)), vec_box_i32(row_ptr, as_i32(((*((int *)(vec_get(row_ptr, i)))) + (*((int *)(vec_get(counts, i)))))))));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
}

void scatter_into_(Vec * values __attribute__((unused)), Vec * col_indices __attribute__((unused)), Vec * cursor __attribute__((unused)), Vec * coo_rows __attribute__((unused)), Vec * coo_cols __attribute__((unused)), Vec * coo_vals __attribute__((unused)), int n __attribute__((unused))) {
    void * __loop_result_16 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i < n)) {
    int r __attribute__((unused)) = (*((int *)(vec_get(coo_rows, i))));
    int slot __attribute__((unused)) = (*((int *)(vec_get(cursor, r))));
    (void)(vec_set_at_(values, slot, vec_box_f64(values, (*((double *)(vec_get(coo_vals, i)))))));
    (void)(vec_set_at_(col_indices, slot, vec_box_i32(col_indices, as_i32((*((int *)(vec_get(coo_cols, i))))))));
    (void)(vec_set_at_(cursor, r, vec_box_i32(cursor, as_i32((slot + 1)))));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
}

Result csr_from_coo(int rows __attribute__((unused)), int cols __attribute__((unused)), Vec * coo_rows __attribute__((unused)), Vec * coo_cols __attribute__((unused)), Vec * coo_vals __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = vec_len(coo_rows);
    if (((!((n == vec_len(coo_cols)))) || (!((n == vec_len(coo_vals)))))) {
    return result_err(SparseError_box(dest, SparseError_ShapeMismatch()));
    } else {
    Vec counts __attribute__((unused)) = vec_new(dest);
    (void)(init_i32_zeros_(&(counts), rows));
    Result __match_result_0 __attribute__((unused)) = {0};
    Result __match_tmp_0 = count_per_row(&(counts), coo_rows, rows, n, dest);
    if (__match_tmp_0.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_0.value;
        __match_result_0 = result_err(e);
    }
    else if (__match_tmp_0.tag == 1) {
        void *_ __attribute__((unused)) = __match_tmp_0.value;
        Vec row_ptr __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(row_ptr), vec_box_i32(&(row_ptr), as_i32(0))));
    (void)(init_i32_zeros_(&(row_ptr), rows));
    (void)(prefix_sum_into_(&(row_ptr), &(counts), rows));
        Vec cursor __attribute__((unused)) = vec_new(dest);
    (void)(copy_first_n_(&(cursor), &(row_ptr), rows));
        Vec values __attribute__((unused)) = vec_new(dest);
        Vec col_indices __attribute__((unused)) = vec_new(dest);
    (void)(init_f64_zeros_(&(values), n));
    (void)(init_i32_zeros_(&(col_indices), n));
    (void)(scatter_into_(&(values), &(col_indices), &(cursor), coo_rows, coo_cols, coo_vals, n));
        __match_result_0 = result_ok(CsrMatrix_box(dest, CsrMatrix_new(rows, cols, values, col_indices, row_ptr)));
    }
    return __match_result_0;
    }
}

int csr_nnz(CsrMatrix * m __attribute__((unused))) {
    return vec_len(&((m)->values));
}

double find_in_row(Vec * col_indices __attribute__((unused)), Vec * values __attribute__((unused)), int col __attribute__((unused)), int k __attribute__((unused)), int end __attribute__((unused))) {
    if ((k >= end)) {
    return 0.0;
    } else {
    if (((*((int *)(vec_get(col_indices, k)))) == col)) {
    return (*((double *)(vec_get(values, k))));
    } else {
    return find_in_row(col_indices, values, col, (k + 1), end);
    }
    }
}

double csr_get(CsrMatrix * m __attribute__((unused)), int row __attribute__((unused)), int col __attribute__((unused))) {
    int start __attribute__((unused)) = (*((int *)(vec_get(&((m)->row_ptr), row))));
    int end __attribute__((unused)) = (*((int *)(vec_get(&((m)->row_ptr), as_i32((row + 1))))));
    return find_in_row(&((m)->col_indices), &((m)->values), col, start, end);
}

double row_dot(Vec * values __attribute__((unused)), Vec * col_indices __attribute__((unused)), Vec * x __attribute__((unused)), int k __attribute__((unused)), int end __attribute__((unused))) {
    if ((k >= end)) {
    return 0.0;
    } else {
    return (((*((double *)(vec_get(values, k)))) * (*((double *)(vec_get(x, (*((int *)(vec_get(col_indices, k))))))))) + row_dot(values, col_indices, x, (k + 1), end));
    }
}

void matvec_rows_(Vec * row_ptr __attribute__((unused)), Vec * col_indices __attribute__((unused)), Vec * values __attribute__((unused)), Vec * x __attribute__((unused)), Vec * y __attribute__((unused)), int rows __attribute__((unused))) {
    void * __loop_result_17 __attribute__((unused));
    int i = 0;
    while (1) {
        if ((i < rows)) {
        int start __attribute__((unused)) = (*((int *)(vec_get(row_ptr, i))));
        int end __attribute__((unused)) = (*((int *)(vec_get(row_ptr, as_i32((i + 1))))));
        (void)(vec_set_at_(y, i, vec_box_f64(y, row_dot(values, col_indices, x, start, end))));
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
}

Result csr_matvec(CsrMatrix * m __attribute__((unused)), Vec * x __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!((vec_len(x) == (m)->cols)))) {
    return result_err(SparseError_box(dest, SparseError_ShapeMismatch()));
    } else {
    Vec y __attribute__((unused)) = vec_new(dest);
    (void)(init_f64_zeros_(&(y), (m)->rows));
    (void)(matvec_rows_(&((m)->row_ptr), &((m)->col_indices), &((m)->values), x, &(y), (m)->rows));
    return result_ok(Vec_box(dest, y));
    }
}

