/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

typedef struct {
    Vec data;
    Vec shape;
    Vec strides;
} NDArray;
static inline NDArray NDArray_new(Vec data, Vec shape, Vec strides) {
    NDArray v;
    v.data = data;
    v.shape = shape;
    v.strides = strides;
    return v;
}

typedef struct {
    char * message;
} ShapeError;
static inline ShapeError ShapeError_new(char * message) {
    ShapeError v;
    v.message = message;
    return v;
}

typedef struct {
    char * message;
} IndexError;
static inline IndexError IndexError_new(char * message) {
    IndexError v;
    v.message = message;
    return v;
}

typedef struct {
    int fd;
} FileHandle;
static inline FileHandle FileHandle_new(int fd) {
    FileHandle v;
    v.fd = fd;
    return v;
}

typedef enum {
    IoError_TAG_NotFound,
    IoError_TAG_PermissionDenied,
    IoError_TAG_AlreadyExists,
    IoError_TAG_Other,
} IoError_Tag;
typedef struct { IoError_Tag tag; void *value; } IoError;
static inline IoError IoError_NotFound(void) { IoError v; v.tag = IoError_TAG_NotFound; v.value = NULL; return v; }
static inline IoError IoError_PermissionDenied(void) { IoError v; v.tag = IoError_TAG_PermissionDenied; v.value = NULL; return v; }
static inline IoError IoError_AlreadyExists(void) { IoError v; v.tag = IoError_TAG_AlreadyExists; v.value = NULL; return v; }
static inline IoError IoError_Other(void) { IoError v; v.tag = IoError_TAG_Other; v.value = NULL; return v; }

typedef enum {
    OpenMode_TAG_Read,
    OpenMode_TAG_Write,
    OpenMode_TAG_Append,
} OpenMode_Tag;
typedef struct { OpenMode_Tag tag; void *value; } OpenMode;
static inline OpenMode OpenMode_Read(void) { OpenMode v; v.tag = OpenMode_TAG_Read; v.value = NULL; return v; }
static inline OpenMode OpenMode_Write(void) { OpenMode v; v.tag = OpenMode_TAG_Write; v.value = NULL; return v; }
static inline OpenMode OpenMode_Append(void) { OpenMode v; v.tag = OpenMode_TAG_Append; v.value = NULL; return v; }

typedef enum {
    AnchorKind_TAG_Start,
    AnchorKind_TAG_End,
    AnchorKind_TAG_WordBoundary,
} AnchorKind_Tag;
typedef struct { AnchorKind_Tag tag; void *value; } AnchorKind;
static inline AnchorKind AnchorKind_Start(void) { AnchorKind v; v.tag = AnchorKind_TAG_Start; v.value = NULL; return v; }
static inline AnchorKind AnchorKind_End(void) { AnchorKind v; v.tag = AnchorKind_TAG_End; v.value = NULL; return v; }
static inline AnchorKind AnchorKind_WordBoundary(void) { AnchorKind v; v.tag = AnchorKind_TAG_WordBoundary; v.value = NULL; return v; }

typedef struct {
    char * lo;
    char * hi;
} CharRange;
static inline CharRange CharRange_new(char * lo, char * hi) {
    CharRange v;
    v.lo = lo;
    v.hi = hi;
    return v;
}

typedef enum {
    PatternNode_TAG_Literal,
    PatternNode_TAG_AnyChar,
    PatternNode_TAG_Concat,
    PatternNode_TAG_Alt,
    PatternNode_TAG_Star,
    PatternNode_TAG_Plus,
    PatternNode_TAG_Optional,
    PatternNode_TAG_Group,
    PatternNode_TAG_CharClass,
    PatternNode_TAG_Anchor,
} PatternNode_Tag;
typedef struct { PatternNode_Tag tag; void *value; } PatternNode;
static inline PatternNode PatternNode_Literal(void *value) { PatternNode v; v.tag = PatternNode_TAG_Literal; v.value = value; return v; }
static inline PatternNode PatternNode_AnyChar(void) { PatternNode v; v.tag = PatternNode_TAG_AnyChar; v.value = NULL; return v; }
static inline PatternNode PatternNode_Concat(void *value) { PatternNode v; v.tag = PatternNode_TAG_Concat; v.value = value; return v; }
static inline PatternNode PatternNode_Alt(void *value) { PatternNode v; v.tag = PatternNode_TAG_Alt; v.value = value; return v; }
typedef struct {
    PatternNode inner;
    int greedy;
} PatternNode_Star_Payload;
static inline PatternNode PatternNode_Star(Arena *dest, PatternNode inner, int greedy) {
    PatternNode_Star_Payload *p = (PatternNode_Star_Payload *)arena_alloc(dest, sizeof(PatternNode_Star_Payload));
    p->inner = inner;
    p->greedy = greedy;
    PatternNode v; v.tag = PatternNode_TAG_Star; v.value = p; return v;
}
typedef struct {
    PatternNode inner;
    int greedy;
} PatternNode_Plus_Payload;
static inline PatternNode PatternNode_Plus(Arena *dest, PatternNode inner, int greedy) {
    PatternNode_Plus_Payload *p = (PatternNode_Plus_Payload *)arena_alloc(dest, sizeof(PatternNode_Plus_Payload));
    p->inner = inner;
    p->greedy = greedy;
    PatternNode v; v.tag = PatternNode_TAG_Plus; v.value = p; return v;
}
typedef struct {
    PatternNode inner;
    int greedy;
} PatternNode_Optional_Payload;
static inline PatternNode PatternNode_Optional(Arena *dest, PatternNode inner, int greedy) {
    PatternNode_Optional_Payload *p = (PatternNode_Optional_Payload *)arena_alloc(dest, sizeof(PatternNode_Optional_Payload));
    p->inner = inner;
    p->greedy = greedy;
    PatternNode v; v.tag = PatternNode_TAG_Optional; v.value = p; return v;
}
typedef struct {
    PatternNode inner;
    Option capture_index;
    Option name;
} PatternNode_Group_Payload;
static inline PatternNode PatternNode_Group(Arena *dest, PatternNode inner, Option capture_index, Option name) {
    PatternNode_Group_Payload *p = (PatternNode_Group_Payload *)arena_alloc(dest, sizeof(PatternNode_Group_Payload));
    p->inner = inner;
    p->capture_index = capture_index;
    p->name = name;
    PatternNode v; v.tag = PatternNode_TAG_Group; v.value = p; return v;
}
typedef struct {
    Vec ranges;
    int negated;
} PatternNode_CharClass_Payload;
static inline PatternNode PatternNode_CharClass(Arena *dest, Vec ranges, int negated) {
    PatternNode_CharClass_Payload *p = (PatternNode_CharClass_Payload *)arena_alloc(dest, sizeof(PatternNode_CharClass_Payload));
    p->ranges = ranges;
    p->negated = negated;
    PatternNode v; v.tag = PatternNode_TAG_CharClass; v.value = p; return v;
}
static inline PatternNode PatternNode_Anchor(void *value) { PatternNode v; v.tag = PatternNode_TAG_Anchor; v.value = value; return v; }

typedef struct {
    PatternNode root;
    int capture_count;
} PatternAst;
static inline PatternAst PatternAst_new(PatternNode root, int capture_count) {
    PatternAst v;
    v.root = root;
    v.capture_count = capture_count;
    return v;
}

typedef struct {
    char * message;
    int pos;
} SyntaxError;
static inline SyntaxError SyntaxError_new(char * message, int pos) {
    SyntaxError v;
    v.message = message;
    v.pos = pos;
    return v;
}

typedef struct {
    PatternNode node;
    int next;
    int ncap;
} ParseStep;
static inline ParseStep ParseStep_new(PatternNode node, int next, int ncap) {
    ParseStep v;
    v.node = node;
    v.next = next;
    v.ncap = ncap;
    return v;
}

typedef struct {
    int max_steps;
} MatchBudget;
static inline MatchBudget MatchBudget_new(int max_steps) {
    MatchBudget v;
    v.max_steps = max_steps;
    return v;
}

typedef struct {
    PatternAst ast;
    MatchBudget budget;
} Regex;
static inline Regex Regex_new(PatternAst ast, MatchBudget budget) {
    Regex v;
    v.ast = ast;
    v.budget = budget;
    return v;
}

typedef struct {
    int start;
    int end;
    Vec groups;
} Match;
static inline Match Match_new(int start, int end, Vec groups) {
    Match v;
    v.start = start;
    v.end = end;
    v.groups = groups;
    return v;
}

typedef enum {
    ExprValue_TAG_Num,
    ExprValue_TAG_Str,
} ExprValue_Tag;
typedef struct { ExprValue_Tag tag; void *value; } ExprValue;
static inline ExprValue ExprValue_Num(void *value) { ExprValue v; v.tag = ExprValue_TAG_Num; v.value = value; return v; }
static inline ExprValue ExprValue_Str(void *value) { ExprValue v; v.tag = ExprValue_TAG_Str; v.value = value; return v; }

typedef struct {
    char * message;
    int pos;
} EvalError;
static inline EvalError EvalError_new(char * message, int pos) {
    EvalError v;
    v.message = message;
    v.pos = pos;
    return v;
}

typedef struct {
    Vec keys;
    Vec values;
} Bindings;
static inline Bindings Bindings_new(Vec keys, Vec values) {
    Bindings v;
    v.keys = keys;
    v.values = values;
    return v;
}

typedef enum {
    ExprNode_TAG_NumLit,
    ExprNode_TAG_StrLit,
    ExprNode_TAG_Var,
    ExprNode_TAG_BinOp,
} ExprNode_Tag;
typedef struct { ExprNode_Tag tag; void *value; } ExprNode;
static inline ExprNode ExprNode_NumLit(void *value) { ExprNode v; v.tag = ExprNode_TAG_NumLit; v.value = value; return v; }
static inline ExprNode ExprNode_StrLit(void *value) { ExprNode v; v.tag = ExprNode_TAG_StrLit; v.value = value; return v; }
static inline ExprNode ExprNode_Var(void *value) { ExprNode v; v.tag = ExprNode_TAG_Var; v.value = value; return v; }
typedef struct {
    char * op;
    ExprNode lhs;
    ExprNode rhs;
} ExprNode_BinOp_Payload;
static inline ExprNode ExprNode_BinOp(Arena *dest, char * op, ExprNode lhs, ExprNode rhs) {
    ExprNode_BinOp_Payload *p = (ExprNode_BinOp_Payload *)arena_alloc(dest, sizeof(ExprNode_BinOp_Payload));
    p->op = op;
    p->lhs = lhs;
    p->rhs = rhs;
    ExprNode v; v.tag = ExprNode_TAG_BinOp; v.value = p; return v;
}

typedef struct {
    ExprNode node;
    int next;
} ExprParseStep;
static inline ExprParseStep ExprParseStep_new(ExprNode node, int next) {
    ExprParseStep v;
    v.node = node;
    v.next = next;
    return v;
}

typedef struct {
    Option pattern;
    char * action;
} AwkRule;
static inline AwkRule AwkRule_new(Option pattern, char * action) {
    AwkRule v;
    v.pattern = pattern;
    v.action = action;
    return v;
}

typedef struct {
    Vec rules;
} AwkProgram;
static inline AwkProgram AwkProgram_new(Vec rules) {
    AwkProgram v;
    v.rules = rules;
    return v;
}

typedef struct {
    Vec fields;
    int nr;
} Record;
static inline Record Record_new(Vec fields, int nr) {
    Record v;
    v.fields = fields;
    v.nr = nr;
    return v;
}

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
int contains_ci_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
int product(Vec *);
Vec strides_for(Vec *, Arena *);
NDArray zeros(Vec, Arena *);
Result from_vec(Vec, Vec, Arena *);
int flat_index(NDArray *, Vec *);
Result get(NDArray *, Vec, Arena *);
Result set_(NDArray *, Vec, double, Arena *);
Result reshape(NDArray *, Vec, Arena *);
int same_shape_(NDArray *, NDArray *);
Result elementwise(NDArray *, NDArray *, double (*)(double, double), Arena *);
Result add(NDArray *, NDArray *, Arena *);
Result mul_elementwise(NDArray *, NDArray *, Arena *);
int raw_open(char *, int);
int raw_close(int);
int raw_write(int, char *);
char * raw_read_all(int, Arena *);
int raw_at_eof_(int);
char * raw_read_line(int, Arena *);
int raw_errno();
int mode_tag_of(OpenMode);
IoError errno_to_io_error(int);
Result file_open(char *, OpenMode, Arena *);
Result file_close(FileHandle, Arena *);
int path_exists_(char *);
Result write_string(FileHandle, char *, Arena *);
Result read_string(FileHandle, Arena *);
Result read_line(FileHandle, Arena *);
double raw_read_f64(int);
Result read_floats(FileHandle, int, Arena *);
Result parse(char *, Arena *);
Result parse_alt(char *, int, int, Arena *);
Result parse_concat(char *, int, int, Arena *);
Result parse_quant(char *, int, int, Arena *);
Result parse_atom(char *, int, int, Arena *);
Result parse_escape(char *, int, int, Arena *);
Result parse_group(char *, int, int, Arena *);
int find_class_close(char *, int, int);
Result parse_class(char *, int, int, Arena *);
Result compile(char *, MatchBudget, Arena *);
AnchorKind unbox_anchor_kind(void *);
int anchor_kind_supported_(AnchorKind);
int node_supported_(PatternNode *);
int all_nodes_supported_(Vec *, int);
int pattern_supported_(Regex *);
int char_matches_(char *, int, char *);
Option ast_literal_text(PatternNode *, Arena *);
Option single_branch_literal(Vec *, Arena *);
Option concat_literal_parts(Vec *, int, char *, Arena *);
Option alt_literal_scan(Vec *, int, char *, Arena *);
Option alt_literal_scan_root(PatternNode *, char *, Arena *);
int literal_matches_at_(char *, int, char *, int);
int string_contains_(char *, char *);
int zero_i32();
int vec_i32_at(Vec *, int);
Vec single_or_empty(int, int, Arena *);
Vec vec_reversed(Vec *, Arena *);
CharRange vec_charrange_at(Vec *, int);
int char_in_range_(int, CharRange);
int char_in_any_range_(int, Vec *, int);
int char_class_matches_(char *, int, Vec *, int);
int anchor_matches_(char *, int, AnchorKind);
Vec match_node(PatternNode *, char *, int, int *, int, Arena *);
Vec match_concat(Vec *, int, char *, int, int *, int, Arena *);
Vec match_alt(Vec *, int, char *, int, int *, int, Arena *);
Vec match_star(PatternNode *, int, char *, int, int *, int, Arena *);
Vec match_plus(PatternNode *, int, char *, int, int *, int, Arena *);
Vec match_optional(PatternNode *, int, char *, int, int *, int, Arena *);
Result is_match(Regex *, char *, Arena *);
Result find(Regex *, char *, Arena *);
int match_end_i32(Match *);
int match_start_i32(Match *);
Match offset_match(Match *, int, Arena *);
Result find_all(Regex *, char *, Arena *);
char * vec_string_at(Vec *, int);
char * join_strings(Vec *, Arena *);
int vec_match_start_at(void *, int);
int vec_match_end_at(void *, int);
char * replace(Regex *, char *, char *, int, Arena *);
Bindings bindings_new(Arena *);
void bindings_set_(Bindings *, char *, ExprValue, Arena *);
ExprValue bindings_get(Bindings *, char *, Arena *);
Result eval(char *, Bindings *, Arena *);
ExprValue eval_tree(ExprNode *, Bindings *, Arena *);
ExprValue apply_binop(char *, ExprValue, ExprValue, Arena *);
double raw_parse_f64(char *);
double coerce_num(ExprValue);
char * coerce_str(ExprValue, Arena *);
char * f64_to_string(double, Arena *);
double i32_to_f64(int);
int is_space_(int);
int is_alpha_(int);
int is_ident_start_(int);
int is_ident_char_(int);
int is_op_char_(int);
int skip_ws(char *, int);
ExprParseStep parse_number(char *, int, Arena *);
ExprParseStep parse_fraction(char *, int, double, Arena *);
Result parse_string_lit(char *, int, Arena *);
ExprParseStep parse_ident(char *, int, Arena *);
Result parse_term(char *, int, Arena *);
Result parse_expr(char *, int, Arena *);
Result parse_expr_rest(char *, ExprNode, int, Arena *);
Result run(FileHandle, AwkProgram *, Arena *);
Record record_from_line(char *, int, Arena *);
char * join_fields(Record, Arena *);
char * concat_field_name(int, Arena *);
void run_rules(Vec *, Record, Arena *);
int unbox_bool(void *);
int rule_matches_(AwkRule *, Record, Arena *);
Bindings bindings_for(Record, Arena *);

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

static inline NDArray *NDArray_box(Arena *dest, NDArray v) {
    NDArray *p = (NDArray *)arena_alloc(dest, sizeof(NDArray));
    *p = v;
    return p;
}

static inline ShapeError *ShapeError_box(Arena *dest, ShapeError v) {
    ShapeError *p = (ShapeError *)arena_alloc(dest, sizeof(ShapeError));
    *p = v;
    return p;
}

static inline IndexError *IndexError_box(Arena *dest, IndexError v) {
    IndexError *p = (IndexError *)arena_alloc(dest, sizeof(IndexError));
    *p = v;
    return p;
}

static inline double *double_box(Arena *dest, double v) {
    double *p = (double *)arena_alloc(dest, sizeof(double));
    *p = v;
    return p;
}

static inline IoError *IoError_box(Arena *dest, IoError v) {
    IoError *p = (IoError *)arena_alloc(dest, sizeof(IoError));
    *p = v;
    return p;
}

static inline FileHandle *FileHandle_box(Arena *dest, FileHandle v) {
    FileHandle *p = (FileHandle *)arena_alloc(dest, sizeof(FileHandle));
    *p = v;
    return p;
}

static inline Option *Option_box(Arena *dest, Option v) {
    Option *p = (Option *)arena_alloc(dest, sizeof(Option));
    *p = v;
    return p;
}

static inline SyntaxError *SyntaxError_box(Arena *dest, SyntaxError v) {
    SyntaxError *p = (SyntaxError *)arena_alloc(dest, sizeof(SyntaxError));
    *p = v;
    return p;
}

static inline PatternAst *PatternAst_box(Arena *dest, PatternAst v) {
    PatternAst *p = (PatternAst *)arena_alloc(dest, sizeof(PatternAst));
    *p = v;
    return p;
}

static inline PatternNode *PatternNode_box(Arena *dest, PatternNode v) {
    PatternNode *p = (PatternNode *)arena_alloc(dest, sizeof(PatternNode));
    *p = v;
    return p;
}

static inline Vec *Vec_box(Arena *dest, Vec v) {
    Vec *p = (Vec *)arena_alloc(dest, sizeof(Vec));
    *p = v;
    return p;
}

static inline ParseStep *ParseStep_box(Arena *dest, ParseStep v) {
    ParseStep *p = (ParseStep *)arena_alloc(dest, sizeof(ParseStep));
    *p = v;
    return p;
}

static inline AnchorKind *AnchorKind_box(Arena *dest, AnchorKind v) {
    AnchorKind *p = (AnchorKind *)arena_alloc(dest, sizeof(AnchorKind));
    *p = v;
    return p;
}

static inline CharRange *CharRange_box(Arena *dest, CharRange v) {
    CharRange *p = (CharRange *)arena_alloc(dest, sizeof(CharRange));
    *p = v;
    return p;
}

static inline Regex *Regex_box(Arena *dest, Regex v) {
    Regex *p = (Regex *)arena_alloc(dest, sizeof(Regex));
    *p = v;
    return p;
}

static inline Match *Match_box(Arena *dest, Match v) {
    Match *p = (Match *)arena_alloc(dest, sizeof(Match));
    *p = v;
    return p;
}

static inline ExprValue *ExprValue_box(Arena *dest, ExprValue v) {
    ExprValue *p = (ExprValue *)arena_alloc(dest, sizeof(ExprValue));
    *p = v;
    return p;
}

static inline EvalError *EvalError_box(Arena *dest, EvalError v) {
    EvalError *p = (EvalError *)arena_alloc(dest, sizeof(EvalError));
    *p = v;
    return p;
}

static inline ExprParseStep *ExprParseStep_box(Arena *dest, ExprParseStep v) {
    ExprParseStep *p = (ExprParseStep *)arena_alloc(dest, sizeof(ExprParseStep));
    *p = v;
    return p;
}

static inline int int_vec_eq(Vec *a, Vec *b) {
    if (vec_len(a) != vec_len(b)) return 0;
    for (int i = 0; i < vec_len(a); i++) {
        if (*(int *)vec_get(a, i) != *(int *)vec_get(b, i)) return 0;
    }
    return 1;
}

static double __lambda_0(double x, double y) {
    return (x + y);
}

static double __lambda_1(double x, double y) {
    return (x * y);
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

int contains_ci_(char * haystack __attribute__((unused)), char * needle __attribute__((unused))) {
    return (strcasestr(haystack, needle) != NULL);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    double i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    double start = 0;
    double i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        double __recur_tmp_0 = start;
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

int product(Vec * shape __attribute__((unused))) {
    double __loop_result_2 __attribute__((unused));
    double i = 0;
    double acc = 1;
    while (1) {
        if ((i >= vec_len(shape))) {
        __loop_result_2 = acc;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (acc * (*((int *)(vec_get(shape, i)))));
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_2;
}

Vec strides_for(Vec * shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = vec_len(shape);
    int total __attribute__((unused)) = product(shape);
    Vec s __attribute__((unused)) = vec_new(dest);
    void * __loop_result_3 __attribute__((unused));
    double i = 0;
    int running = total;
    while (1) {
        if ((i < n)) {
        int next __attribute__((unused)) = (running / (*((int *)(vec_get(shape, i)))));
        (void)(vec_push_(&(s), vec_box_i32(&(s), next)));
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = next;
        i = __recur_tmp_0;
        running = __recur_tmp_1;
        continue;
        } else {
            break;
        }
    }
    return s;
}

NDArray zeros(Vec shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = product(&(shape));
    Vec data __attribute__((unused)) = vec_new(dest);
    void * __loop_result_4 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < n)) {
    (void)(vec_push_(&(data), vec_box_f64(&(data), 0.0)));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return NDArray_new(data, shape, strides_for(&(shape), dest));
}

Result from_vec(Vec data __attribute__((unused)), Vec shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((vec_len(&(data)) == product(&(shape)))) {
    return result_ok(NDArray_box(dest, NDArray_new(data, shape, strides_for(&(shape), dest))));
    } else {
    return result_err(ShapeError_box(dest, ShapeError_new("data length does not match shape product")));
    }
}

int flat_index(NDArray * a __attribute__((unused)), Vec * idx __attribute__((unused))) {
    double __loop_result_5 __attribute__((unused));
    double i = 0;
    double offset = 0;
    while (1) {
        if ((i >= vec_len(idx))) {
        __loop_result_5 = offset;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (offset + ((*((int *)(vec_get(idx, i)))) * (*((int *)(vec_get(&((a)->strides), i))))));
        i = __recur_tmp_0;
        offset = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_5;
}

Result get(NDArray * a __attribute__((unused)), Vec idx __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int off __attribute__((unused)) = flat_index(a, &(idx));
    if (((off < 0) || (off >= vec_len(&((a)->data))))) {
    return result_err(IndexError_box(dest, IndexError_new("out of bounds")));
    } else {
    return result_ok(double_box(dest, (*((double *)(vec_get(&((a)->data), off))))));
    }
}

Result set_(NDArray * a __attribute__((unused)), Vec idx __attribute__((unused)), double v __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int off __attribute__((unused)) = flat_index(a, &(idx));
    if (((off < 0) || (off >= vec_len(&((a)->data))))) {
    return result_err(IndexError_box(dest, IndexError_new("out of bounds")));
    } else {
    (void)(vec_set_at_(&((a)->data), off, vec_box_f64(&((a)->data), v)));
    return result_ok(NULL);
    }
}

Result reshape(NDArray * a __attribute__((unused)), Vec new_shape __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((product(&(new_shape)) == product(&((a)->shape)))) {
    return result_ok(NDArray_box(dest, NDArray_new((a)->data, new_shape, strides_for(&(new_shape), dest))));
    } else {
    return result_err(ShapeError_box(dest, ShapeError_new("reshape must preserve element count")));
    }
}

int same_shape_(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused))) {
    return int_vec_eq(&((a)->shape), &((b)->shape));
}

Result elementwise(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), double (*op)(double, double) __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!(same_shape_(a, b)))) {
    return result_err(ShapeError_box(dest, ShapeError_new("shape mismatch")));
    } else {
    int n __attribute__((unused)) = vec_len(&((a)->data));
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_6 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < n)) {
    (void)(vec_push_(&(out), vec_box_f64(&(out), op((*((double *)(vec_get(&((a)->data), i)))), (*((double *)(vec_get(&((b)->data), i))))))));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return result_ok(NDArray_box(dest, NDArray_new(out, (a)->shape, (a)->strides)));
    }
}

Result add(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return elementwise(a, b, __lambda_0, dest);
}

Result mul_elementwise(NDArray * a __attribute__((unused)), NDArray * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return elementwise(a, b, __lambda_1, dest);
}

int raw_open(char * path __attribute__((unused)), int mode_tag __attribute__((unused))) {
    return (raw_open_impl(path, mode_tag));
}

int raw_close(int fd __attribute__((unused))) {
    return (raw_close_impl(fd));
}

int raw_write(int fd __attribute__((unused)), char * s __attribute__((unused))) {
    return (raw_write_impl(fd, s));
}

char * raw_read_all(int fd __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (raw_read_all_impl(fd, dest));
}

int raw_at_eof_(int fd __attribute__((unused))) {
    return (raw_at_eof_impl(fd));
}

char * raw_read_line(int fd __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return (raw_read_line_impl(fd, dest));
}

int raw_errno(void) {
    return (errno);
}

int mode_tag_of(OpenMode mode __attribute__((unused))) {
    double __match_result_0 __attribute__((unused));
    OpenMode __match_tmp_0 = mode;
    if (__match_tmp_0.tag == 0) {
        __match_result_0 = 0;
    }
    else if (__match_tmp_0.tag == 1) {
        __match_result_0 = 1;
    }
    else if (__match_tmp_0.tag == 2) {
        __match_result_0 = 2;
    }
    return __match_result_0;
}

IoError errno_to_io_error(int e __attribute__((unused))) {
    return ((e == 2) ? IoError_NotFound() : ((e == 13) ? IoError_PermissionDenied() : ((e == 17) ? IoError_AlreadyExists() : IoError_Other())));
}

Result file_open(char * path __attribute__((unused)), OpenMode mode __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int fd __attribute__((unused)) = raw_open(path, mode_tag_of(mode));
    if ((fd < 0)) {
    return result_err(IoError_box(dest, errno_to_io_error(raw_errno())));
    } else {
    return result_ok(FileHandle_box(dest, FileHandle_new(fd)));
    }
}

Result file_close(FileHandle f __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((raw_close((f).fd) < 0)) {
    return result_err(IoError_box(dest, errno_to_io_error(raw_errno())));
    } else {
    return result_ok(NULL);
    }
}

int path_exists_(char * path __attribute__((unused))) {
    return (file_exists_impl(path) != 0);
}

Result write_string(FileHandle f __attribute__((unused)), char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((raw_write((f).fd, s) < 0)) {
    return result_err(IoError_box(dest, errno_to_io_error(raw_errno())));
    } else {
    return result_ok(NULL);
    }
}

Result read_string(FileHandle f __attribute__((unused)), Arena *buf __attribute__((unused))) {
    return result_ok(raw_read_all((f).fd, buf));
}

Result read_line(FileHandle f __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (raw_at_eof_((f).fd)) {
    return result_ok(Option_box(dest, option_none()));
    } else {
    return result_ok(Option_box(dest, option_some(raw_read_line((f).fd, dest))));
    }
}

double raw_read_f64(int fd __attribute__((unused))) {
    return (raw_read_f64_impl(fd));
}

Result read_floats(FileHandle f __attribute__((unused)), int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec data __attribute__((unused)) = vec_new(dest);
    void * __loop_result_7 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < n)) {
        (void)(vec_push_(&(data), vec_box_f64(&(data), raw_read_f64((f).fd))));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    Vec shape __attribute__((unused)) = vec_new(dest);
    Vec strides __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(shape), vec_box_i32(&(shape), n)));
    (void)(vec_push_(&(strides), vec_box_f64(&(strides), 1)));
    return result_ok(NDArray_box(dest, NDArray_new(data, shape, strides)));
}

Result parse(char * pattern __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int plen __attribute__((unused)) = length(pattern);
    Result __match_result_1 __attribute__((unused));
    Result __match_tmp_1 = parse_alt(pattern, 0, 0, dest);
    if (__match_tmp_1.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_1.value;
        __match_result_1 = result_err(e);
    }
    else if (__match_tmp_1.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_1.value;
        if ((((*((ParseStep *)(step)))).next < plen)) {
        __match_result_1 = result_err(SyntaxError_box(dest, SyntaxError_new("unexpected ')'", ((*((ParseStep *)(step)))).next)));
        } else {
        __match_result_1 = result_ok(PatternAst_box(dest, PatternAst_new(((*((ParseStep *)(step)))).node, ((*((ParseStep *)(step)))).ncap)));
        }
    }
    return __match_result_1;
}

Result parse_alt(char * pattern __attribute__((unused)), int pos __attribute__((unused)), int ncap __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __match_result_2 __attribute__((unused));
    Result __match_tmp_2 = parse_concat(pattern, pos, ncap, dest);
    if (__match_tmp_2.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_2.value;
        __match_result_2 = result_err(e);
    }
    else if (__match_tmp_2.tag == 1) {
        void *first __attribute__((unused)) = __match_tmp_2.value;
        int plen __attribute__((unused)) = length(pattern);
        Vec branches __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(branches), PatternNode_box(dest, ((*((ParseStep *)(first)))).node)));
    int p = ((*((ParseStep *)(first)))).next;
    int nc = ((*((ParseStep *)(first)))).ncap;
    while (1) {
        if (((p < plen) && (char_at(pattern, p) == 124))) {
    Result __match_tmp_3 = parse_concat(pattern, (p + 1), nc, dest);
    if (__match_tmp_3.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_3.value;
        __match_result_2 = result_err(e);
        break;
    }
    else if (__match_tmp_3.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_3.value;
    (void)(vec_push_(&(branches), PatternNode_box(dest, ((*((ParseStep *)(step)))).node)));
        int __recur_tmp_0 = ((*((ParseStep *)(step)))).next;
        int __recur_tmp_1 = ((*((ParseStep *)(step)))).ncap;
        p = __recur_tmp_0;
        nc = __recur_tmp_1;
        continue;
    }
        } else {
        __match_result_2 = result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_Alt(Vec_box(dest, branches)), p, nc)));
        break;
        }
    }
    }
    return __match_result_2;
}

Result parse_concat(char * pattern __attribute__((unused)), int pos __attribute__((unused)), int ncap __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int plen __attribute__((unused)) = length(pattern);
    Vec parts __attribute__((unused)) = vec_new(dest);
    Result __loop_result_8 __attribute__((unused));
    int p = pos;
    int nc = ncap;
    while (1) {
        if ((((p >= plen) || (char_at(pattern, p) == 124)) || (char_at(pattern, p) == 41))) {
        __loop_result_8 = result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_Concat(Vec_box(dest, parts)), p, nc)));
        break;
        } else {
    Result __match_tmp_4 = parse_quant(pattern, p, nc, dest);
    if (__match_tmp_4.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_4.value;
        __loop_result_8 = result_err(e);
        break;
    }
    else if (__match_tmp_4.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_4.value;
    (void)(vec_push_(&(parts), PatternNode_box(dest, ((*((ParseStep *)(step)))).node)));
        int __recur_tmp_0 = ((*((ParseStep *)(step)))).next;
        int __recur_tmp_1 = ((*((ParseStep *)(step)))).ncap;
        p = __recur_tmp_0;
        nc = __recur_tmp_1;
        continue;
    }
        }
    }
    return __loop_result_8;
}

Result parse_quant(char * pattern __attribute__((unused)), int pos __attribute__((unused)), int ncap __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __match_result_3 __attribute__((unused));
    Result __match_tmp_5 = parse_atom(pattern, pos, ncap, dest);
    if (__match_tmp_5.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_5.value;
        __match_result_3 = result_err(e);
    }
    else if (__match_tmp_5.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_5.value;
        int plen __attribute__((unused)) = length(pattern);
        int p __attribute__((unused)) = ((*((ParseStep *)(step)))).next;
        if ((p >= plen)) {
        __match_result_3 = result_ok(ParseStep_box(dest, (*((ParseStep *)(step)))));
        } else {
        __match_result_3 = ((char_at(pattern, p) == 42) ? result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_Star(dest, ((*((ParseStep *)(step)))).node, 1), (p + 1), ((*((ParseStep *)(step)))).ncap))) : ((char_at(pattern, p) == 43) ? result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_Plus(dest, ((*((ParseStep *)(step)))).node, 1), (p + 1), ((*((ParseStep *)(step)))).ncap))) : ((char_at(pattern, p) == 63) ? result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_Optional(dest, ((*((ParseStep *)(step)))).node, 1), (p + 1), ((*((ParseStep *)(step)))).ncap))) : result_ok(ParseStep_box(dest, (*((ParseStep *)(step))))))));
        }
    }
    return __match_result_3;
}

Result parse_atom(char * pattern __attribute__((unused)), int pos __attribute__((unused)), int ncap __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int plen __attribute__((unused)) = length(pattern);
    if ((pos >= plen)) {
    return result_err(SyntaxError_box(dest, SyntaxError_new("unexpected end of pattern", pos)));
    } else {
    int c __attribute__((unused)) = char_at(pattern, pos);
    return ((c == 40) ? parse_group(pattern, pos, ncap, dest) : ((c == 91) ? parse_class(pattern, pos, ncap, dest) : ((c == 92) ? parse_escape(pattern, pos, ncap, dest) : ((c == 46) ? result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_AnyChar(), (pos + 1), ncap))) : ((c == 94) ? result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_Anchor(AnchorKind_box(dest, AnchorKind_Start())), (pos + 1), ncap))) : ((c == 36) ? result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_Anchor(AnchorKind_box(dest, AnchorKind_End())), (pos + 1), ncap))) : (((c == 42) || ((c == 43) || (c == 63))) ? result_err(SyntaxError_box(dest, SyntaxError_new("quantifier with nothing to repeat", pos))) : ((c == 124) ? result_err(SyntaxError_box(dest, SyntaxError_new("unexpected '|'", pos))) : ((c == 41) ? result_err(SyntaxError_box(dest, SyntaxError_new("unexpected ')'", pos))) : result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_Literal(substring(pattern, pos, (pos + 1), dest)), (pos + 1), ncap))))))))))));
    }
}

Result parse_escape(char * pattern __attribute__((unused)), int pos __attribute__((unused)), int ncap __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (((pos + 1) >= length(pattern))) {
    return result_err(SyntaxError_box(dest, SyntaxError_new("trailing backslash", pos)));
    } else {
    return result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_Literal(substring(pattern, (pos + 1), (pos + 2), dest)), (pos + 2), ncap)));
    }
}

Result parse_group(char * pattern __attribute__((unused)), int pos __attribute__((unused)), int ncap __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int my_index __attribute__((unused)) = (ncap + 1);
    Result __match_result_4 __attribute__((unused));
    Result __match_tmp_6 = parse_alt(pattern, (pos + 1), my_index, dest);
    if (__match_tmp_6.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_6.value;
        __match_result_4 = result_err(e);
    }
    else if (__match_tmp_6.tag == 1) {
        void *inner __attribute__((unused)) = __match_tmp_6.value;
        int plen __attribute__((unused)) = length(pattern);
        int p __attribute__((unused)) = ((*((ParseStep *)(inner)))).next;
        if (((p >= plen) || (!((char_at(pattern, p) == 41))))) {
        __match_result_4 = result_err(SyntaxError_box(dest, SyntaxError_new("expected ')'", p)));
        } else {
        __match_result_4 = result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_Group(dest, ((*((ParseStep *)(inner)))).node, option_some(int_box(dest, my_index)), option_none()), (p + 1), ((*((ParseStep *)(inner)))).ncap)));
        }
    }
    return __match_result_4;
}

int find_class_close(char * pattern __attribute__((unused)), int from __attribute__((unused)), int plen __attribute__((unused))) {
    double __loop_result_9 __attribute__((unused));
    int j = from;
    while (1) {
        if ((j >= plen)) {
        __loop_result_9 = -1;
        break;
        } else {
        if ((char_at(pattern, j) == 93)) {
        __loop_result_9 = j;
        break;
        } else {
        int __recur_tmp_0 = (j + 1);
        j = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_9;
}

Result parse_class(char * pattern __attribute__((unused)), int pos __attribute__((unused)), int ncap __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int plen __attribute__((unused)) = length(pattern);
    int negate __attribute__((unused)) = (((pos + 1) < plen) && (char_at(pattern, (pos + 1)) == 94));
    int start __attribute__((unused)) = (negate ? (pos + 2) : (pos + 1));
    int close __attribute__((unused)) = find_class_close(pattern, start, plen);
    if ((close < 0)) {
    return result_err(SyntaxError_box(dest, SyntaxError_new("unterminated character class", pos)));
    } else {
    Vec ranges __attribute__((unused)) = vec_new(dest);
    void * __loop_result_10 __attribute__((unused));
    int j = start;
    while (1) {
        if ((j < close)) {
        if ((((j + 2) < close) && (char_at(pattern, (j + 1)) == 45))) {
        (void)(vec_push_(&(ranges), CharRange_box(dest, CharRange_new(substring(pattern, j, (j + 1), dest), substring(pattern, (j + 2), (j + 3), dest)))));
        int __recur_tmp_0 = (j + 3);
        j = __recur_tmp_0;
        continue;
        } else {
        (void)(vec_push_(&(ranges), CharRange_box(dest, CharRange_new(substring(pattern, j, (j + 1), dest), substring(pattern, j, (j + 1), dest)))));
        int __recur_tmp_0 = (j + 1);
        j = __recur_tmp_0;
        continue;
        }
        } else {
            break;
        }
    }
    return result_ok(ParseStep_box(dest, ParseStep_new(PatternNode_CharClass(dest, ranges, negate), (close + 1), ncap)));
    }
}

Result compile(char * pattern __attribute__((unused)), MatchBudget budget __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __match_result_5 __attribute__((unused));
    Result __match_tmp_7 = parse(pattern, dest);
    if (__match_tmp_7.tag == 1) {
        void *ast __attribute__((unused)) = __match_tmp_7.value;
        __match_result_5 = result_ok(Regex_box(dest, Regex_new((*((PatternAst *)(ast))), budget)));
    }
    else if (__match_tmp_7.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_7.value;
        __match_result_5 = result_err(e);
    }
    return __match_result_5;
}

AnchorKind unbox_anchor_kind(void * k __attribute__((unused))) {
    return (*(AnchorKind *)k);
}

int anchor_kind_supported_(AnchorKind kind __attribute__((unused))) {
    int __match_result_6 __attribute__((unused));
    AnchorKind __match_tmp_8 = kind;
    if (__match_tmp_8.tag == 0) {
        __match_result_6 = 1;
    }
    else if (__match_tmp_8.tag == 1) {
        __match_result_6 = 1;
    }
    else if (__match_tmp_8.tag == 2) {
        __match_result_6 = 0;
    }
    return __match_result_6;
}

int node_supported_(PatternNode * node __attribute__((unused))) {
    int __match_result_7 __attribute__((unused));
    PatternNode __match_tmp_9 = (*((PatternNode *)(node)));
    if (__match_tmp_9.tag == 0) {
        void *ch __attribute__((unused)) = __match_tmp_9.value;
        __match_result_7 = 1;
    }
    else if (__match_tmp_9.tag == 1) {
        __match_result_7 = 1;
    }
    else if (__match_tmp_9.tag == 8) {
        PatternNode_CharClass_Payload *__match_payload_9 = (PatternNode_CharClass_Payload *)(__match_tmp_9.value);
        Vec ranges __attribute__((unused)) = __match_payload_9->ranges;
        int negated __attribute__((unused)) = __match_payload_9->negated;
        __match_result_7 = 1;
    }
    else if (__match_tmp_9.tag == 9) {
        void *kind __attribute__((unused)) = __match_tmp_9.value;
        __match_result_7 = anchor_kind_supported_(unbox_anchor_kind(kind));
    }
    else if (__match_tmp_9.tag == 2) {
        void *parts __attribute__((unused)) = __match_tmp_9.value;
        __match_result_7 = all_nodes_supported_(parts, 0);
    }
    else if (__match_tmp_9.tag == 3) {
        void *branches __attribute__((unused)) = __match_tmp_9.value;
        __match_result_7 = all_nodes_supported_(branches, 0);
    }
    else if (__match_tmp_9.tag == 4) {
        PatternNode_Star_Payload *__match_payload_9 = (PatternNode_Star_Payload *)(__match_tmp_9.value);
        PatternNode inner __attribute__((unused)) = __match_payload_9->inner;
        int greedy __attribute__((unused)) = __match_payload_9->greedy;
        __match_result_7 = node_supported_(&(inner));
    }
    else if (__match_tmp_9.tag == 5) {
        PatternNode_Plus_Payload *__match_payload_9 = (PatternNode_Plus_Payload *)(__match_tmp_9.value);
        PatternNode inner __attribute__((unused)) = __match_payload_9->inner;
        int greedy __attribute__((unused)) = __match_payload_9->greedy;
        __match_result_7 = node_supported_(&(inner));
    }
    else if (__match_tmp_9.tag == 6) {
        PatternNode_Optional_Payload *__match_payload_9 = (PatternNode_Optional_Payload *)(__match_tmp_9.value);
        PatternNode inner __attribute__((unused)) = __match_payload_9->inner;
        int greedy __attribute__((unused)) = __match_payload_9->greedy;
        __match_result_7 = node_supported_(&(inner));
    }
    else if (__match_tmp_9.tag == 7) {
        PatternNode_Group_Payload *__match_payload_9 = (PatternNode_Group_Payload *)(__match_tmp_9.value);
        PatternNode inner __attribute__((unused)) = __match_payload_9->inner;
        Option _capture __attribute__((unused)) = __match_payload_9->capture_index;
        Option _name __attribute__((unused)) = __match_payload_9->name;
        __match_result_7 = node_supported_(&(inner));
    }
    else if (1) {
        __match_result_7 = 0;
    }
    return __match_result_7;
}

int all_nodes_supported_(Vec * parts __attribute__((unused)), int i __attribute__((unused))) {
    if ((i >= vec_len(parts))) {
    return 1;
    } else {
    if (node_supported_(vec_get(parts, i))) {
    return all_nodes_supported_(parts, (i + 1));
    } else {
    return 0;
    }
    }
}

int pattern_supported_(Regex * re __attribute__((unused))) {
    return node_supported_(&(((re)->ast).root));
}

int char_matches_(char * text __attribute__((unused)), int pos __attribute__((unused)), char * ch __attribute__((unused))) {
    return ((pos < length(text)) && (char_at(text, pos) == char_at(ch, 0)));
}

Option ast_literal_text(PatternNode * node __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Option __match_result_8 __attribute__((unused));
    PatternNode __match_tmp_10 = (*((PatternNode *)(node)));
    if (__match_tmp_10.tag == 0) {
        void *ch __attribute__((unused)) = __match_tmp_10.value;
        __match_result_8 = option_some(ch);
    }
    else if (__match_tmp_10.tag == 2) {
        void *parts __attribute__((unused)) = __match_tmp_10.value;
        __match_result_8 = concat_literal_parts(parts, 0, "", dest);
    }
    else if (__match_tmp_10.tag == 3) {
        void *branches __attribute__((unused)) = __match_tmp_10.value;
        __match_result_8 = single_branch_literal(branches, dest);
    }
    else if (1) {
        __match_result_8 = option_none();
    }
    return __match_result_8;
}

Option single_branch_literal(Vec * branches __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((vec_len(branches) == 1)) {
    return ast_literal_text(vec_get(branches, 0), dest);
    } else {
    return option_none();
    }
}

Option concat_literal_parts(Vec * parts __attribute__((unused)), int i __attribute__((unused)), char * acc __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((i >= vec_len(parts))) {
    return option_some(acc);
    } else {
    Option __match_result_9 __attribute__((unused));
    Option __match_tmp_11 = ast_literal_text(vec_get(parts, i), dest);
    if (__match_tmp_11.tag == 1) {
        void *s __attribute__((unused)) = __match_tmp_11.value;
        __match_result_9 = concat_literal_parts(parts, (i + 1), concat(acc, s, dest), dest);
    }
    else if (__match_tmp_11.tag == 0) {
        __match_result_9 = option_none();
    }
    return __match_result_9;
    }
}

Option alt_literal_scan(Vec * branches __attribute__((unused)), int i __attribute__((unused)), char * text __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((i >= vec_len(branches))) {
    return option_some(int_box(dest, 0));
    } else {
    Option __match_result_10 __attribute__((unused));
    Option __match_tmp_12 = ast_literal_text(vec_get(branches, i), dest);
    if (__match_tmp_12.tag == 1) {
        void *needle __attribute__((unused)) = __match_tmp_12.value;
        if (string_contains_(text, needle)) {
        __match_result_10 = option_some(int_box(dest, 1));
        } else {
        __match_result_10 = alt_literal_scan(branches, (i + 1), text, dest);
        }
    }
    else if (__match_tmp_12.tag == 0) {
        __match_result_10 = option_none();
    }
    return __match_result_10;
    }
}

Option alt_literal_scan_root(PatternNode * node __attribute__((unused)), char * text __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Option __match_result_11 __attribute__((unused));
    PatternNode __match_tmp_13 = (*((PatternNode *)(node)));
    if (__match_tmp_13.tag == 3) {
        void *branches __attribute__((unused)) = __match_tmp_13.value;
        if ((vec_len(branches) > 1)) {
        __match_result_11 = alt_literal_scan(branches, 0, text, dest);
        } else {
        __match_result_11 = option_none();
        }
    }
    else if (1) {
        __match_result_11 = option_none();
    }
    return __match_result_11;
}

int literal_matches_at_(char * text __attribute__((unused)), int start __attribute__((unused)), char * needle __attribute__((unused)), int nlen __attribute__((unused))) {
    int __loop_result_11 __attribute__((unused));
    double j = 0;
    while (1) {
        if ((j >= nlen)) {
        __loop_result_11 = 1;
        break;
        } else {
        if ((char_at(text, (start + j)) == char_at(needle, j))) {
        double __recur_tmp_0 = (j + 1);
        j = __recur_tmp_0;
        continue;
        } else {
        __loop_result_11 = 0;
        break;
        }
        }
    }
    return __loop_result_11;
}

int string_contains_(char * text __attribute__((unused)), char * needle __attribute__((unused))) {
    int tlen __attribute__((unused)) = length(text);
    int nlen __attribute__((unused)) = length(needle);
    if ((nlen > tlen)) {
    return 0;
    } else {
    int __loop_result_12 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i > (tlen - nlen))) {
        __loop_result_12 = 0;
        break;
        } else {
        if (literal_matches_at_(text, i, needle, nlen)) {
        __loop_result_12 = 1;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_12;
    }
}

int zero_i32(void) {
    return (0);
}

int vec_i32_at(Vec * v __attribute__((unused)), int idx __attribute__((unused))) {
    return (*(int *)vec_get(v, idx));
}

Vec single_or_empty(int matched __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec out __attribute__((unused)) = vec_new(dest);
    if (matched) {
        (void)(vec_push_(&(out), vec_box_i32(&(out), pos)));
    }
    return out;
}

Vec vec_reversed(Vec * src __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_13 __attribute__((unused));
    int i = (vec_len(src) - 1);
    while (1) {
        if ((i >= 0)) {
        (void)(vec_push_(&(out), vec_box_i32(&(out), vec_i32_at(src, i))));
        int __recur_tmp_0 = (i - 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return out;
}

CharRange vec_charrange_at(Vec * v __attribute__((unused)), int idx __attribute__((unused))) {
    return (*(CharRange *)vec_get(v, idx));
}

int char_in_range_(int c __attribute__((unused)), CharRange r __attribute__((unused))) {
    return ((c >= char_at((r).lo, 0)) && (c <= char_at((r).hi, 0)));
}

int char_in_any_range_(int c __attribute__((unused)), Vec * ranges __attribute__((unused)), int i __attribute__((unused))) {
    if ((i >= vec_len(ranges))) {
    return 0;
    } else {
    if (char_in_range_(c, vec_charrange_at(ranges, i))) {
    return 1;
    } else {
    return char_in_any_range_(c, ranges, (i + 1));
    }
    }
}

int char_class_matches_(char * text __attribute__((unused)), int pos __attribute__((unused)), Vec * ranges __attribute__((unused)), int negated __attribute__((unused))) {
    if ((pos >= length(text))) {
    return 0;
    } else {
    int c __attribute__((unused)) = char_at(text, pos);
    int in_class __attribute__((unused)) = char_in_any_range_(c, ranges, 0);
    if (negated) {
    if (in_class) {
    return 0;
    } else {
    return 1;
    }
    } else {
    return in_class;
    }
    }
}

int anchor_matches_(char * text __attribute__((unused)), int pos __attribute__((unused)), AnchorKind kind __attribute__((unused))) {
    int __match_result_12 __attribute__((unused));
    AnchorKind __match_tmp_14 = kind;
    if (__match_tmp_14.tag == 0) {
        __match_result_12 = (pos == 0);
    }
    else if (__match_tmp_14.tag == 1) {
        __match_result_12 = (pos == length(text));
    }
    else if (__match_tmp_14.tag == 2) {
        __match_result_12 = 0;
    }
    return __match_result_12;
}

Vec match_node(PatternNode * node __attribute__((unused)), char * text __attribute__((unused)), int pos __attribute__((unused)), int * steps __attribute__((unused)), int budget __attribute__((unused)), Arena *dest __attribute__((unused))) {
    (void)((*(steps) = ((*((int *)(steps))) + 1)));
    if (((*((int *)(steps))) > budget)) {
    return vec_new(dest);
    } else {
    Vec __match_result_13 __attribute__((unused));
    PatternNode __match_tmp_15 = (*((PatternNode *)(node)));
    if (__match_tmp_15.tag == 0) {
        void *ch __attribute__((unused)) = __match_tmp_15.value;
        __match_result_13 = single_or_empty(char_matches_(text, pos, ch), (pos + 1), dest);
    }
    else if (__match_tmp_15.tag == 1) {
        __match_result_13 = single_or_empty((pos < length(text)), (pos + 1), dest);
    }
    else if (__match_tmp_15.tag == 2) {
        void *parts __attribute__((unused)) = __match_tmp_15.value;
        __match_result_13 = match_concat(parts, 0, text, pos, steps, budget, dest);
    }
    else if (__match_tmp_15.tag == 3) {
        void *branches __attribute__((unused)) = __match_tmp_15.value;
        __match_result_13 = match_alt(branches, 0, text, pos, steps, budget, dest);
    }
    else if (__match_tmp_15.tag == 4) {
        PatternNode_Star_Payload *__match_payload_15 = (PatternNode_Star_Payload *)(__match_tmp_15.value);
        PatternNode inner __attribute__((unused)) = __match_payload_15->inner;
        int greedy __attribute__((unused)) = __match_payload_15->greedy;
        __match_result_13 = match_star(&(inner), greedy, text, pos, steps, budget, dest);
    }
    else if (__match_tmp_15.tag == 7) {
        PatternNode_Group_Payload *__match_payload_15 = (PatternNode_Group_Payload *)(__match_tmp_15.value);
        PatternNode inner __attribute__((unused)) = __match_payload_15->inner;
        Option _capture __attribute__((unused)) = __match_payload_15->capture_index;
        Option _name __attribute__((unused)) = __match_payload_15->name;
        __match_result_13 = match_node(&(inner), text, pos, steps, budget, dest);
    }
    else if (__match_tmp_15.tag == 8) {
        PatternNode_CharClass_Payload *__match_payload_15 = (PatternNode_CharClass_Payload *)(__match_tmp_15.value);
        Vec ranges __attribute__((unused)) = __match_payload_15->ranges;
        int negated __attribute__((unused)) = __match_payload_15->negated;
        __match_result_13 = single_or_empty(char_class_matches_(text, pos, &(ranges), negated), (pos + 1), dest);
    }
    else if (__match_tmp_15.tag == 9) {
        void *kind __attribute__((unused)) = __match_tmp_15.value;
        __match_result_13 = single_or_empty(anchor_matches_(text, pos, unbox_anchor_kind(kind)), pos, dest);
    }
    else if (__match_tmp_15.tag == 5) {
        PatternNode_Plus_Payload *__match_payload_15 = (PatternNode_Plus_Payload *)(__match_tmp_15.value);
        PatternNode inner __attribute__((unused)) = __match_payload_15->inner;
        int greedy __attribute__((unused)) = __match_payload_15->greedy;
        __match_result_13 = match_plus(&(inner), greedy, text, pos, steps, budget, dest);
    }
    else if (__match_tmp_15.tag == 6) {
        PatternNode_Optional_Payload *__match_payload_15 = (PatternNode_Optional_Payload *)(__match_tmp_15.value);
        PatternNode inner __attribute__((unused)) = __match_payload_15->inner;
        int greedy __attribute__((unused)) = __match_payload_15->greedy;
        __match_result_13 = match_optional(&(inner), greedy, text, pos, steps, budget, dest);
    }
    else if (1) {
        __match_result_13 = vec_new(dest);
    }
    return __match_result_13;
    }
}

Vec match_concat(Vec * parts __attribute__((unused)), int i __attribute__((unused)), char * text __attribute__((unused)), int pos __attribute__((unused)), int * steps __attribute__((unused)), int budget __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((i >= vec_len(parts))) {
    return single_or_empty(1, pos, dest);
    } else {
    Vec candidates __attribute__((unused)) = match_node(vec_get(parts, i), text, pos, steps, budget, dest);
    Vec __loop_result_14 __attribute__((unused));
    double ci = 0;
    while (1) {
        if ((ci >= vec_len(&(candidates)))) {
        __loop_result_14 = vec_new(dest);
        break;
        } else {
        Vec rest __attribute__((unused)) = match_concat(parts, (i + 1), text, vec_i32_at(&(candidates), ci), steps, budget, dest);
        if ((vec_len(&(rest)) > 0)) {
        __loop_result_14 = rest;
        break;
        } else {
        double __recur_tmp_0 = (ci + 1);
        ci = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_14;
    }
}

Vec match_alt(Vec * branches __attribute__((unused)), int i __attribute__((unused)), char * text __attribute__((unused)), int pos __attribute__((unused)), int * steps __attribute__((unused)), int budget __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((i >= vec_len(branches))) {
    return vec_new(dest);
    } else {
    Vec own __attribute__((unused)) = match_node(vec_get(branches, i), text, pos, steps, budget, dest);
    if ((vec_len(&(own)) > 0)) {
    return own;
    } else {
    return match_alt(branches, (i + 1), text, pos, steps, budget, dest);
    }
    }
}

Vec match_star(PatternNode * inner __attribute__((unused)), int greedy __attribute__((unused)), char * text __attribute__((unused)), int pos __attribute__((unused)), int * steps __attribute__((unused)), int budget __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec ascending __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(ascending), vec_box_i32(&(ascending), pos)));
    void * __loop_result_15 __attribute__((unused));
    int cur = pos;
    while (1) {
        Vec inner_candidates __attribute__((unused)) = match_node(inner, text, cur, steps, budget, dest);
        if ((vec_len(&(inner_candidates)) > 0)) {
        int next_pos __attribute__((unused)) = vec_i32_at(&(inner_candidates), 0);
        if ((next_pos > cur)) {
        (void)(vec_push_(&(ascending), vec_box_i32(&(ascending), next_pos)));
        int __recur_tmp_0 = next_pos;
        cur = __recur_tmp_0;
        continue;
        } else {
            break;
        }
        } else {
            break;
        }
    }
    if (greedy) {
    return vec_reversed(&(ascending), dest);
    } else {
    return ascending;
    }
}

Vec match_plus(PatternNode * inner __attribute__((unused)), int greedy __attribute__((unused)), char * text __attribute__((unused)), int pos __attribute__((unused)), int * steps __attribute__((unused)), int budget __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec first_candidates __attribute__((unused)) = match_node(inner, text, pos, steps, budget, dest);
    if ((vec_len(&(first_candidates)) == 0)) {
    return vec_new(dest);
    } else {
    int first_pos __attribute__((unused)) = vec_i32_at(&(first_candidates), 0);
    Vec ascending __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(ascending), vec_box_i32(&(ascending), first_pos)));
    void * __loop_result_16 __attribute__((unused));
    int cur = first_pos;
    while (1) {
        Vec inner_candidates __attribute__((unused)) = match_node(inner, text, cur, steps, budget, dest);
        if ((vec_len(&(inner_candidates)) > 0)) {
        int next_pos __attribute__((unused)) = vec_i32_at(&(inner_candidates), 0);
        if ((next_pos > cur)) {
        (void)(vec_push_(&(ascending), vec_box_i32(&(ascending), next_pos)));
        int __recur_tmp_0 = next_pos;
        cur = __recur_tmp_0;
        continue;
        } else {
            break;
        }
        } else {
            break;
        }
    }
    if (greedy) {
    return vec_reversed(&(ascending), dest);
    } else {
    return ascending;
    }
    }
}

Vec match_optional(PatternNode * inner __attribute__((unused)), int greedy __attribute__((unused)), char * text __attribute__((unused)), int pos __attribute__((unused)), int * steps __attribute__((unused)), int budget __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec inner_candidates __attribute__((unused)) = match_node(inner, text, pos, steps, budget, dest);
    if ((vec_len(&(inner_candidates)) == 0)) {
    return single_or_empty(1, pos, dest);
    } else {
    int one_pos __attribute__((unused)) = vec_i32_at(&(inner_candidates), 0);
    Vec both __attribute__((unused)) = vec_new(dest);
    (void)((greedy ? vec_push_(&(both), vec_box_i32(&(both), one_pos)) : vec_push_(&(both), vec_box_i32(&(both), pos))));
    (void)((greedy ? vec_push_(&(both), vec_box_i32(&(both), pos)) : vec_push_(&(both), vec_box_i32(&(both), one_pos))));
    return both;
    }
}

Result is_match(Regex * re __attribute__((unused)), char * text __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __match_result_14 __attribute__((unused));
    Option __match_tmp_16 = ast_literal_text(&(((re)->ast).root), dest);
    if (__match_tmp_16.tag == 1) {
        void *needle __attribute__((unused)) = __match_tmp_16.value;
        __match_result_14 = result_ok(int_box(dest, string_contains_(text, needle)));
    }
    else if (__match_tmp_16.tag == 0) {
    Option __match_tmp_17 = alt_literal_scan_root(&(((re)->ast).root), text, dest);
    if (__match_tmp_17.tag == 1) {
        void *result __attribute__((unused)) = __match_tmp_17.value;
        __match_result_14 = result_ok(result);
    }
    else if (__match_tmp_17.tag == 0) {
        int steps __attribute__((unused)) = zero_i32();
    double start = 0;
    while (1) {
        if ((start > length(text))) {
        __match_result_14 = result_ok(int_box(dest, 0));
        break;
        } else {
        Vec candidates __attribute__((unused)) = match_node(&(((re)->ast).root), text, start, &(steps), ((re)->budget).max_steps, dest);
        if ((vec_len(&(candidates)) > 0)) {
        __match_result_14 = result_ok(int_box(dest, 1));
        break;
        } else {
        double __recur_tmp_0 = (start + 1);
        start = __recur_tmp_0;
        continue;
        }
        }
    }
    }
    }
    return __match_result_14;
}

Result find(Regex * re __attribute__((unused)), char * text __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int steps __attribute__((unused)) = zero_i32();
    Result __loop_result_17 __attribute__((unused));
    double start = 0;
    while (1) {
        if ((start > length(text))) {
        __loop_result_17 = result_ok(Option_box(dest, option_none()));
        break;
        } else {
        Vec candidates __attribute__((unused)) = match_node(&(((re)->ast).root), text, start, &(steps), ((re)->budget).max_steps, dest);
        if ((vec_len(&(candidates)) > 0)) {
        __loop_result_17 = result_ok(Option_box(dest, option_some(Match_box(dest, Match_new(start, vec_i32_at(&(candidates), 0), vec_new(dest))))));
        break;
        } else {
        double __recur_tmp_0 = (start + 1);
        start = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_17;
}

int match_end_i32(Match * m __attribute__((unused))) {
    return (((Match *)m)->end);
}

int match_start_i32(Match * m __attribute__((unused))) {
    return (((Match *)m)->start);
}

Match offset_match(Match * m __attribute__((unused)), int offset __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return Match_new((match_start_i32(m) + offset), (match_end_i32(m) + offset), vec_new(dest));
}

Result find_all(Regex * re __attribute__((unused)), char * text __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec results __attribute__((unused)) = vec_new(dest);
    void * __loop_result_18 __attribute__((unused));
    double start = 0;
    while (1) {
        if ((start <= length(text))) {
    Result __match_tmp_18 = find(re, substring(text, start, length(text), dest), dest);
    if (__match_tmp_18.tag == 1) {
        void *opt __attribute__((unused)) = __match_tmp_18.value;
    Option __match_tmp_19 = (*((Option *)(opt)));
    if (__match_tmp_19.tag == 1) {
        void *m __attribute__((unused)) = __match_tmp_19.value;
        Match absolute __attribute__((unused)) = offset_match(m, start, dest);
        int mend __attribute__((unused)) = match_end_i32(&(absolute));
        int mstart __attribute__((unused)) = match_start_i32(&(absolute));
    (void)(vec_push_(&(results), Match_box(dest, absolute)));
        double __recur_tmp_0 = (mend + ((mend == mstart) ? 1 : 0));
        start = __recur_tmp_0;
        continue;
    }
    else if (__match_tmp_19.tag == 0) {
        __loop_result_18 = NULL;
        break;
    }
    }
    else if (__match_tmp_18.tag == 0) {
        void *_ __attribute__((unused)) = __match_tmp_18.value;
        __loop_result_18 = NULL;
        break;
    }
        } else {
            break;
        }
    }
    return result_ok(Vec_box(dest, results));
}

char * vec_string_at(Vec * v __attribute__((unused)), int idx __attribute__((unused))) {
    return (*(char **)vec_get(v, idx));
}

char * join_strings(Vec * parts __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char * __loop_result_19 __attribute__((unused));
    double i = 0;
    char * acc = "";
    while (1) {
        if ((i >= vec_len(parts))) {
        __loop_result_19 = acc;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        char * __recur_tmp_1 = concat(acc, vec_string_at(parts, i), dest);
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_19;
}

int vec_match_start_at(void * v __attribute__((unused)), int idx __attribute__((unused))) {
    return (((Match *)vec_get((Vec *)v, idx))->start);
}

int vec_match_end_at(void * v __attribute__((unused)), int idx __attribute__((unused))) {
    return (((Match *)vec_get((Vec *)v, idx))->end);
}

char * replace(Regex * re __attribute__((unused)), char * text __attribute__((unused)), char * replacement __attribute__((unused)), int global_ __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char * __match_result_15 __attribute__((unused));
    Result __match_tmp_20 = find_all(re, text, dest);
    if (__match_tmp_20.tag == 1) {
        void *matches __attribute__((unused)) = __match_tmp_20.value;
        int total __attribute__((unused)) = vec_len(matches);
        int n __attribute__((unused)) = (global_ ? total : ((total > 0) ? 1 : 0));
        if ((n == 0)) {
        __match_result_15 = text;
        } else {
    double i = 0;
    double pos = 0;
    char * acc = "";
    while (1) {
        if ((i >= n)) {
        __match_result_15 = concat(acc, substring(text, pos, length(text), dest), dest);
        break;
        } else {
        int mstart __attribute__((unused)) = vec_match_start_at(matches, i);
        int mend __attribute__((unused)) = vec_match_end_at(matches, i);
        char *before __attribute__((unused)) = substring(text, pos, mstart, dest);
        char *spliced __attribute__((unused)) = concat(concat(acc, before, dest), replacement, dest);
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = mend;
        char * __recur_tmp_2 = spliced;
        i = __recur_tmp_0;
        pos = __recur_tmp_1;
        acc = __recur_tmp_2;
        continue;
        }
    }
        }
    }
    else if (__match_tmp_20.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_20.value;
        __match_result_15 = text;
    }
    return __match_result_15;
}

Bindings bindings_new(Arena *dest __attribute__((unused))) {
    return Bindings_new(vec_new(dest), vec_new(dest));
}

void bindings_set_(Bindings * b __attribute__((unused)), char * key __attribute__((unused)), ExprValue value __attribute__((unused)), Arena *dest __attribute__((unused))) {
    (void)(vec_push_(&(((*((Bindings *)(b)))).keys), key));
    (void)(vec_push_(&(((*((Bindings *)(b)))).values), ExprValue_box(dest, value)));
}

ExprValue bindings_get(Bindings * b __attribute__((unused)), char * key __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = vec_len(&(((*((Bindings *)(b)))).keys));
    ExprValue __loop_result_20 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i >= n)) {
        __loop_result_20 = ExprValue_Num(double_box(dest, 0.0));
        break;
        } else {
        if (str_eq_(vec_get(&(((*((Bindings *)(b)))).keys), i), key)) {
        __loop_result_20 = (*((ExprValue *)(vec_get(&(((*((Bindings *)(b)))).values), i))));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_20;
}

Result eval(char * src __attribute__((unused)), Bindings * bindings __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __match_result_16 __attribute__((unused));
    Result __match_tmp_21 = parse_expr(src, 0, dest);
    if (__match_tmp_21.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_21.value;
        __match_result_16 = result_ok(ExprValue_box(dest, eval_tree(&(((*((ExprParseStep *)(step)))).node), bindings, dest)));
    }
    else if (__match_tmp_21.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_21.value;
        __match_result_16 = result_err(e);
    }
    return __match_result_16;
}

ExprValue eval_tree(ExprNode * node __attribute__((unused)), Bindings * bindings __attribute__((unused)), Arena *dest __attribute__((unused))) {
    ExprValue __match_result_17 __attribute__((unused));
    ExprNode __match_tmp_22 = (*((ExprNode *)(node)));
    if (__match_tmp_22.tag == 0) {
        void *v __attribute__((unused)) = __match_tmp_22.value;
        __match_result_17 = ExprValue_Num(v);
    }
    else if (__match_tmp_22.tag == 1) {
        void *v __attribute__((unused)) = __match_tmp_22.value;
        __match_result_17 = ExprValue_Str(v);
    }
    else if (__match_tmp_22.tag == 2) {
        void *name __attribute__((unused)) = __match_tmp_22.value;
        __match_result_17 = bindings_get(bindings, name, dest);
    }
    else if (__match_tmp_22.tag == 3) {
        ExprNode_BinOp_Payload *__match_payload_22 = (ExprNode_BinOp_Payload *)(__match_tmp_22.value);
        char *op __attribute__((unused)) = __match_payload_22->op;
        ExprNode lhs __attribute__((unused)) = __match_payload_22->lhs;
        ExprNode rhs __attribute__((unused)) = __match_payload_22->rhs;
        __match_result_17 = apply_binop(op, eval_tree(&(lhs), bindings, dest), eval_tree(&(rhs), bindings, dest), dest);
    }
    return __match_result_17;
}

ExprValue apply_binop(char * op __attribute__((unused)), ExprValue l __attribute__((unused)), ExprValue r __attribute__((unused)), Arena *dest __attribute__((unused))) {
    double ln __attribute__((unused)) = coerce_num(l);
    double rn __attribute__((unused)) = coerce_num(r);
    return (str_eq_(op, "+") ? ExprValue_Num(double_box(dest, (ln + rn))) : (str_eq_(op, "-") ? ExprValue_Num(double_box(dest, (ln - rn))) : (str_eq_(op, "*") ? ExprValue_Num(double_box(dest, (ln * rn))) : (str_eq_(op, "/") ? ExprValue_Num(double_box(dest, (ln / rn))) : (str_eq_(op, ".") ? ExprValue_Str(concat(coerce_str(l, dest), coerce_str(r, dest), dest)) : ExprValue_Num(double_box(dest, 0.0)))))));
}

double raw_parse_f64(char * s __attribute__((unused))) {
    return (atof(s));
}

double coerce_num(ExprValue v __attribute__((unused))) {
    double __match_result_18 __attribute__((unused));
    ExprValue __match_tmp_23 = v;
    if (__match_tmp_23.tag == 0) {
        void *n __attribute__((unused)) = __match_tmp_23.value;
        __match_result_18 = (*((double *)(n)));
    }
    else if (__match_tmp_23.tag == 1) {
        void *s __attribute__((unused)) = __match_tmp_23.value;
        __match_result_18 = raw_parse_f64(s);
    }
    return __match_result_18;
}

char * coerce_str(ExprValue v __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char * __match_result_19 __attribute__((unused));
    ExprValue __match_tmp_24 = v;
    if (__match_tmp_24.tag == 1) {
        void *s __attribute__((unused)) = __match_tmp_24.value;
        __match_result_19 = s;
    }
    else if (__match_tmp_24.tag == 0) {
        void *n __attribute__((unused)) = __match_tmp_24.value;
        __match_result_19 = f64_to_string((*((double *)(n))), dest);
    }
    return __match_result_19;
}

char * f64_to_string(double v __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (32) + 1);
    snprintf(out, 32, "%g", v);
    return out;
}

double i32_to_f64(int x __attribute__((unused))) {
    return ((double)(x));
}

int is_space_(int c __attribute__((unused))) {
    return (c == 32);
}

int is_alpha_(int c __attribute__((unused))) {
    return (((c >= 65) && (c <= 90)) || ((c >= 97) && (c <= 122)));
}

int is_ident_start_(int c __attribute__((unused))) {
    return (is_alpha_(c) || (c == 95));
}

int is_ident_char_(int c __attribute__((unused))) {
    return (is_ident_start_(c) || is_digit_(c));
}

int is_op_char_(int c __attribute__((unused))) {
    return ((c == 43) || ((c == 45) || ((c == 42) || ((c == 47) || (c == 46)))));
}

int skip_ws(char * src __attribute__((unused)), int pos __attribute__((unused))) {
    int len __attribute__((unused)) = length(src);
    int __loop_result_21 __attribute__((unused));
    int p = pos;
    while (1) {
        if (((p < len) && is_space_(char_at(src, p)))) {
        int __recur_tmp_0 = (p + 1);
        p = __recur_tmp_0;
        continue;
        } else {
        __loop_result_21 = p;
        break;
        }
    }
    return __loop_result_21;
}

ExprParseStep parse_number(char * src __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int len __attribute__((unused)) = length(src);
    ExprParseStep __loop_result_22 __attribute__((unused));
    int p = pos;
    double acc = 0.0;
    while (1) {
        if (((p < len) && is_digit_(char_at(src, p)))) {
        int __recur_tmp_0 = (p + 1);
        double __recur_tmp_1 = ((acc * 10.0) + i32_to_f64((char_at(src, p) - 48)));
        p = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        } else {
        if (((p < len) && (char_at(src, p) == 46))) {
        __loop_result_22 = parse_fraction(src, (p + 1), acc, dest);
        break;
        } else {
        __loop_result_22 = ExprParseStep_new(ExprNode_NumLit(double_box(dest, acc)), p);
        break;
        }
        }
    }
    return __loop_result_22;
}

ExprParseStep parse_fraction(char * src __attribute__((unused)), int pos __attribute__((unused)), double whole __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int len __attribute__((unused)) = length(src);
    ExprParseStep __loop_result_23 __attribute__((unused));
    int p = pos;
    double acc = whole;
    double scale = 0.1;
    while (1) {
        if (((p < len) && is_digit_(char_at(src, p)))) {
        int __recur_tmp_0 = (p + 1);
        double __recur_tmp_1 = (acc + (scale * i32_to_f64((char_at(src, p) - 48))));
        double __recur_tmp_2 = (scale * 0.1);
        p = __recur_tmp_0;
        acc = __recur_tmp_1;
        scale = __recur_tmp_2;
        continue;
        } else {
        __loop_result_23 = ExprParseStep_new(ExprNode_NumLit(double_box(dest, acc)), p);
        break;
        }
    }
    return __loop_result_23;
}

Result parse_string_lit(char * src __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int len __attribute__((unused)) = length(src);
    Result __loop_result_24 __attribute__((unused));
    int p = (pos + 1);
    while (1) {
        if ((p >= len)) {
        __loop_result_24 = result_err(EvalError_box(dest, EvalError_new("unterminated string literal", pos)));
        break;
        } else {
        if ((char_at(src, p) == 34)) {
        __loop_result_24 = result_ok(ExprParseStep_box(dest, ExprParseStep_new(ExprNode_StrLit(substring(src, (pos + 1), p, dest)), (p + 1))));
        break;
        } else {
        int __recur_tmp_0 = (p + 1);
        p = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_24;
}

ExprParseStep parse_ident(char * src __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int len __attribute__((unused)) = length(src);
    ExprParseStep __loop_result_25 __attribute__((unused));
    int p = pos;
    while (1) {
        if (((p < len) && is_ident_char_(char_at(src, p)))) {
        int __recur_tmp_0 = (p + 1);
        p = __recur_tmp_0;
        continue;
        } else {
        __loop_result_25 = ExprParseStep_new(ExprNode_Var(substring(src, pos, p, dest)), p);
        break;
        }
    }
    return __loop_result_25;
}

Result parse_term(char * src __attribute__((unused)), int pos0 __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int pos __attribute__((unused)) = skip_ws(src, pos0);
    int len __attribute__((unused)) = length(src);
    if ((pos >= len)) {
    return result_err(EvalError_box(dest, EvalError_new("unexpected end of expression", pos)));
    } else {
    int c __attribute__((unused)) = char_at(src, pos);
    return (is_digit_(c) ? result_ok(ExprParseStep_box(dest, parse_number(src, pos, dest))) : ((c == 34) ? parse_string_lit(src, pos, dest) : (is_ident_start_(c) ? result_ok(ExprParseStep_box(dest, parse_ident(src, pos, dest))) : result_err(EvalError_box(dest, EvalError_new("unexpected character", pos))))));
    }
}

Result parse_expr(char * src __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __match_result_20 __attribute__((unused));
    Result __match_tmp_25 = parse_term(src, pos, dest);
    if (__match_tmp_25.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_25.value;
        __match_result_20 = result_err(e);
    }
    else if (__match_tmp_25.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_25.value;
        __match_result_20 = parse_expr_rest(src, ((*((ExprParseStep *)(step)))).node, ((*((ExprParseStep *)(step)))).next, dest);
    }
    return __match_result_20;
}

Result parse_expr_rest(char * src __attribute__((unused)), ExprNode lhs __attribute__((unused)), int pos __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int p __attribute__((unused)) = skip_ws(src, pos);
    int len __attribute__((unused)) = length(src);
    if (((p >= len) || (!(is_op_char_(char_at(src, p)))))) {
    return result_ok(ExprParseStep_box(dest, ExprParseStep_new(lhs, pos)));
    } else {
    char *op __attribute__((unused)) = substring(src, p, (p + 1), dest);
    Result __match_result_21 __attribute__((unused));
    Result __match_tmp_26 = parse_term(src, (p + 1), dest);
    if (__match_tmp_26.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_26.value;
        __match_result_21 = result_err(e);
    }
    else if (__match_tmp_26.tag == 1) {
        void *rstep __attribute__((unused)) = __match_tmp_26.value;
        __match_result_21 = parse_expr_rest(src, ExprNode_BinOp(dest, op, lhs, ((*((ExprParseStep *)(rstep)))).node), ((*((ExprParseStep *)(rstep)))).next, dest);
    }
    return __match_result_21;
    }
}

Result run(FileHandle f __attribute__((unused)), AwkProgram * program __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __loop_result_26 __attribute__((unused));
    double nr = 1;
    while (1) {
    Result __match_tmp_27 = read_line(f, dest);
    if (__match_tmp_27.tag == 1) {
        void *opt __attribute__((unused)) = __match_tmp_27.value;
    Option __match_tmp_28 = (*((Option *)(opt)));
    if (__match_tmp_28.tag == 1) {
        void *line __attribute__((unused)) = __match_tmp_28.value;
    (void)(run_rules(&((program)->rules), record_from_line(line, nr, dest), dest));
        double __recur_tmp_0 = (nr + 1);
        nr = __recur_tmp_0;
        continue;
    }
    else if (__match_tmp_28.tag == 0) {
        __loop_result_26 = result_ok(NULL);
        break;
    }
    }
    else if (__match_tmp_27.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_27.value;
        __loop_result_26 = result_err(e);
        break;
    }
    }
    return __loop_result_26;
}

Record record_from_line(char * line __attribute__((unused)), int nr __attribute__((unused)), Arena *dest __attribute__((unused))) {
    return Record_new(split(line, " ", dest), nr);
}

char * join_fields(Record rec __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = vec_len(&((rec).fields));
    if ((n == 0)) {
    return "";
    } else {
    char * __loop_result_27 __attribute__((unused));
    double i = 1;
    char * acc = vec_get(&((rec).fields), 0);
    while (1) {
        if ((i >= n)) {
        __loop_result_27 = acc;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        char * __recur_tmp_1 = concat(concat(acc, " ", dest), vec_get(&((rec).fields), i), dest);
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_27;
    }
}

char * concat_field_name(int i __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (16) + 1);
    snprintf(out, 16, "$%d", i + 1);
    return out;
}

void run_rules(Vec * rules __attribute__((unused)), Record rec __attribute__((unused)), Arena *dest __attribute__((unused))) {
    void * __loop_result_28 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < vec_len(rules))) {
    AwkRule *rule __attribute__((unused)) = vec_get(rules, i);
    Bindings b __attribute__((unused)) = bindings_for(rec, dest);
    if (rule_matches_(rule, rec, dest)) {
        (void)(eval((rule)->action, &(b), dest));
    }
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
}

int unbox_bool(void * b __attribute__((unused))) {
    return (*(int *)b);
}

int rule_matches_(AwkRule * rule __attribute__((unused)), Record rec __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int __match_result_22 __attribute__((unused));
    Option __match_tmp_29 = ((*((AwkRule *)(rule)))).pattern;
    if (__match_tmp_29.tag == 0) {
        __match_result_22 = 1;
    }
    else if (__match_tmp_29.tag == 1) {
        void *re __attribute__((unused)) = __match_tmp_29.value;
    Result __match_tmp_30 = is_match(re, join_fields(rec, dest), dest);
    if (__match_tmp_30.tag == 1) {
        void *m __attribute__((unused)) = __match_tmp_30.value;
        __match_result_22 = unbox_bool(m);
    }
    else if (__match_tmp_30.tag == 0) {
        void *_ __attribute__((unused)) = __match_tmp_30.value;
        __match_result_22 = 0;
    }
    }
    return __match_result_22;
}

Bindings bindings_for(Record rec __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Bindings b __attribute__((unused)) = bindings_new(dest);
    (void)(bindings_set_(&(b), "NR", ExprValue_Num(double_box(dest, i32_to_f64((rec).nr))), dest));
    (void)(bindings_set_(&(b), "NF", ExprValue_Num(double_box(dest, i32_to_f64(vec_len(&((rec).fields))))), dest));
    void * __loop_result_29 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i < vec_len(&((rec).fields)))) {
    (void)(bindings_set_(&(b), concat_field_name(i, dest), ExprValue_Str(vec_get(&((rec).fields), i)), dest));
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return b;
}

