/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    Vec data;
    int rows;
    int cols;
} Base4Matrix;
static inline __attribute__((unused)) Base4Matrix Base4Matrix_new(Vec data, int rows, int cols) {
    Base4Matrix v;
    v.data = data;
    v.rows = rows;
    v.cols = cols;
    return v;
}

int symbol_zero();
int symbol_one();
int symbol_minus();
int symbol_plus();
int base4_xor(int, int);
int base4_and(int, int);
int base4_or(int, int);
int base4_add(int, int);
int base4_subtract(int, int);
int base4_iterate(int, int (*)(int, int), int);
int base4_cycle_length(int, int (*)(int, int));
int rows(Base4Matrix *);
int cols(Base4Matrix *);
int dims_eq(Base4Matrix *, Base4Matrix *);
Option stack2(Vec *, Vec *, Arena *);
int matrix_eq(Base4Matrix *, Base4Matrix *);
Base4Matrix matmul(Base4Matrix *, Base4Matrix *, Arena *);

static inline Base4Matrix *Base4Matrix_box(Arena *dest, Base4Matrix v) {
    Base4Matrix *p = (Base4Matrix *)arena_alloc(dest, sizeof(Base4Matrix));
    *p = v;
    return p;
}

int symbol_zero(void) {
    return 0;
}

int symbol_one(void) {
    return 1;
}

int symbol_minus(void) {
    return 2;
}

int symbol_plus(void) {
    return 3;
}

int base4_xor(int a __attribute__((unused)), int b __attribute__((unused))) {
    return (a ^ b);
}

int base4_and(int a __attribute__((unused)), int b __attribute__((unused))) {
    return (a & b);
}

int base4_or(int a __attribute__((unused)), int b __attribute__((unused))) {
    return (a | b);
}

int base4_add(int a __attribute__((unused)), int b __attribute__((unused))) {
    return ((a + b) % 4);
}

int base4_subtract(int a __attribute__((unused)), int b __attribute__((unused))) {
    return (((a - b) + 4) % 4);
}

int base4_iterate(int start __attribute__((unused)), int (*op)(int, int) __attribute__((unused)), int steps __attribute__((unused))) {
    int __loop_result_0 __attribute__((unused));
    int state = start;
    double i = 0;
    while (1) {
        if ((i >= steps)) {
        __loop_result_0 = state;
        break;
        } else {
        int __recur_tmp_0 = op(state, start);
        double __recur_tmp_1 = (i + 1);
        state = __recur_tmp_0;
        i = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
}

int base4_cycle_length(int start __attribute__((unused)), int (*op)(int, int) __attribute__((unused))) {
    double __loop_result_1 __attribute__((unused));
    int state = op(start, start);
    double i = 1;
    while (1) {
        if ((state == start)) {
        __loop_result_1 = i;
        break;
        } else {
        if ((i >= 5)) {
        __loop_result_1 = -1;
        break;
        } else {
        int __recur_tmp_0 = op(state, start);
        double __recur_tmp_1 = (i + 1);
        state = __recur_tmp_0;
        i = __recur_tmp_1;
        continue;
        }
        }
    }
    return __loop_result_1;
}

int rows(Base4Matrix * m __attribute__((unused))) {
    return (m)->rows;
}

int cols(Base4Matrix * m __attribute__((unused))) {
    return (m)->cols;
}

int dims_eq(Base4Matrix * a __attribute__((unused)), Base4Matrix * b __attribute__((unused))) {
    return ((a)->cols == (b)->rows);
}

Option stack2(Vec * row0 __attribute__((unused)), Vec * row1 __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((!((vec_len(row0) == vec_len(row1))))) {
    return option_none();
    } else {
    int n __attribute__((unused)) = vec_len(row0);
    Vec data __attribute__((unused)) = vec_new(dest);
    void * __loop_result_2 __attribute__((unused));
    double i0 = 0;
    while (1) {
        if ((i0 < n)) {
    (void)(vec_push_(&(data), vec_box_i32(&(data), (*((int *)(vec_get(row0, i0)))))));
        double __recur_tmp_0 = (i0 + 1);
        i0 = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    void * __loop_result_3 __attribute__((unused));
    double i1 = 0;
    while (1) {
        if ((i1 < n)) {
    (void)(vec_push_(&(data), vec_box_i32(&(data), (*((int *)(vec_get(row1, i1)))))));
        double __recur_tmp_0 = (i1 + 1);
        i1 = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return option_some(Base4Matrix_box(dest, Base4Matrix_new(data, 2, n)));
    }
}

int matrix_eq(Base4Matrix * a __attribute__((unused)), Base4Matrix * b __attribute__((unused))) {
    if ((!((((a)->rows == (b)->rows) && ((a)->cols == (b)->cols))))) {
    return 0;
    } else {
    int n __attribute__((unused)) = vec_len(&((a)->data));
    int __loop_result_4 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i >= n)) {
        __loop_result_4 = 1;
        break;
        } else {
        if ((!(((*((int *)(vec_get(&((a)->data), i)))) == (*((int *)(vec_get(&((b)->data), i)))))))) {
        __loop_result_4 = 0;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_4;
    }
}

Base4Matrix matmul(Base4Matrix * a __attribute__((unused)), Base4Matrix * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int out_rows __attribute__((unused)) = (a)->rows;
    int out_cols __attribute__((unused)) = (b)->cols;
    int inner __attribute__((unused)) = (a)->cols;
    Vec out __attribute__((unused)) = vec_new(dest);
    void * __loop_result_5 __attribute__((unused));
    double r = 0;
    while (1) {
        if ((r < out_rows)) {
    void * __loop_result_6 __attribute__((unused));
    double c = 0;
    while (1) {
        if ((c < out_cols)) {
    double __let_val_0 __attribute__((unused));
    double k = 0;
    double acc = 0;
    while (1) {
        if ((k >= inner)) {
        __let_val_0 = acc;
        break;
        } else {
        double __recur_tmp_0 = (k + 1);
        double __recur_tmp_1 = base4_add(acc, base4_and((*((int *)(vec_get(&((a)->data), ((r * inner) + k))))), (*((int *)(vec_get(&((b)->data), ((k * out_cols) + c)))))));
        k = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        }
    }
    double cell __attribute__((unused)) = __let_val_0;
    (void)(vec_push_(&(out), vec_box_f64(&(out), cell)));
        double __recur_tmp_0 = (c + 1);
        c = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
        double __recur_tmp_0 = (r + 1);
        r = __recur_tmp_0;
        continue;
        } else {
            break;
        }
    }
    return Base4Matrix_new(out, out_rows, out_cols);
}

