/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline __attribute__((unused)) ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
char * char_from_code(int, Arena *);
char * i32_to_string(int, Arena *);
int contains_ci_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
double parse_f64_raw(char *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
char * vec_string_at(Vec *, int);
int is_capture_segment_(char *);
int segments_match_(Vec *, Vec *, int, int);
int route_matches_(char *, char *, Arena *);
int find_param_index(Vec *, char *, int, int, Arena *);
char * extract_param(char *, char *, char *, Arena *);

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

char * char_from_code(int code __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (1) + 1);
    out[0] = (char)code; out[1] = '\0';
    return out;
}

char * i32_to_string(int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (16) + 1);
    snprintf(out, 16, "%d", n);
    return out;
}

int contains_ci_(char * haystack __attribute__((unused)), char * needle __attribute__((unused))) {
    return (string_contains_ci_impl(haystack, needle) != 0);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

double parse_f64_raw(char * s __attribute__((unused))) {
    return (strtod(s, NULL));
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    double i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    double start = 0;
    double i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        double __recur_tmp_0 = start;
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

char * vec_string_at(Vec * v __attribute__((unused)), int idx __attribute__((unused))) {
    return ((char *)vec_get(v, idx));
}

int is_capture_segment_(char * seg __attribute__((unused))) {
    return ((length(seg) > 0) && (char_at(seg, 0) == 58));
}

int segments_match_(Vec * pat_segs __attribute__((unused)), Vec * path_segs __attribute__((unused)), int i __attribute__((unused)), int n __attribute__((unused))) {
    if ((i >= n)) {
    return 1;
    } else {
    char *pseg __attribute__((unused)) = vec_string_at(pat_segs, i);
    if (is_capture_segment_(pseg)) {
    return segments_match_(pat_segs, path_segs, (i + 1), n);
    } else {
    if (str_eq_(pseg, vec_string_at(path_segs, i))) {
    return segments_match_(pat_segs, path_segs, (i + 1), n);
    } else {
    return 0;
    }
    }
    }
}

int route_matches_(char * pattern __attribute__((unused)), char * path __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec pat_segs __attribute__((unused)) = split(pattern, "/", dest);
    Vec path_segs __attribute__((unused)) = split(path, "/", dest);
    if ((!((vec_len(&(pat_segs)) == vec_len(&(path_segs)))))) {
    return 0;
    } else {
    return segments_match_(&(pat_segs), &(path_segs), 0, vec_len(&(pat_segs)));
    }
}

int find_param_index(Vec * pat_segs __attribute__((unused)), char * param_name __attribute__((unused)), int i __attribute__((unused)), int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if ((i >= n)) {
    return -1;
    } else {
    char *pseg __attribute__((unused)) = vec_string_at(pat_segs, i);
    if ((is_capture_segment_(pseg) && str_eq_(substring(pseg, 1, length(pseg), dest), param_name))) {
    return i;
    } else {
    return find_param_index(pat_segs, param_name, (i + 1), n, dest);
    }
    }
}

char * extract_param(char * pattern __attribute__((unused)), char * path __attribute__((unused)), char * param_name __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec pat_segs __attribute__((unused)) = split(pattern, "/", dest);
    Vec path_segs __attribute__((unused)) = split(path, "/", dest);
    int idx __attribute__((unused)) = find_param_index(&(pat_segs), param_name, 0, vec_len(&(pat_segs)), dest);
    return vec_string_at(&(path_segs), idx);
}

