/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline __attribute__((unused)) ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

typedef enum {
    TokenType_TAG_TLParen,
    TokenType_TAG_TRParen,
    TokenType_TAG_TLBracket,
    TokenType_TAG_TRBracket,
    TokenType_TAG_TLBrace,
    TokenType_TAG_TRBrace,
    TokenType_TAG_TColon,
    TokenType_TAG_TAt,
    TokenType_TAG_TSymbol,
    TokenType_TAG_TKeyword,
    TokenType_TAG_TString,
    TokenType_TAG_TNumber,
    TokenType_TAG_TEof,
} TokenType_Tag;
typedef struct { TokenType_Tag tag; void *value; } TokenType;
static inline __attribute__((unused)) TokenType TokenType_TLParen(void) { TokenType v; v.tag = TokenType_TAG_TLParen; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TRParen(void) { TokenType v; v.tag = TokenType_TAG_TRParen; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TLBracket(void) { TokenType v; v.tag = TokenType_TAG_TLBracket; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TRBracket(void) { TokenType v; v.tag = TokenType_TAG_TRBracket; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TLBrace(void) { TokenType v; v.tag = TokenType_TAG_TLBrace; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TRBrace(void) { TokenType v; v.tag = TokenType_TAG_TRBrace; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TColon(void) { TokenType v; v.tag = TokenType_TAG_TColon; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TAt(void) { TokenType v; v.tag = TokenType_TAG_TAt; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TSymbol(void) { TokenType v; v.tag = TokenType_TAG_TSymbol; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TKeyword(void) { TokenType v; v.tag = TokenType_TAG_TKeyword; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TString(void) { TokenType v; v.tag = TokenType_TAG_TString; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TNumber(void) { TokenType v; v.tag = TokenType_TAG_TNumber; v.value = NULL; return v; }
static inline __attribute__((unused)) TokenType TokenType_TEof(void) { TokenType v; v.tag = TokenType_TAG_TEof; v.value = NULL; return v; }

typedef struct {
    TokenType kind;
    char * text;
    int line;
} Token;
static inline __attribute__((unused)) Token Token_new(TokenType kind, char * text, int line) {
    Token v;
    v.kind = kind;
    v.text = text;
    v.line = line;
    return v;
}

typedef struct {
    char * src;
    int pos;
    int len;
    int line;
} Lexer;
static inline __attribute__((unused)) Lexer Lexer_new(char * src, int pos, int len, int line) {
    Lexer v;
    v.src = src;
    v.pos = pos;
    v.len = len;
    v.line = line;
    return v;
}

typedef enum {
    LexError_TAG_UnterminatedString,
    LexError_TAG_UnexpectedChar,
} LexError_Tag;
typedef struct { LexError_Tag tag; void *value; } LexError;
static inline __attribute__((unused)) LexError LexError_UnterminatedString(void *value) { LexError v; v.tag = LexError_TAG_UnterminatedString; v.value = value; return v; }
static inline __attribute__((unused)) LexError LexError_UnexpectedChar(void *value) { LexError v; v.tag = LexError_TAG_UnexpectedChar; v.value = value; return v; }

typedef struct {
    Token token;
    Lexer lexer;
} LexStep;
static inline __attribute__((unused)) LexStep LexStep_new(Token token, Lexer lexer) {
    LexStep v;
    v.token = token;
    v.lexer = lexer;
    return v;
}

typedef enum {
    NodeType_TAG_NList,
    NodeType_TAG_NVec,
    NodeType_TAG_NMap,
    NodeType_TAG_NSymbol,
    NodeType_TAG_NKeyword,
    NodeType_TAG_NString,
    NodeType_TAG_NNumber,
    NodeType_TAG_NColon,
    NodeType_TAG_NAt,
} NodeType_Tag;
typedef struct { NodeType_Tag tag; void *value; } NodeType;
static inline __attribute__((unused)) NodeType NodeType_NList(void) { NodeType v; v.tag = NodeType_TAG_NList; v.value = NULL; return v; }
static inline __attribute__((unused)) NodeType NodeType_NVec(void) { NodeType v; v.tag = NodeType_TAG_NVec; v.value = NULL; return v; }
static inline __attribute__((unused)) NodeType NodeType_NMap(void) { NodeType v; v.tag = NodeType_TAG_NMap; v.value = NULL; return v; }
static inline __attribute__((unused)) NodeType NodeType_NSymbol(void) { NodeType v; v.tag = NodeType_TAG_NSymbol; v.value = NULL; return v; }
static inline __attribute__((unused)) NodeType NodeType_NKeyword(void) { NodeType v; v.tag = NodeType_TAG_NKeyword; v.value = NULL; return v; }
static inline __attribute__((unused)) NodeType NodeType_NString(void) { NodeType v; v.tag = NodeType_TAG_NString; v.value = NULL; return v; }
static inline __attribute__((unused)) NodeType NodeType_NNumber(void) { NodeType v; v.tag = NodeType_TAG_NNumber; v.value = NULL; return v; }
static inline __attribute__((unused)) NodeType NodeType_NColon(void) { NodeType v; v.tag = NodeType_TAG_NColon; v.value = NULL; return v; }
static inline __attribute__((unused)) NodeType NodeType_NAt(void) { NodeType v; v.tag = NodeType_TAG_NAt; v.value = NULL; return v; }

typedef struct {
    NodeType kind;
    char * text;
    Vec children;
    int line;
} Node;
static inline __attribute__((unused)) Node Node_new(NodeType kind, char * text, Vec children, int line) {
    Node v;
    v.kind = kind;
    v.text = text;
    v.children = children;
    v.line = line;
    return v;
}

typedef enum {
    SelfhostParseError_TAG_SelfhostParseFailed,
} SelfhostParseError_Tag;
typedef struct { SelfhostParseError_Tag tag; void *value; } SelfhostParseError;
static inline __attribute__((unused)) SelfhostParseError SelfhostParseError_SelfhostParseFailed(void *value) { SelfhostParseError v; v.tag = SelfhostParseError_TAG_SelfhostParseFailed; v.value = value; return v; }

typedef struct {
    Node node;
    Lexer lexer;
    Token cur;
} ParseStep;
static inline __attribute__((unused)) ParseStep ParseStep_new(Node node, Lexer lexer, Token cur) {
    ParseStep v;
    v.node = node;
    v.lexer = lexer;
    v.cur = cur;
    return v;
}

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
char * char_from_code(int, Arena *);
char * i32_to_string(int, Arena *);
int contains_ci_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
double parse_f64_raw(char *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
Lexer new_lexer(char *);
int lx_at_end_(Lexer *);
int lx_peek(Lexer *);
int lx_peek2(Lexer *);
Lexer lx_advance(Lexer *);
int lx_is_whitespace_(int);
int lx_is_symbol_char_(int);
Lexer lx_skip_ws_and_comments(Lexer *);
int lx_scan_symbol_end(Lexer *);
int lx_scan_keyword_end(Lexer *);
int lx_scan_digits_end(char *, int, int);
int lx_looks_like_number_(Lexer *);
int lx_scan_number_end(Lexer *);
Result lex_symbol(Lexer *, Arena *);
Result lex_keyword(Lexer *, Arena *);
Result lex_number(Lexer *, Arena *);
Result lex_string(Lexer *, Arena *);
Result lexer_next(Lexer *, Arena *);
Result tokenize(char *, Arena *);
int kind_code(TokenType);
int is_close_token_(TokenType);
char * close_name(TokenType);
char * join_all(Vec *, Arena *);
SelfhostParseError lex_error_to_parse_error(LexError, Arena *);
Result parse_form(Lexer, Token, Arena *);
Result parse_atom(NodeType, Lexer, Token, Arena *);
Result parse_compound(NodeType, TokenType, int, Lexer, Token, Arena *);
Result parse_program(char *, Arena *);

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

static inline LexStep *LexStep_box(Arena *dest, LexStep v) {
    LexStep *p = (LexStep *)arena_alloc(dest, sizeof(LexStep));
    *p = v;
    return p;
}

static inline LexError *LexError_box(Arena *dest, LexError v) {
    LexError *p = (LexError *)arena_alloc(dest, sizeof(LexError));
    *p = v;
    return p;
}

static inline Token *Token_box(Arena *dest, Token v) {
    Token *p = (Token *)arena_alloc(dest, sizeof(Token));
    *p = v;
    return p;
}

static inline Vec *Vec_box(Arena *dest, Vec v) {
    Vec *p = (Vec *)arena_alloc(dest, sizeof(Vec));
    *p = v;
    return p;
}

static inline SelfhostParseError *SelfhostParseError_box(Arena *dest, SelfhostParseError v) {
    SelfhostParseError *p = (SelfhostParseError *)arena_alloc(dest, sizeof(SelfhostParseError));
    *p = v;
    return p;
}

static inline ParseStep *ParseStep_box(Arena *dest, ParseStep v) {
    ParseStep *p = (ParseStep *)arena_alloc(dest, sizeof(ParseStep));
    *p = v;
    return p;
}

static inline Node *Node_box(Arena *dest, Node v) {
    Node *p = (Node *)arena_alloc(dest, sizeof(Node));
    *p = v;
    return p;
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

char * char_from_code(int code __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (1) + 1);
    out[0] = (char)code; out[1] = '\0';
    return out;
}

char * i32_to_string(int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (16) + 1);
    snprintf(out, 16, "%d", n);
    return out;
}

int contains_ci_(char * haystack __attribute__((unused)), char * needle __attribute__((unused))) {
    return (string_contains_ci_impl(haystack, needle) != 0);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

double parse_f64_raw(char * s __attribute__((unused))) {
    return (strtod(s, NULL));
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    double i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    double start = 0;
    double i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        double __recur_tmp_0 = start;
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

Lexer new_lexer(char * src __attribute__((unused))) {
    return Lexer_new(src, 0, length(src), 1);
}

int lx_at_end_(Lexer * lx __attribute__((unused))) {
    return ((lx)->pos >= (lx)->len);
}

int lx_peek(Lexer * lx __attribute__((unused))) {
    if (lx_at_end_(lx)) {
    return 0;
    } else {
    return char_at((lx)->src, (lx)->pos);
    }
}

int lx_peek2(Lexer * lx __attribute__((unused))) {
    int p __attribute__((unused)) = ((lx)->pos + 1);
    if ((p >= (lx)->len)) {
    return 0;
    } else {
    return char_at((lx)->src, p);
    }
}

Lexer lx_advance(Lexer * lx __attribute__((unused))) {
    int c __attribute__((unused)) = lx_peek(lx);
    return Lexer_new((lx)->src, ((lx)->pos + 1), (lx)->len, ((c == 10) ? ((lx)->line + 1) : (lx)->line));
}

int lx_is_whitespace_(int c __attribute__((unused))) {
    return ((c == 32) || ((c == 9) || ((c == 10) || (c == 13))));
}

int lx_is_symbol_char_(int c __attribute__((unused))) {
    return (lx_is_whitespace_(c) ? 0 : ((c == 40) ? 0 : ((c == 41) ? 0 : ((c == 91) ? 0 : ((c == 93) ? 0 : ((c == 123) ? 0 : ((c == 125) ? 0 : ((c == 58) ? 0 : ((c == 64) ? 0 : ((c == 34) ? 0 : ((c == 59) ? 0 : 1)))))))))));
}

Lexer lx_skip_ws_and_comments(Lexer * lx __attribute__((unused))) {
    char *src __attribute__((unused)) = (lx)->src;
    int len __attribute__((unused)) = (lx)->len;
    Lexer __loop_result_2 __attribute__((unused));
    int pos = (lx)->pos;
    int line = (lx)->line;
    int in_comment = 0;
    while (1) {
        if ((pos >= len)) {
        __loop_result_2 = Lexer_new(src, pos, len, line);
        break;
        } else {
        int c __attribute__((unused)) = char_at(src, pos);
        if (in_comment) {
        if ((c == 10)) {
        int __recur_tmp_0 = pos;
        int __recur_tmp_1 = line;
        int __recur_tmp_2 = 0;
        pos = __recur_tmp_0;
        line = __recur_tmp_1;
        in_comment = __recur_tmp_2;
        continue;
        } else {
        int __recur_tmp_0 = (pos + 1);
        int __recur_tmp_1 = line;
        int __recur_tmp_2 = 1;
        pos = __recur_tmp_0;
        line = __recur_tmp_1;
        in_comment = __recur_tmp_2;
        continue;
        }
        } else {
        if (lx_is_whitespace_(c)) {
        int __recur_tmp_0 = (pos + 1);
        int __recur_tmp_1 = ((c == 10) ? (line + 1) : line);
        int __recur_tmp_2 = 0;
        pos = __recur_tmp_0;
        line = __recur_tmp_1;
        in_comment = __recur_tmp_2;
        continue;
        } else {
        if ((c == 59)) {
        int __recur_tmp_0 = (pos + 1);
        int __recur_tmp_1 = line;
        int __recur_tmp_2 = 1;
        pos = __recur_tmp_0;
        line = __recur_tmp_1;
        in_comment = __recur_tmp_2;
        continue;
        } else {
        __loop_result_2 = Lexer_new(src, pos, len, line);
        break;
        }
        }
        }
        }
    }
    return __loop_result_2;
}

int lx_scan_symbol_end(Lexer * lx __attribute__((unused))) {
    char *src __attribute__((unused)) = (lx)->src;
    int len __attribute__((unused)) = (lx)->len;
    int __loop_result_3 __attribute__((unused));
    int pos = (lx)->pos;
    while (1) {
        if ((pos >= len)) {
        __loop_result_3 = pos;
        break;
        } else {
        if (lx_is_symbol_char_(char_at(src, pos))) {
        int __recur_tmp_0 = (pos + 1);
        pos = __recur_tmp_0;
        continue;
        } else {
        __loop_result_3 = pos;
        break;
        }
        }
    }
    return __loop_result_3;
}

int lx_scan_keyword_end(Lexer * lx __attribute__((unused))) {
    char *src __attribute__((unused)) = (lx)->src;
    int len __attribute__((unused)) = (lx)->len;
    int __loop_result_4 __attribute__((unused));
    int pos = ((lx)->pos + 1);
    while (1) {
        if ((pos >= len)) {
        __loop_result_4 = pos;
        break;
        } else {
        int c __attribute__((unused)) = char_at(src, pos);
        if ((lx_is_symbol_char_(c) || (c == 47))) {
        int __recur_tmp_0 = (pos + 1);
        pos = __recur_tmp_0;
        continue;
        } else {
        __loop_result_4 = pos;
        break;
        }
        }
    }
    return __loop_result_4;
}

int lx_scan_digits_end(char * src __attribute__((unused)), int len __attribute__((unused)), int start __attribute__((unused))) {
    int __loop_result_5 __attribute__((unused));
    int pos = start;
    while (1) {
        if ((pos >= len)) {
        __loop_result_5 = pos;
        break;
        } else {
        if (is_digit_(char_at(src, pos))) {
        int __recur_tmp_0 = (pos + 1);
        pos = __recur_tmp_0;
        continue;
        } else {
        __loop_result_5 = pos;
        break;
        }
        }
    }
    return __loop_result_5;
}

int lx_looks_like_number_(Lexer * lx __attribute__((unused))) {
    int c __attribute__((unused)) = lx_peek(lx);
    return (is_digit_(c) ? 1 : (((c == 45) || (c == 43)) ? is_digit_(lx_peek2(lx)) : 0));
}

int lx_scan_number_end(Lexer * lx __attribute__((unused))) {
    char *src __attribute__((unused)) = (lx)->src;
    int len __attribute__((unused)) = (lx)->len;
    int p0 __attribute__((unused)) = (lx)->pos;
    int c0 __attribute__((unused)) = char_at(src, p0);
    int int_start __attribute__((unused)) = (((c0 == 45) || (c0 == 43)) ? (p0 + 1) : p0);
    int int_end __attribute__((unused)) = lx_scan_digits_end(src, len, int_start);
    if ((int_end >= len)) {
    return int_end;
    } else {
    if (((char_at(src, int_end) == 46) && (((int_end + 1) < len) && is_digit_(char_at(src, (int_end + 1)))))) {
    return lx_scan_digits_end(src, len, (int_end + 1));
    } else {
    return int_end;
    }
    }
}

Result lex_symbol(Lexer * lx __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *src __attribute__((unused)) = (lx)->src;
    int start __attribute__((unused)) = (lx)->pos;
    int line __attribute__((unused)) = (lx)->line;
    int end __attribute__((unused)) = lx_scan_symbol_end(lx);
    char *text __attribute__((unused)) = substring(src, start, end, dest);
    return result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TSymbol(), text, line), Lexer_new(src, end, (lx)->len, line))));
}

Result lex_keyword(Lexer * lx __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *src __attribute__((unused)) = (lx)->src;
    int start __attribute__((unused)) = (lx)->pos;
    int line __attribute__((unused)) = (lx)->line;
    int end __attribute__((unused)) = lx_scan_keyword_end(lx);
    char *text __attribute__((unused)) = substring(src, start, end, dest);
    return result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TKeyword(), text, line), Lexer_new(src, end, (lx)->len, line))));
}

Result lex_number(Lexer * lx __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *src __attribute__((unused)) = (lx)->src;
    int start __attribute__((unused)) = (lx)->pos;
    int line __attribute__((unused)) = (lx)->line;
    int end __attribute__((unused)) = lx_scan_number_end(lx);
    char *text __attribute__((unused)) = substring(src, start, end, dest);
    return result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TNumber(), text, line), Lexer_new(src, end, (lx)->len, line))));
}

Result lex_string(Lexer * lx __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int start_line __attribute__((unused)) = (lx)->line;
    char *src __attribute__((unused)) = (lx)->src;
    int len __attribute__((unused)) = (lx)->len;
    Result __loop_result_6 __attribute__((unused));
    int pos = ((lx)->pos + 1);
    int line = start_line;
    char * acc = "";
    while (1) {
        if ((pos >= len)) {
        __loop_result_6 = result_err(LexError_box(dest, LexError_UnterminatedString(int_box(dest, start_line))));
        break;
        } else {
        int c __attribute__((unused)) = char_at(src, pos);
        if ((c == 34)) {
        __loop_result_6 = result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TString(), acc, start_line), Lexer_new(src, (pos + 1), len, line))));
        break;
        } else {
        if ((c == 92)) {
        if (((pos + 1) >= len)) {
        __loop_result_6 = result_err(LexError_box(dest, LexError_UnterminatedString(int_box(dest, start_line))));
        break;
        } else {
        int e __attribute__((unused)) = char_at(src, (pos + 1));
        int decoded __attribute__((unused)) = ((e == 110) ? 10 : ((e == 116) ? 9 : ((e == 34) ? 34 : ((e == 92) ? 92 : e))));
        int __recur_tmp_0 = (pos + 2);
        int __recur_tmp_1 = line;
        char * __recur_tmp_2 = concat(acc, char_from_code(decoded, dest), dest);
        pos = __recur_tmp_0;
        line = __recur_tmp_1;
        acc = __recur_tmp_2;
        continue;
        }
        } else {
        int __recur_tmp_0 = (pos + 1);
        int __recur_tmp_1 = ((c == 10) ? (line + 1) : line);
        char * __recur_tmp_2 = concat(acc, char_from_code(c, dest), dest);
        pos = __recur_tmp_0;
        line = __recur_tmp_1;
        acc = __recur_tmp_2;
        continue;
        }
        }
        }
    }
    return __loop_result_6;
}

Result lexer_next(Lexer * lx __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Lexer skipped __attribute__((unused)) = lx_skip_ws_and_comments(lx);
    if (lx_at_end_(&(skipped))) {
    return result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TEof(), "", (skipped).line), skipped)));
    } else {
    int line __attribute__((unused)) = (skipped).line;
    int c __attribute__((unused)) = lx_peek(&(skipped));
    return ((c == 40) ? result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TLParen(), "", line), lx_advance(&(skipped))))) : ((c == 41) ? result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TRParen(), "", line), lx_advance(&(skipped))))) : ((c == 91) ? result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TLBracket(), "", line), lx_advance(&(skipped))))) : ((c == 93) ? result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TRBracket(), "", line), lx_advance(&(skipped))))) : ((c == 123) ? result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TLBrace(), "", line), lx_advance(&(skipped))))) : ((c == 125) ? result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TRBrace(), "", line), lx_advance(&(skipped))))) : ((c == 34) ? lex_string(&(skipped), dest) : ((c == 64) ? result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TAt(), "", line), lx_advance(&(skipped))))) : ((c == 58) ? (lx_is_symbol_char_(lx_peek2(&(skipped))) ? lex_keyword(&(skipped), dest) : result_ok(LexStep_box(dest, LexStep_new(Token_new(TokenType_TColon(), "", line), lx_advance(&(skipped)))))) : (lx_looks_like_number_(&(skipped)) ? lex_number(&(skipped), dest) : (lx_is_symbol_char_(c) ? lex_symbol(&(skipped), dest) : result_err(LexError_box(dest, LexError_UnexpectedChar(int_box(dest, line)))))))))))))));
    }
}

Result tokenize(char * src __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec out __attribute__((unused)) = vec_new(dest);
    Result __loop_result_7 __attribute__((unused));
    Lexer lx = new_lexer(src);
    while (1) {
    Result __match_tmp_0 = lexer_next(&(lx), dest);
    if (__match_tmp_0.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_0.value;
        __loop_result_7 = result_err(e);
        break;
    }
    else if (__match_tmp_0.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_0.value;
        Token tok __attribute__((unused)) = ((*((LexStep *)(step)))).token;
        Lexer next_lx __attribute__((unused)) = ((*((LexStep *)(step)))).lexer;
    (void)(vec_push_(&(out), Token_box(dest, tok)));
    TokenType __match_tmp_1 = (tok).kind;
    if (__match_tmp_1.tag == 12) {
        __loop_result_7 = result_ok(Vec_box(dest, out));
        break;
    }
    else if (1) {
        Lexer __recur_tmp_0 = next_lx;
        lx = __recur_tmp_0;
        continue;
    }
    }
    }
    return __loop_result_7;
}

int kind_code(TokenType k __attribute__((unused))) {
    double __match_result_0 __attribute__((unused)) = {0};
    TokenType __match_tmp_2 = k;
    if (__match_tmp_2.tag == 0) {
        __match_result_0 = 0;
    }
    else if (__match_tmp_2.tag == 1) {
        __match_result_0 = 1;
    }
    else if (__match_tmp_2.tag == 2) {
        __match_result_0 = 2;
    }
    else if (__match_tmp_2.tag == 3) {
        __match_result_0 = 3;
    }
    else if (__match_tmp_2.tag == 4) {
        __match_result_0 = 4;
    }
    else if (__match_tmp_2.tag == 5) {
        __match_result_0 = 5;
    }
    else if (__match_tmp_2.tag == 6) {
        __match_result_0 = 6;
    }
    else if (__match_tmp_2.tag == 7) {
        __match_result_0 = 7;
    }
    else if (__match_tmp_2.tag == 8) {
        __match_result_0 = 8;
    }
    else if (__match_tmp_2.tag == 9) {
        __match_result_0 = 9;
    }
    else if (__match_tmp_2.tag == 10) {
        __match_result_0 = 10;
    }
    else if (__match_tmp_2.tag == 11) {
        __match_result_0 = 11;
    }
    else if (__match_tmp_2.tag == 12) {
        __match_result_0 = 12;
    }
    return __match_result_0;
}

int is_close_token_(TokenType k __attribute__((unused))) {
    return ((kind_code(k) == 1) || ((kind_code(k) == 3) || (kind_code(k) == 5)));
}

char * close_name(TokenType k __attribute__((unused))) {
    char * __match_result_1 __attribute__((unused)) = {0};
    TokenType __match_tmp_3 = k;
    if (__match_tmp_3.tag == 1) {
        __match_result_1 = ")";
    }
    else if (__match_tmp_3.tag == 3) {
        __match_result_1 = "]";
    }
    else if (__match_tmp_3.tag == 5) {
        __match_result_1 = "}";
    }
    else if (1) {
        __match_result_1 = "?";
    }
    return __match_result_1;
}

char * join_all(Vec * parts __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char * __loop_result_8 __attribute__((unused));
    double i = 0;
    char * acc = "";
    while (1) {
        if ((i >= vec_len(parts))) {
        __loop_result_8 = acc;
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        char * __recur_tmp_1 = concat(acc, vec_get(parts, i), dest);
        i = __recur_tmp_0;
        acc = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_8;
}

SelfhostParseError lex_error_to_parse_error(LexError e __attribute__((unused)), Arena *dest __attribute__((unused))) {
    SelfhostParseError __match_result_2 __attribute__((unused)) = {0};
    LexError __match_tmp_4 = e;
    if (__match_tmp_4.tag == 0) {
        void *line __attribute__((unused)) = __match_tmp_4.value;
        Vec parts __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(parts), "unterminated string literal (opened at line "));
    (void)(vec_push_(&(parts), i32_to_string((*((int *)(line))), dest)));
    (void)(vec_push_(&(parts), ")"));
        __match_result_2 = SelfhostParseError_SelfhostParseFailed(join_all(&(parts), dest));
    }
    else if (__match_tmp_4.tag == 1) {
        void *line __attribute__((unused)) = __match_tmp_4.value;
        Vec parts __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(parts), "unexpected character at line "));
    (void)(vec_push_(&(parts), i32_to_string((*((int *)(line))), dest)));
        __match_result_2 = SelfhostParseError_SelfhostParseFailed(join_all(&(parts), dest));
    }
    return __match_result_2;
}

Result parse_form(Lexer lx __attribute__((unused)), Token cur __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Result __match_result_3 __attribute__((unused)) = {0};
    TokenType __match_tmp_5 = (cur).kind;
    if (__match_tmp_5.tag == 0) {
        __match_result_3 = parse_compound(NodeType_NList(), TokenType_TRParen(), (cur).line, lx, cur, dest);
    }
    else if (__match_tmp_5.tag == 2) {
        __match_result_3 = parse_compound(NodeType_NVec(), TokenType_TRBracket(), (cur).line, lx, cur, dest);
    }
    else if (__match_tmp_5.tag == 4) {
        __match_result_3 = parse_compound(NodeType_NMap(), TokenType_TRBrace(), (cur).line, lx, cur, dest);
    }
    else if (__match_tmp_5.tag == 8) {
        __match_result_3 = parse_atom(NodeType_NSymbol(), lx, cur, dest);
    }
    else if (__match_tmp_5.tag == 9) {
        __match_result_3 = parse_atom(NodeType_NKeyword(), lx, cur, dest);
    }
    else if (__match_tmp_5.tag == 10) {
        __match_result_3 = parse_atom(NodeType_NString(), lx, cur, dest);
    }
    else if (__match_tmp_5.tag == 11) {
        __match_result_3 = parse_atom(NodeType_NNumber(), lx, cur, dest);
    }
    else if (__match_tmp_5.tag == 6) {
        __match_result_3 = parse_atom(NodeType_NColon(), lx, cur, dest);
    }
    else if (__match_tmp_5.tag == 7) {
        __match_result_3 = parse_atom(NodeType_NAt(), lx, cur, dest);
    }
    else if (1) {
        if (is_close_token_((cur).kind)) {
        Vec parts __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(parts), "unexpected '"));
    (void)(vec_push_(&(parts), close_name((cur).kind)));
    (void)(vec_push_(&(parts), "' with no matching open bracket at line "));
    (void)(vec_push_(&(parts), i32_to_string((cur).line, dest)));
        __match_result_3 = result_err(SelfhostParseError_box(dest, SelfhostParseError_SelfhostParseFailed(join_all(&(parts), dest))));
        } else {
        Vec parts __attribute__((unused)) = vec_new(dest);
    (void)(vec_push_(&(parts), "unexpected end of file, expected a form at line "));
    (void)(vec_push_(&(parts), i32_to_string((cur).line, dest)));
        __match_result_3 = result_err(SelfhostParseError_box(dest, SelfhostParseError_SelfhostParseFailed(join_all(&(parts), dest))));
        }
    }
    return __match_result_3;
}

Result parse_atom(NodeType kind __attribute__((unused)), Lexer lx __attribute__((unused)), Token cur __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Node node __attribute__((unused)) = Node_new(kind, (cur).text, vec_new(dest), (cur).line);
    Result __match_result_4 __attribute__((unused)) = {0};
    Result __match_tmp_6 = lexer_next(&(lx), dest);
    if (__match_tmp_6.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_6.value;
        __match_result_4 = result_err(SelfhostParseError_box(dest, lex_error_to_parse_error((*((LexError *)(e))), dest)));
    }
    else if (__match_tmp_6.tag == 1) {
        void *step __attribute__((unused)) = __match_tmp_6.value;
        __match_result_4 = result_ok(ParseStep_box(dest, ParseStep_new(node, ((*((LexStep *)(step)))).lexer, ((*((LexStep *)(step)))).token)));
    }
    return __match_result_4;
}

Result parse_compound(NodeType kind __attribute__((unused)), TokenType close_tag __attribute__((unused)), int open_line __attribute__((unused)), Lexer lx __attribute__((unused)), Token cur __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec children __attribute__((unused)) = vec_new(dest);
    Result __match_result_5 __attribute__((unused)) = {0};
    Result __match_tmp_7 = lexer_next(&(lx), dest);
    if (__match_tmp_7.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_7.value;
        __match_result_5 = result_err(SelfhostParseError_box(dest, lex_error_to_parse_error((*((LexError *)(e))), dest)));
    }
    else if (__match_tmp_7.tag == 1) {
        void *step0 __attribute__((unused)) = __match_tmp_7.value;
    Lexer lx2 = ((*((LexStep *)(step0)))).lexer;
    Token cur2 = ((*((LexStep *)(step0)))).token;
    while (1) {
        if ((kind_code((cur2).kind) == kind_code(close_tag))) {
    Result __match_tmp_8 = lexer_next(&(lx2), dest);
    if (__match_tmp_8.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_8.value;
        __match_result_5 = result_err(SelfhostParseError_box(dest, lex_error_to_parse_error((*((LexError *)(e))), dest)));
        break;
    }
    else if (__match_tmp_8.tag == 1) {
        void *stepc __attribute__((unused)) = __match_tmp_8.value;
        __match_result_5 = result_ok(ParseStep_box(dest, ParseStep_new(Node_new(kind, "", children, open_line), ((*((LexStep *)(stepc)))).lexer, ((*((LexStep *)(stepc)))).token)));
        break;
    }
        } else {
        if ((kind_code((cur2).kind) == 12)) {
        Vec parts __attribute__((unused)) = vec_new(dest);
        (void)(vec_push_(&(parts), "unterminated form: expected '"));
        (void)(vec_push_(&(parts), close_name(close_tag)));
        (void)(vec_push_(&(parts), "' to close the form opened at line "));
        (void)(vec_push_(&(parts), i32_to_string(open_line, dest)));
        __match_result_5 = result_err(SelfhostParseError_box(dest, SelfhostParseError_SelfhostParseFailed(join_all(&(parts), dest))));
        break;
        } else {
        if (is_close_token_((cur2).kind)) {
        Vec parts __attribute__((unused)) = vec_new(dest);
        (void)(vec_push_(&(parts), "mismatched bracket: expected '"));
        (void)(vec_push_(&(parts), close_name(close_tag)));
        (void)(vec_push_(&(parts), "' but found '"));
        (void)(vec_push_(&(parts), close_name((cur2).kind)));
        (void)(vec_push_(&(parts), "' at line "));
        (void)(vec_push_(&(parts), i32_to_string((cur2).line, dest)));
        __match_result_5 = result_err(SelfhostParseError_box(dest, SelfhostParseError_SelfhostParseFailed(join_all(&(parts), dest))));
        break;
        } else {
    Result __match_tmp_9 = parse_form(lx2, cur2, dest);
    if (__match_tmp_9.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_9.value;
        __match_result_5 = result_err(e);
        break;
    }
    else if (__match_tmp_9.tag == 1) {
        void *childstep __attribute__((unused)) = __match_tmp_9.value;
    (void)(vec_push_(&(children), Node_box(dest, ((*((ParseStep *)(childstep)))).node)));
        Lexer __recur_tmp_0 = ((*((ParseStep *)(childstep)))).lexer;
        Token __recur_tmp_1 = ((*((ParseStep *)(childstep)))).cur;
        lx2 = __recur_tmp_0;
        cur2 = __recur_tmp_1;
        continue;
    }
        }
        }
        }
    }
    }
    return __match_result_5;
}

Result parse_program(char * src __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Lexer lx0 __attribute__((unused)) = new_lexer(src);
    Vec children __attribute__((unused)) = vec_new(dest);
    Result __match_result_6 __attribute__((unused)) = {0};
    Result __match_tmp_10 = lexer_next(&(lx0), dest);
    if (__match_tmp_10.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_10.value;
        __match_result_6 = result_err(SelfhostParseError_box(dest, lex_error_to_parse_error((*((LexError *)(e))), dest)));
    }
    else if (__match_tmp_10.tag == 1) {
        void *step0 __attribute__((unused)) = __match_tmp_10.value;
    Lexer lx2 = ((*((LexStep *)(step0)))).lexer;
    Token cur2 = ((*((LexStep *)(step0)))).token;
    while (1) {
        if ((kind_code((cur2).kind) == 12)) {
        __match_result_6 = result_ok(Node_box(dest, Node_new(NodeType_NList(), "", children, 1)));
        break;
        } else {
        if (is_close_token_((cur2).kind)) {
        Vec parts __attribute__((unused)) = vec_new(dest);
        (void)(vec_push_(&(parts), "unexpected '"));
        (void)(vec_push_(&(parts), close_name((cur2).kind)));
        (void)(vec_push_(&(parts), "' with no matching open bracket at line "));
        (void)(vec_push_(&(parts), i32_to_string((cur2).line, dest)));
        __match_result_6 = result_err(SelfhostParseError_box(dest, SelfhostParseError_SelfhostParseFailed(join_all(&(parts), dest))));
        break;
        } else {
    Result __match_tmp_11 = parse_form(lx2, cur2, dest);
    if (__match_tmp_11.tag == 0) {
        void *e __attribute__((unused)) = __match_tmp_11.value;
        __match_result_6 = result_err(e);
        break;
    }
    else if (__match_tmp_11.tag == 1) {
        void *childstep __attribute__((unused)) = __match_tmp_11.value;
    (void)(vec_push_(&(children), Node_box(dest, ((*((ParseStep *)(childstep)))).node)));
        Lexer __recur_tmp_0 = ((*((ParseStep *)(childstep)))).lexer;
        Token __recur_tmp_1 = ((*((ParseStep *)(childstep)))).cur;
        lx2 = __recur_tmp_0;
        cur2 = __recur_tmp_1;
        continue;
    }
        }
        }
    }
    }
    return __match_result_6;
}

