/* Generated by parena build -- VS0 domain 3, do not edit by hand. */
#include "parena_runtime.h"
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <math.h>

typedef struct {
    char * message;
} ParseError;
static inline __attribute__((unused)) ParseError ParseError_new(char * message) {
    ParseError v;
    v.message = message;
    return v;
}

typedef struct {
    char * name;
    char * value;
} AmiHeader;
static inline __attribute__((unused)) AmiHeader AmiHeader_new(char * name, char * value) {
    AmiHeader v;
    v.name = name;
    v.value = value;
    return v;
}

typedef enum {
    AmiError_TAG_MalformedHeaderLine,
} AmiError_Tag;
typedef struct { AmiError_Tag tag; void *value; } AmiError;
static inline __attribute__((unused)) AmiError AmiError_MalformedHeaderLine(void) { AmiError v; v.tag = AmiError_TAG_MalformedHeaderLine; v.value = NULL; return v; }

int length(char *);
int char_at(char *, int);
int str_eq_(char *, char *);
char * char_from_code(int, Arena *);
char * i32_to_string(int, Arena *);
int contains_ci_(char *, char *);
int is_digit_(int);
char * substring(char *, int, int, Arena *);
int raw_parse_i32(char *);
Result parse_i32(char *, Arena *);
double parse_f64_raw(char *);
int starts_with_sign_(char *);
int is_valid_i32_text_(char *);
char * concat(char *, char *, Arena *);
Vec split(char *, char *, Arena *);
int find_crlf(char *, int, int);
int find_char(char *, int, int, int);
Result parse_message(char *, Arena *);
Option header_value(Vec *, char *);
char * build_login_action(char *, char *, Arena *);

static inline int *int_box(Arena *dest, int v) {
    int *p = (int *)arena_alloc(dest, sizeof(int));
    *p = v;
    return p;
}

static inline ParseError *ParseError_box(Arena *dest, ParseError v) {
    ParseError *p = (ParseError *)arena_alloc(dest, sizeof(ParseError));
    *p = v;
    return p;
}

static inline Vec *Vec_box(Arena *dest, Vec v) {
    Vec *p = (Vec *)arena_alloc(dest, sizeof(Vec));
    *p = v;
    return p;
}

static inline AmiError *AmiError_box(Arena *dest, AmiError v) {
    AmiError *p = (AmiError *)arena_alloc(dest, sizeof(AmiError));
    *p = v;
    return p;
}

static inline AmiHeader *AmiHeader_box(Arena *dest, AmiHeader v) {
    AmiHeader *p = (AmiHeader *)arena_alloc(dest, sizeof(AmiHeader));
    *p = v;
    return p;
}

int length(char * s __attribute__((unused))) {
    return ((int32_t)strlen(s));
}

int char_at(char * s __attribute__((unused)), int i __attribute__((unused))) {
    return ((int32_t)s[i]);
}

int str_eq_(char * a __attribute__((unused)), char * b __attribute__((unused))) {
    return (strcmp(a, b) == 0);
}

char * char_from_code(int code __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (1) + 1);
    out[0] = (char)code; out[1] = '\0';
    return out;
}

char * i32_to_string(int n __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, (16) + 1);
    snprintf(out, 16, "%d", n);
    return out;
}

int contains_ci_(char * haystack __attribute__((unused)), char * needle __attribute__((unused))) {
    return (string_contains_ci_impl(haystack, needle) != 0);
}

int is_digit_(int c __attribute__((unused))) {
    return ((c >= 48) && (c <= 57));
}

char * substring(char * s __attribute__((unused)), int start __attribute__((unused)), int end __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((end - start)) + 1);
    memcpy(out, s + start, end - start); out[end - start] = '\0';
    return out;
}

int raw_parse_i32(char * s __attribute__((unused))) {
    return (atoi(s));
}

Result parse_i32(char * s __attribute__((unused)), Arena *dest __attribute__((unused))) {
    if (is_valid_i32_text_(s)) {
    return result_ok(int_box(dest, raw_parse_i32(s)));
    } else {
    return result_err(ParseError_box(dest, ParseError_new("not a valid integer")));
    }
}

double parse_f64_raw(char * s __attribute__((unused))) {
    return (strtod(s, NULL));
}

int starts_with_sign_(char * s __attribute__((unused))) {
    return ((char_at(s, 0) == 45) || (char_at(s, 0) == 43));
}

int is_valid_i32_text_(char * s __attribute__((unused))) {
    int n __attribute__((unused)) = length(s);
    if ((n == 0)) {
    return 0;
    } else {
    int __loop_result_0 __attribute__((unused));
    double i = (starts_with_sign_(s) ? 1 : 0);
    int ok = 1;
    while (1) {
        if ((i >= n)) {
        __loop_result_0 = (ok && (n > (starts_with_sign_(s) ? 1 : 0)));
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        int __recur_tmp_1 = (ok && is_digit_(char_at(s, i)));
        i = __recur_tmp_0;
        ok = __recur_tmp_1;
        continue;
        }
    }
    return __loop_result_0;
    }
}

char * concat(char * a __attribute__((unused)), char * b __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *out __attribute__((unused)) = (char *)arena_alloc(dest, ((length(a) + length(b))) + 1);
    strcpy(out, a); strcat(out, b);
    return out;
}

Vec split(char * s __attribute__((unused)), char * sep __attribute__((unused)), Arena *dest __attribute__((unused))) {
    Vec result __attribute__((unused)) = vec_new(dest);
    Vec __loop_result_1 __attribute__((unused));
    double start = 0;
    double i = 0;
    int n = length(s);
    while (1) {
        if ((i >= n)) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        __loop_result_1 = result;
        break;
        } else {
        if ((char_at(s, i) == char_at(sep, 0))) {
        (void)(vec_push_(&(result), substring(s, start, i, dest)));
        double __recur_tmp_0 = (i + 1);
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        } else {
        double __recur_tmp_0 = start;
        double __recur_tmp_1 = (i + 1);
        int __recur_tmp_2 = n;
        start = __recur_tmp_0;
        i = __recur_tmp_1;
        n = __recur_tmp_2;
        continue;
        }
        }
    }
    return __loop_result_1;
}

int find_crlf(char * s __attribute__((unused)), int start __attribute__((unused)), int n __attribute__((unused))) {
    int __loop_result_2 __attribute__((unused));
    int i = start;
    while (1) {
        if ((i >= (n - 1))) {
        __loop_result_2 = n;
        break;
        } else {
        if (((char_at(s, i) == 13) && (char_at(s, (i + 1)) == 10))) {
        __loop_result_2 = i;
        break;
        } else {
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_2;
}

int find_char(char * s __attribute__((unused)), int start __attribute__((unused)), int n __attribute__((unused)), int target __attribute__((unused))) {
    int __loop_result_3 __attribute__((unused));
    int i = start;
    while (1) {
        if ((i >= n)) {
        __loop_result_3 = n;
        break;
        } else {
        if ((char_at(s, i) == target)) {
        __loop_result_3 = i;
        break;
        } else {
        int __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_3;
}

Result parse_message(char * raw __attribute__((unused)), Arena *dest __attribute__((unused))) {
    int n __attribute__((unused)) = length(raw);
    Vec headers __attribute__((unused)) = vec_new(dest);
    Result __loop_result_4 __attribute__((unused));
    double i = 0;
    while (1) {
        int line_end __attribute__((unused)) = find_crlf(raw, i, n);
        if ((i >= n)) {
        __loop_result_4 = result_ok(Vec_box(dest, headers));
        break;
        } else {
        if ((line_end == i)) {
        __loop_result_4 = result_ok(Vec_box(dest, headers));
        break;
        } else {
        int colon __attribute__((unused)) = find_char(raw, i, line_end, 58);
        if ((colon >= line_end)) {
        __loop_result_4 = result_err(AmiError_box(dest, AmiError_MalformedHeaderLine()));
        break;
        } else {
        char *hname __attribute__((unused)) = substring(raw, i, colon, dest);
        char *hval __attribute__((unused)) = substring(raw, (colon + 2), line_end, dest);
        (void)(vec_push_(&(headers), AmiHeader_box(dest, AmiHeader_new(hname, hval))));
        double __recur_tmp_0 = (line_end + 2);
        i = __recur_tmp_0;
        continue;
        }
        }
        }
    }
    return __loop_result_4;
}

Option header_value(Vec * headers __attribute__((unused)), char * name __attribute__((unused))) {
    Option __loop_result_5 __attribute__((unused));
    double i = 0;
    while (1) {
        if ((i >= vec_len(headers))) {
        __loop_result_5 = option_none();
        break;
        } else {
        AmiHeader *h __attribute__((unused)) = vec_get(headers, i);
        if (str_eq_((h)->name, name)) {
        __loop_result_5 = option_some((h)->value);
        break;
        } else {
        double __recur_tmp_0 = (i + 1);
        i = __recur_tmp_0;
        continue;
        }
        }
    }
    return __loop_result_5;
}

char * build_login_action(char * username __attribute__((unused)), char * secret __attribute__((unused)), Arena *dest __attribute__((unused))) {
    char *p1 __attribute__((unused)) = "Action: Login\r\nUsername: ";
    char *p2 __attribute__((unused)) = concat(p1, username, dest);
    char *p3 __attribute__((unused)) = concat(p2, "\r\nSecret: ", dest);
    char *p4 __attribute__((unused)) = concat(p3, secret, dest);
    return concat(p4, "\r\n\r\n", dest);
}

