/* examples/avr/blink_main_llvm.c — the real "direct AVR route" host (2026-09-10,
 * `docs/LLVM_BACKEND_NORTHSTAR.md`'s own Phase 3 v0): unlike `blink_main.c` (which `#include`s
 * `blink_gen.c` — plain C generated by `parena build`'s C target), this file links against
 * `next_led_state` as a SEPARATELY-COMPILED object file: `parena build examples/avr/blink.prn -o
 * blink.ll` emits real LLVM IR text directly (`src/emit_llvm.c` — no C, no clang C-frontend
 * involvement in the decision-logic path at all), then `llc -mtriple=avr -mcpu=atmega328p
 * -filetype=obj blink.ll -o blink_llvm.o` lowers that IR straight to real AVR machine code. This
 * host file just needs an `extern` declaration to call it — there's nothing to `#include`, the
 * function body doesn't exist as C text anywhere in this build.
 *
 * Real, load-bearing ABI detail, found and verified by actually disassembling the emitted object
 * file (`avr-objdump -d`), not assumed: `emit_llvm.c` maps PARENA's `Bool` to LLVM's `i1`, and
 * AVR's own default C calling convention passes/returns an `i1`-typed value in exactly ONE 8-bit
 * register (r24) — NOT a 16-bit `int` (which would occupy the r24:r25 PAIR). Declaring this
 * extern as `int next_led_state(int)` (matching `blink_main.c`'s own C-target prototype) would be
 * a real, silent ABI mismatch — the C caller would read/write a phantom high byte (r25) the real
 * function never touches. `unsigned char` is the genuinely correct, real, single-register match.
 */
#include <avr/io.h>
#include <util/delay_basic.h>

extern unsigned char next_led_state(unsigned char);

int main(void) {
    DDRB |= (1 << PB5);
    unsigned char led_on = 0;
    for (;;) {
        led_on = next_led_state(led_on);
        if (led_on) { PORTB |= (1 << PB5); } else { PORTB &= (uint8_t)~(1 << PB5); }
        for (int i = 0; i < 100; i++) {
            _delay_loop_2(60000);
        }
    }
    return 0;
}
